### ISSUE TITLE
Cambios en Diseño Sitio Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#1]
Fede, te paso cambios para el sitio:
1. Agregar feed de Facebook
2. Cambiar el background por un pleno que lo haga parecer más moderno al sitio
3. Que la Galería sea con ventanas más modernas y que se puedan modificar los contenidos más fácilmente. Se nos ocurrió que podemos usar Pinterest. Cómo lo ves?

**Comment by FAAREIA** [comment]
1- Seguro? Me dijeron de sacarlo hace poco.
2- ¿Cuál background? Me parece que estan bien los fondos, pero igualmente un cambio de fondo solamente no va a transformarlo en algo nuevo / moderno.
3- Puede funcionar, pero sepan que la foto grande la van a ver en pinterest y no dentro del sitio. Con pinterest no hay ventanas emergentes que se puedan cerrar como ahora o que se pueda navegar entre foto y foto. Lo que se puede hacer es cambiar las fotos y hacerlo similar a pinterest

**Comment by LeandroBraier** [comment]
1- Lo hable con Eze en la reunión de ayer. Quien te habia pedido sacarlo?

2- lo se, pero ayuda.

3- ok, pasanos una propuesta simil pinterest entonces.

Gracias!

**Comment by FAAREIA** [comment]
1- Eze me lo había dicho =/
2- Ok, qué fondo/s decis?
3- Ok

**Comment by LeandroBraier** [comment]
1- OK, lo hablé con él. Volvelo a colocar al feed, debe haber habido un mal
entendido porque él me dijo: "Yo lo había visto al feed y ahora no está" A
mi también me parecía haberlo visto.

2- Fondo pleno del mismo tono gris O fondo tal como está en graduación del
color pero sin los ladrillos.
1. Genial.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_btv2/index.html
Hola Lea, ahi esta la actualización. Las fotos las reordené y las encuadré diferente. Suma también que ocupa menos espacio en lo vertical la sección.
También solucioné un bug de las fotos corridas cuando se bajaba antes de que se cargara el sitio.

Avisame y decime
Si está OK, quedaría pasar a responsivo las actualizaciones que se fueron haciendo.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Ya se lo paso a Eze para que le de el OK y me pase las 3 fotos que hay que
cambiar en la sección Entretenimiento + COmunicación.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-25 16:44 GMT-03:00 Federico Arena notifications@github.com:
