### ISSUE TITLE
Favicon Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#10]
Para cuando tengas tiempo. Recuerdo que esto lo había puesto dentro de la estrategia de SEO pero nunca lo hablamos. 

Me imagino un pajaro benteveo como el del logo pero simplificado, con una B grande adentro. 

*UPDATE: Perdón, creo que con el pájaro solo simplicado negro y beige como el del logo estamos bien.

**Comment by FAAREIA** [comment]
Me lo podes conseguir en vector? Los que tengo son img y al escalarlo se rompe feo.

**Comment by LeandroBraier** [comment]
Dale, consulto con Eze

**Comment by LeandroBraier** [comment]
Buen día Fede!

Te lo conseguí, lo tenés en la carpeta PATY MAQUETADOR/ BENTEVEO MAQUETADOR.

abrazo

**Comment by FAAREIA** [comment]
Joya Lea, ahi estoy cerrando con MK lo del mail de las landing. Por otra
parte, hoy voy a estar hasta las 11 trabajando, después tengo un
compromiso. Pedime lo que todo lo que haya, ahora ^^

**Comment by LeandroBraier** [comment]
Gracias por avisar Fede!

Si cerramos el mailing y ya lo ponemos a funcionar automáticamente como
respuesta para todos los mails que nos llegan a la landing del casting ya
estamos por hoy. Yo te voy a pasar pedidos a la tarde pero son para la
semana que viene.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-26 8:48 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, avancemos con esto hoy entonces.

abrazo

**Comment by FAAREIA** [comment]
Justo estaba con eso Lea, fijate las posibilidades:
http://www.benteveo.tv/_btv1/index.html
http://www.benteveo.tv/_btv1/index-2.html
http://www.benteveo.tv/_btv1/index-3.html

El color de fondo en el favicon creo que no va, no le suma a la nitidez del pájaro

**Comment by LeandroBraier** [comment]
Hermoso Fede!

Vamos con el index-3, que tiene el iso completo. Muy bueno quedó! Se ve con
definición perfecta. Cómo hiciste?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si? Los ves mejores que los otros?
Simplemente lo hice 32x32, en vez de 16x16. Qué modelo de mac tenes? Quiero
ver si tu modelo tiene algo estilo retina.

**Comment by LeandroBraier** [comment]
Si, es MacBook Pro Retina 15 pulgadas la mia.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-29 11:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Te parece que en función de esto de Benteveo podremos mejorar los favicons
de Danica y Paty?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-29 11:34 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Si dale, les duplico el tamaño.
Con razón ves mal las cosas que yo veo bien! No sabía que estaba en macbook también, pensé que solo en algunos modelos de dispositivos móviles.

Ya esta aplicado el favicon de btv

**Comment by LeandroBraier** [comment]
Genial. Cambiemos el nombre del sitio de "Benteveo Producciones
Audiovisuales" a "Benteveo Argentina" por ahora. Va a quedar mejor más
corto también y ayuda al SEO de "productora audiovisual argentina".

Dupliquemos el tamaño a los Favicons de Dánica, Paty y Patyviena también
entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-29 11:37 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi los actualicé a todos. Cualquier cosa dale F5.
Lo del Título en benteveo, también está.

**Comment by LeandroBraier** [comment]
Quedó perfecto, Fede. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
