### ISSUE TITLE
Mailing Casting Storydoing

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#11]
Fede, necesito que armes para mañana un mailing para enviarle a los que se suscriben al casting.

Armalo con la estética de la landing nomás. El texto es:

"¡Gracias por participar del casting de nuestro próximo show! Recibimos tus materiales y estaremos analizando tu perfil. 

Por favor mantenete al tanto de todas las novedades del casting siguiendo nuestro muro en Facebook. (con link a http://www.facebook.com/BenteveoProducciones)."

abrazo

**Comment by LeandroBraier** [comment]
Fede,no recibí nada de esto. Cómo venís? Lo necesitamos bastante urgente.

**Comment by FAAREIA** [comment]
Hola Lea, recien lo leo, nunca me llegó el mail de github. Ahi me lo pongo a hacer.

**Comment by FAAREIA** [comment]
Es para mandar al email del suscripto no?

**Comment by LeandroBraier** [comment]
Si, exacto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día Fede!

Cómo quedó el mailing? Ya está funcional?

Solo para confirmar.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ya esta funcionando. Probate una landing asi ves como envia el
email.

**Comment by LeandroBraier** [comment]
Jaja te estás confundiendo vos como me pasó a mi el otro. Este mailing es
el del Casting, no el de las Landing de las marcas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
jajaja, muy confunso! Si, esta listo. Fijate en la versión online, te lo
adjunto igual.
http://www.benteveo.tv/mailing/storydoing-tv/storydoing-tv.html

Abrazooo

2014-09-29 10:31 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Genial, Fede! Cierro el ticket entonces.

abrazo
