### ISSUE TITLE
Mailing Casting Storydoing Versión Manual

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#12]
Fede, necesitaría mandarle manualmente el mailing a todos los que no lo recibieron automáticamente. Tengo la lista completa de mails de los que se subscribieron pero no tengo las fechas. ¿Tenemos alguna forma de saber cuáles ya recibieron el mailing y cuales no?

**Comment by FAAREIA** [comment]
No se bien como es que envian los emails, capas que la herramienta que usan tiene un historial de los enviados. Caso contrario, lo que se podría hacer es ver el mail de suscripción y fijarse la fecha en que llegó para saber si fue incluido o no en el envío automático

**Comment by LeandroBraier** [comment]
El tema es que no tengo acceso a esa cuenta de mail. No sé por qué Eze no me da acceso. ¿No hay forma de ver el historial de esa herramienta entonces? ¿Le preguntamos a MK?

**Comment by FAAREIA** [comment]
Sin la clave no podemos acceder ni desde el webmail ni desde el panel de control del sitio. Fijate si Eze te puede exportar los mails que tengan el asunto del casting.

**Comment by FAAREIA** [comment]
La herramienta del mailing esta en una pc o en el hosting de benteveo? Le preguntaste a MK?
Capas que algo se puede hacer.

**Comment by LeandroBraier** [comment]
La verdad no sé Fede, eso lo debe saber MK.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-01 9:07 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahora le pregunto
