### ISSUE TITLE
Enroque del orden de la cartelera de redes sociales

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#13]
Fede, quedó muy buena la cartelera de redes. Necesitamos que quede más arriba dentro del sitio. Puntualmente, arriba de la parte de Hombres Pájaro. Me habías cuando lo pudiste impactar?

Gracias.

**Comment by FAAREIA** [comment]
Vos decis la parte de "VOLAMOS, cuanto más alto mejor..." ?

**Comment by LeandroBraier** [comment]
Sip.

**Comment by FAAREIA** [comment]
Ok, mañana me pongo con eso y agrego unas fotos más de instagram.
Pregunta: ¿le dejo el fondo a la sección y que corte o le pongo el fondo blanco y que quede todo unido?

**Comment by LeandroBraier** [comment]
Que quede todo unido.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-02 14:40 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_btv4/
Ahi esta el cambio de ubicación + 4 fotos más a lo de instagram.
Cuando suban 4 fotos más al instagram, creo que podemos pasar esta versión a producción. De paso van viendo como queda ahi en "_btv4"

Otra cosa, ponganle título a las fotos. La última foto de Eze en TED no tiene título y eso genera que en la página haya un título vacio, sin caracteres.

**Comment by LeandroBraier** [comment]
OK, Fede. Gracias!

Podés subirlo ya a producción como está. Cuando haya 4 fotos subimos las 4,
se podrá así?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-03 12:03 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
El tema es que son fotos de instagram y creo que van a tardar en generar 4 fotos, excepto que suban 4 fotos de lo mismo en el mismo día. Avisame

**Comment by LeandroBraier** [comment]
Fede, seguimos con problemas para la carga del tab de Benteveo. Yo tengo 3 MB de conexión y NUNCA se carga. No es que demora. No carga NUNCA. Resolvamos esto por favor, o busquemos otro embed de Facebook que funcione bien con la página.

Otro tema: Probamos ayer subir fotos a Instagram con texto y el texto no aparece en la cartelera. Necesitaríamos que aparezca, se puede?

**Comment by FAAREIA** [comment]
Lo de instagram creo que se puede, hay que agregarlo.
El bloque de FB, es ese, no hay un alternativo con código distinto, pero que muestre igual data. Si me decis que no carga nunca, fijate si alguien te bloqueó el acceso a FB, o sino FB mismo puede estar andando mal. Si bien son servicios que manejan millones se pueden caer o andar mal, por ejemplo a Gmail lo he visto caerse por completo por más de unos minutos.
Resolver no se puede porque FB manda el código, los datos, etc etc. Nuestra página simplemente le dice a FB "che traeme este bloque prediseñado que ofreces, para la cuenta BenteveoTV", y listo.

**Comment by LeandroBraier** [comment]
Ok, si no lo podés resolver lo veo con MK pero alguna solución tiene que
tener. Evidentemente hay algo de lo que vos decís porque antes en Paty no
me pasaba y ahora sí. Sin embargo, en Dánica sí funciona bien.

Tiene que haber algo en el código de la página, del embed o algo que antes
funcionaba y ahora ya no. ¿Vos lo ves bien al embed? Porque el otro día en
la compu de Eze se veía igual que en la mía y era otra conexión, en la
produ. Puede ser que el embed tenga un tamaño muy chico y ahora Facebook no
despliega en ese tamaño? Digo porque el de Dánica es más grande.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-22 12:13 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Desconozco si la tiene, desde mi visión no tiene solución.
El código siempre es el mismo, no hay otro ya que te lo provee FB.
Lo del tamaño no es, FB ni se entera el tamaño que le das, pero si pone limites propios inmodificables.

Pensá que cada página puede estar en una maquina distinta, y capas que esa maquina accede a un CDN de FB que otra maquina no. No todas las páginas se conectan al mismo servidor de FB.

**Comment by LeandroBraier** [comment]
Ok, le pregunto a MK entonces. 

MK, cómo ves vos el embed de Facebook de la página actual de Benteveo?

http://www.benteveo.tv

**Comment by mkreyness** [comment]
Lo que veo es una tira de facebook que no llega a completar todo el alto 
(tiene la foto de storydoingTV debajo) insertada en la segunda columna 
de fotos de instagram. Se ve bien.

**Comment by LeandroBraier** [comment]
Ahora lo veo bien! Qué loco, ahora me carga al toque. Gracias MK y Fede! No sé si cambiaron algo pero no me quejo más. 

Fede, quedo esperando entonces el tema de texto de Instagram.

abrazo

**Comment by FAAREIA** [comment]
http://chat.benteveo.tv/chat/
Ya esta listo lo de la bajada de instagram, recuerden que a TODAS las fotos le tienen que poner el titulo que es la bajada misma. Eso ayuda al SEO.
Ahora las fotos que no tienen bajada, aparacen vacias, por eso el rectangulo blanco transparente en la parte inferior de la foto

**Comment by LeandroBraier** [comment]
Perfecto Fede! Ahora le subimos texto

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-24 12:53 GMT-03:00 Federico Arena notifications@github.com:
