### ISSUE TITLE
Subir nuevo caso en Video a sitio Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#15]
Fede, porfa subí este nuevo caso al sitio de Benteveo. Tendría que aparecer primero, antes del Caso Dánica.

https://vimeo.com/108678282

**Comment by FAAREIA** [comment]
Ok dale

**Comment by FAAREIA** [comment]
Una vez que terminemos con el chat subo todo junto, asi no tengo una doble versión.

**Comment by FAAREIA** [comment]
Ya lo podes ver en:
http://chat.benteveo.tv/chat/

**Comment by LeandroBraier** [comment]
Andá subiendo este caso a producción porque MK todavía no me terminó de configurar el chat.

Además, estoy pensando que el chat se te va a superponer con los logos de Facebook y Twitter flotantes en este esquema de diseño, no?

**Comment by FAAREIA** [comment]
Ok
Si, se superpone, pero creo que los iconos van a ir del lazo izquierdo ahora, que decis?

**Comment by FAAREIA** [comment]
Ahi ya lo subí al sitio online también

**Comment by LeandroBraier** [comment]
Dale, del lado izquierdo mejor por ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
