### ISSUE TITLE
Nuevas Landings Benteveo para el Jueves 30

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#17]
Fede, tengo unas cuantas landings nuevas para nuevas marcas. Tentativamente serían para el jueves. Decime si llegás. Las filtré bien, pero si se me escapó una marca a la que ya le hiciste la landing avisame.

abrazo

~~Tia Maruca sa~~
http://www.tiamaruca.com/productos-reposteria.php

~~Hojalmar~~
http://www.hojalmar.com/hojalmar.htm

~~Galletitas Cilo~~
http://www.cilo.com.ar/

~~Caramelos Lipo~~
http://www.productoslipo.com/

~~Valente~~
http://www.alimentosvalente.com/

~~Tapa Mania~~
http://www.tapamania.com/

~~Galletitas Neosol~~
http://www.galletitasneosol.com.ar/

~~Lucerna~~
http://www.calzadoslucerna.com.ar/

~~Sibyl Vane~~
http://www.sibylvane.com/inicio

~~Valdez~~
http://shop.gvaldez.com.ar/

~~Ladycomfort~~
http://www.ladycomfort.com.ar/

~~Biferdil~~
http://www.biferdil.com/

~~New Plast~~
http://www.newplastsrl.com.ar/

~~Colombraro~~
http://www.colombraro.com.ar/web/index.php

~~Georgalos~~
http://www.georgalos.com.ar/georgalos_Wsm_Site.nsf/Web_Main?OpenFrameSet&Frame=Web_Main&Src=%2Fgeorgalos_Wsm_Site.nsf%2FwebSite%2Fesinicio%3FOpenDocument%26AutoFramed

~~Ruibal~~
http://www.ruibalgames.com/ruibal.html

~~Yetem~~
http://www.yetem.com/

~~Cebra~~
http://www.cebra.com.ar/

~~Carrousel~~
http://www.jugueteriascarrousel.com/

~~Kinderland~~
http://www.kinderland.com.ar/index.php?route=information/contact

~~Girodidactico~~
http://www.girodidactico.com/

~~Wabro~~
http://www.wabro.com.ar/

~~Top Toys~~
http://www.toptoys.com.ar/

~~Toy Co~~
http://www.toycompany.com.ar/

~~New Toy~~
http://www.newtoys.com.ar/

~~Cicatricure/tio Nacho/ Goycochea/Multi O~~
http://www.genommalab.com.ar/

~~Efiderma~~
http://www.liargentino.com/

~~Mervick~~
http://www.mervick-lab.com.ar/

~~Royal Cannin~~
http://www.royal-canin.com.ar/

~~Alimentos Raza~~
http://www.alimentoraza.com.ar/

~~Catan Shopping~~
http://catanshopping.com/

~~Gaelle~~
http://www.gaelle.com.ar/

~~Alpargatas~~
http://www.alpargatas.com.ar/

~~Pampa Gourmet~~
http://www.pampagourmet.com.ar/

~~CBSE~~
http://www.yerbacbse.com.ar/

~~Taragui/union/La Merced~~
http://www.lasmarias.com.ar

~~Hileret~~
http://www.hileret.com.ar/

~~Budeguer~~
http://www.budeguer.com/

~~awada~~
http://www.awadaonline.com.ar/

~~complot~~
http://www.complot.com.ar/

~~cristobal colon~~
http://www.cristobalcolon.com/

~~delaostia~~
http://www.delaostia.net/

~~Getien~~
http://www.getien.com.ar/getien-comingsoon/

Gimos
~~http://www.gimos.com.ar/~~

indiastyle
~~http://www.indiastyle.com.ar/~~

**Comment by LeandroBraier** [comment]
Buen día Fede!

Por favor en estas nuevas landings, necesitaría que pongas algún distintivo entre el link de los botones que hay al final del video y los links de los botones que hay al final de la página. Podría ser simplemente contacto=1 y contacto=2, no necesito más que eso. Simplemente que sean diferentes.

abrazo

**Comment by FAAREIA** [comment]
¿Por qué necesitan eso? Me parece que se van a mezclar muchisimo si hacemos eso.
Ya ha 69 marcas, si sumamos 40 marcas más con "algo" distinto, cuando le actualicemos algo a la landing, como distinguimos entre unas y otras. Vamos a tener que tener un registro de todas, me parece poco práctico

**Comment by LeandroBraier** [comment]
Yo tengo un registro de todas, con muchos más datos: nombre de contacto,
mail, página web, facebook, rubro, todo. Por eso no hay problema.

En realidad te pediría que le cambies esto del link a las landings ya
hechas también pero eso nos demoraría la salida de hoy.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-27 8:41 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lo que se podría poner es, en vez de:

contacto=1&marca=farmesa

cambiarlo por:

contacto=farmesa

por ejemplo

**Comment by LeandroBraier** [comment]
dale, como te sea más fácil a vos, siempre que sea igual en todas las
landings, asi puedo hacer un análisis después de en qué botones clickearon.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
mmm, estoy viendo que si hacemos el cambio, hay que avisarle a MK. Porque algo de lo que envia el email tiene esas variables.
Lo ideal sería cambiarlo asi no tenemos archivos como esos duplicados para las nuevas landing

**Comment by LeandroBraier** [comment]
Ok, a la tarde les paso un feedback de esto entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-27 10:08 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok

Lea, te actualizo en dos cosas:
- Los links como pediste, ya los cambiamos con marce. Estan todos actualizados. Quedó: contacto=MARCA y almuerzo=MARCA
- Como ya no hay 2 versiones de video, el video ya no se incluye por código javascript, sino que esta dentro del código de la página misma.

**Comment by LeandroBraier** [comment]
Excelente, mejor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-27 11:19 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lea, el logo no dice Efiderma, a la página la titulo Efiderma igualmente? Al cliente también?

Efiderma
http://www.liargentino.com/

**Comment by LeandroBraier** [comment]
No, titula y todo como está en la pagina web.

**Comment by FAAREIA** [comment]
Efiderma pasó a ser "Laboratorio Internacional Argentino"
Fijate el logo de "establecimiento-las-marias", lo saque de google, en su sitio no hay logo. Asi como escuchas =/

http://www.benteveo.tv/abuela-goye/
http://www.benteveo.tv/ag-underwear/
http://www.benteveo.tv/airborn/
http://www.benteveo.tv/akiabara/
http://www.benteveo.tv/alfajores-jorgito/
http://www.benteveo.tv/alimento-raza/
http://www.benteveo.tv/alimentos-granix/
http://www.benteveo.tv/allo-martinez/
http://www.benteveo.tv/alpargatas/
http://www.benteveo.tv/alternativa-comunica/
http://www.benteveo.tv/ancayco/
http://www.benteveo.tv/aretha/
http://www.benteveo.tv/atomik/
http://www.benteveo.tv/avicar/
http://www.benteveo.tv/awada/
http://www.benteveo.tv/bedson/
http://www.benteveo.tv/bensimon/
http://www.benteveo.tv/biferdil/
http://www.benteveo.tv/blaque/
http://www.benteveo.tv/boating/
http://www.benteveo.tv/bowen-london/
http://www.benteveo.tv/brandel/
http://www.benteveo.tv/bras-panties/
http://www.benteveo.tv/budeguer/
http://www.benteveo.tv/cafe-martinez/
http://www.benteveo.tv/calzados-california/
http://www.benteveo.tv/caramelos-lipo/
http://www.benteveo.tv/cardon/
http://www.benteveo.tv/carrousel/
http://www.benteveo.tv/catan-shopping/
http://www.benteveo.tv/cbse/
http://www.benteveo.tv/cebra/
http://www.benteveo.tv/cerini/
http://www.benteveo.tv/chibel/
http://www.benteveo.tv/citykids/
http://www.benteveo.tv/class-life/
http://www.benteveo.tv/clona/
http://www.benteveo.tv/codere/
http://www.benteveo.tv/colombraro/
http://www.benteveo.tv/complot/
http://www.benteveo.tv/cresta-roja/
http://www.benteveo.tv/cristobal-colon/
http://www.benteveo.tv/delaostia/
http://www.benteveo.tv/diezindiecitos/
http://www.benteveo.tv/diuff/
http://www.benteveo.tv/don-satur/
http://www.benteveo.tv/establecimiento-las-marias/
http://www.benteveo.tv/fachitas/
http://www.benteveo.tv/farmesa/
http://www.benteveo.tv/frigorifico-calchaqui/
http://www.benteveo.tv/gaelle/
http://www.benteveo.tv/galletitas-cilo/
http://www.benteveo.tv/galletitas-trio/
http://www.benteveo.tv/general-cereals/
http://www.benteveo.tv/genomma-lab/
http://www.benteveo.tv/georgalos/
http://www.benteveo.tv/getien/
http://www.benteveo.tv/gimos/
http://www.benteveo.tv/giro-didactico/
http://www.benteveo.tv/gravagna/
http://www.benteveo.tv/grupo-gaona/
http://www.benteveo.tv/heredia-infusiones/
http://www.benteveo.tv/hileret/
http://www.benteveo.tv/hojalmar/
http://www.benteveo.tv/iberia-hogar/
http://www.benteveo.tv/icbc/
http://www.benteveo.tv/india-style/
http://www.benteveo.tv/jaguar/
http://www.benteveo.tv/jaguar-kids/
http://www.benteveo.tv/keek/
http://www.benteveo.tv/key-biscayne/
http://www.benteveo.tv/kiero/
http://www.benteveo.tv/kinderland/
http://www.benteveo.tv/laboratorio-internacional-argentino/
http://www.benteveo.tv/lacteos-veronica/
http://www.benteveo.tv/lady-comfort/
http://www.benteveo.tv/little-akiabara/
http://www.benteveo.tv/lucerna/
http://www.benteveo.tv/marolio/
http://www.benteveo.tv/mervick/
http://www.benteveo.tv/natacha/
http://www.benteveo.tv/nazaria-zapatos/
http://www.benteveo.tv/neosol/
http://www.benteveo.tv/nevares/
http://www.benteveo.tv/new-plast/
http://www.benteveo.tv/new-toys/
http://www.benteveo.tv/nivea/
http://www.benteveo.tv/pampagourmet/
http://www.benteveo.tv/parnor/
http://www.benteveo.tv/perlea-maidenform/
http://www.benteveo.tv/peuque-jeans/
http://www.benteveo.tv/philips-healthcare/
http://www.benteveo.tv/plumitas/
http://www.benteveo.tv/rosamonte/
http://www.benteveo.tv/royal-canin/
http://www.benteveo.tv/ruibal/
http://www.benteveo.tv/sibyl-vane/
http://www.benteveo.tv/soriano/
http://www.benteveo.tv/square/
http://www.benteveo.tv/tapamania/
http://www.benteveo.tv/tia-maruca/
http://www.benteveo.tv/toot/
http://www.benteveo.tv/top-toys/
http://www.benteveo.tv/toyco/
http://www.benteveo.tv/valdez/
http://www.benteveo.tv/valente/
http://www.benteveo.tv/vie-tur/
http://www.benteveo.tv/wabro/
http://www.benteveo.tv/yetem/

**Comment by LeandroBraier** [comment]
Gracias Fede! Buena data, mientras menos comunicación tengan más
posibilidad de que le hagamos más cosas nosotros.

Los reviso y te doy feedback por la tarde.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Todo joya Fede. Van algunas modificaciones nada más:

http://www.benteveo.tv/valente/

El logo se ve pixelado

http://www.benteveo.tv/colombraro/

El logo es otro, poné el actual que está en: http://www.colombraro.com.ar/web/index.php

http://www.benteveo.tv/ruibal/

Poner de fondo el color verdecito que hay en el sitio oficial.

http://www.benteveo.tv/efiderma/

No la encuentro.

http://www.benteveo.tv/getien/

mejor poné Getien en blanco, como en el sitio, y el cogito de la G fuxia a la izquierda, como el favicon.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya solucioné lo de Valente, Colombraro y Ruibal.
El logo de Valente lo saqué del sitio, pero hasta en el sitio esta pixelado. Achicado se disumula un poco. En google no lo encontré.
En ruibal le puse fondo verde, pero fijate que los fondos cambian igual, son 4 fondos random aprox.

Efiderma no existe, este es -> http://www.benteveo.tv/laboratorio-internacional-argentino/

Getien esta en construcción:
http://www.getien.com.ar/getien-comingsoon/
pero podes ver lo que tenian antes en:
http://www.getien.com.ar/colecciones/colecciones.php
Por eso la hice asi.

**Comment by LeandroBraier** [comment]
Gracias! Todo Ok entonces, incluido Getien.

Respecto de Efiderma, es cierto lo que decís. La compró un monstruo nacional y después uno internacional. Olvidate de esa.

abrazo
