### ISSUE TITLE
Tercer Tanda de Landings Benteveo para el Jueves 6

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#18]
Fede, te paso una nueva tanda de Landings para el jueves que viene.

~~Jazmin Chebar~~
http://www.jazminchebar.com.ar/

~~La Martina~~
http://www.lamartina.com/arg/en-gb

~~La Toscana~~
http://www.latoscana.com.ar/

~~Las pepas~~
http://laspepas.com.ar/

~~Lazaro~~
http://www.lazarocuero.com.ar/

~~Ribeiro~~
http://www.ribeiro.com.ar/ribeiro/

~~helados schietto~~
http://www.heladosschietto.com.ar/

~~Arancio~~
http://www.aranciohelados.com.ar/

~~Chevanne~~
http://www.chevanne.com.ar/

~~Chocorisimo~~
http://www.chocorisimo.com/

~~Freise~~
http://www.fraise.com.ar/index1.html

~~Cremolatti~~
http://www.cremolattionline.com.ar/

~~El fundador~~
http://www.elfundadorhelados.com.ar/

~~Eurocream~~
http://www.eurocrem.com.ar/home.php

~~Faricci~~
http://www.faricci.com/

~~Helados Copahue~~
http://www.heladoscopahue.com.ar/

~~helados Iglu~~
http://www.igluhelados.com.ar/

~~Il Cavallino~~
www.ilcavallino.com.ar

~~Frahel~~
www.frahel.com

~~Bacchio~~
www.bacchio.com

~~Grido~~
http://www.gridohelado.com.ar/

~~le ble~~
http://www.leble.com.ar/

~~Devas´s~~
http://devas.com/shop/

~~ditoys~~
http://www.ditoys.com.ar/

~~triple w~~
http://www.triplew.com.ar/

~~Ladder Propiedades~~
http://www.ladderpropiedades.com.ar

~~Lado u~~
http://ladou.com.ar/

~~Emporio dental    ~~
http://emporiodental.com/

~~Upa   Upa~~
http://www.upamayorista.com.ar/

~~Dafaplast~~
http://www.dafaplast.com.ar/

~~todo para cocinar~~
http://www.todoparacocinar.com.ar/

~~Gluia~~
http://www.gluiatours.com.ar/

~~Lucerna~~
http://www.calzadoslucerna.com.ar/

~~agostina Bianchi~~
http://www.agostinabianchi.com/

~~Elbita~~
http://www.elbita.com

~~Astton~~
http://www.astton.com/

~~Vanessa Stach~~
http://www.vanessastrach.com/

Aparte te paso otra lista pero es para la otra semana recién.

abrazo

**Comment by FAAREIA** [comment]
Creo que habría que ir pensando un sistema de templates ya que estan siendo demasiadas marcas.
Actualmente hay 104 aprox y se suman con este issue y otro como 70 más.

La base del template la tengo, las variables se donde se donde tienen que ir.
Lo ideal sería hacer algun sistema como hacen los CMS que autogeneré la página en base a variables de Título, Título safe, Color 1, Color 2, etc.

Cómo la ves marce?

**Comment by FAAREIA** [comment]
El sistema de template nos agilizaría la actualización de algo en las landings y suprimiría los errores de tipeo.

**Comment by LeandroBraier** [comment]
Yo completamente de acuerdo. Creo que tenemos tiempo para hacerlo.
Empecemos si MK da el ok.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Todo barbaro, pero no puede funcionar en el hosting actual de Benteveo.
No puedo tener base de datos, no puedo correr programas, etc. etc.
Si quieren se hace directo sobre el nuevo, pero las paginas estarian en 
el nuevo, no en el viejo.

**Comment by FAAREIA** [comment]
Supongamos que HOY delegamos los DNS y supongamos que el míercoles se delegan, si tenemos el mismo contenido en los 2 hosting, nadie se entera de nada. Por lo que no veo nada que frene la delegación.
No es por presionar, pero en cuento tiempo tendrías el CMS ese? Asi vemos si llegamos con esas 70 landing para el jueves

**Comment by mkreyness** [comment]
```
Todavia ni entendi que tendria que tener, pero ponele que un par de
dias, minimo.

El 03/11/2014 a las 9:33, Federico
  Arena escribió:


  Supongamos que HOY delegamos los DNS y supongamos que el
    míercoles se delegan, si tenemos el mismo contenido en los 2
    hosting, nadie se entera de nada. Por lo que no veo nada que
    frene la delegación.
    No es por presionar, pero en cuento tiempo tendrías el CMS ese?
    Asi vemos si llegamos con esas 70 landing para el jueves
  —
    Reply to this email directly or view
      it on GitHub.
  {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61471535">"https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61471535"</a>,"name":"View Issue"}}
```

**Comment by FAAREIA** [comment]
Sería asi:
- Me logueo al CMS
- Voy a crear una página nueva y cargo los siguientes campos:
- Nombre de la marca
- Nombre de la marca SAFE (Ej: catan-shopping)
- Color de fondo
- Color del borde del video
- Color de la sombra
- Color del texto del botón en :hover
- Color de la manito
- Color del borde del círculo de la manito
- Color de la flecha superior
- Color 1 de los íconos de los botones
- Color 2 de los íconos de los botones
- Pongo guardar y se genera un HTML o algo en la base de datos.
- Entro a la URL correspondiente y me levanta el HTML o el sistema accede a la base de datos y me devuelve el HTML
- Todos los datos se cargan sobre la base de un template

**Comment by mkreyness** [comment]
```
Bueno, no seria exactamente asi.
En realidad no genera el HTML el CMS, el CMS solo guarda esos
parametros en una base de datos, y hay un boton "Publicar" que
provoca que un proceso en background (porque desde la web NO se
pueden grabar paginas) genere unos minutos despues el HTML.

Pero no serviria de nada si primero vos no haces esto:
- me tenes que hacer un template donde CADA UNO de estos campos que
nombras tenga su contenido puesto como comentarios
<!--variable-->
(me parece que lo mejor es que para todo lo que sea colores de
borde/sombra/texto/manito/borde de circulo de manito/flecha/iconos
hagas familias de CLASES, entonces en cada uno de esos lugares
solamente pones class="<!--clasefondo-->", etc. Fijate como te
conviene organizarlo, y yo despues me ocupo de reemplazar las
variables.

El 03/11/2014 a las 9:43, Federico
  Arena escribió:


  Sería asi:

    Me logueo al CMS
    Voy a crear una página nueva y cargo los siguientes campos:
    Nombre de la marca
    Nombre de la marca SAFE (Ej: catan-shopping)
    Color de fondo
    Color del borde del video
    Color de la sombra
    Color del texto del botón en :hover
    Color de la manito
    Color del borde del círculo de la manito
    Color de la flecha superior
    Color 1 de los íconos de los botones

      Color 2 de los íconos de los botones


      Pongo guardar y se genera un HTML o algo en la base de
        datos.

    Entro a la URL correspondiente y me levanta el HTML o el
      sistema accede a la base de datos y me devuelve el HTML

  —
    Reply to this email directly or view
      it on GitHub.
  {"@context":<a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,"@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61472398">"https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61472398"</a>,"name":"View Issue"}}
```

**Comment by FAAREIA** [comment]
Ok, cuando lo tenga listo te lo paso.

**Comment by LeandroBraier** [comment]
Fede, no te olvides que para el jueves deberíamos empezar a tener las primeras. Si el CMS ya está funcionando yo te puedo dar una mano cargando los logos y colores, así hacemos más rápido. abrazo

**Comment by FAAREIA** [comment]
Ok, no esperamos el CMS entonces
Marce te pasé el template, lo simplifiqué y tiene solo dos variables. Título y Título-Safe.

**Comment by LeandroBraier** [comment]
Dale, paralelamente con el CMS avancemos con las primeros 25 landings
ponele. Con eso estamos para esta semana. Pero fijate que sean las primeras
25 de la lista, no las reordenes alfabéticamente.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hubo una modificación en algunos detalles, por lo que voy a empezar estas landing de la nueva forma.
Las landing anteriores por ahora las dejo con el sistema viejo.

**Comment by LeandroBraier** [comment]
Entiendo, no hay problema con eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-04 10:15 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
El CMS lo tengo que poner en el sitio nuevo de Benteveo, por lo tanto 
las paginas que genere van a estar ahi, y no en el viejo.
Eso trae algun problema ?

**Comment by FAAREIA** [comment]
Hacelo ahi no queda otra.
Por otra parte, ahora voy a subir todo lo que hay en el server original al de Duplika. Cuando hagan cambio de DNS, nadie va a notar nada, también habría que ir creando los mails que no se cuales son

**Comment by mkreyness** [comment]
Ejem, me parece que pisaste la carpeta cgi-bin que habia, y por lo tanto 
desaparecio el chat.pl
Anoche hice montones de cambios, y los hice todos directamente ahi...

**Comment by FAAREIA** [comment]
Lo que estaba en el root, lo puse en la carpeta __BORRAR. De hecho nadie accede al root, pero por las dudas
La carpeta "chat" tiene todo lo correspondiente al subdominio. ¿Ahi actualizaste el chat.pl?

**Comment by mkreyness** [comment]
No, en cgi-bin ! Nunca borres ni pises cgi-bin, que se pierden todos los 
permisos que pone Duplika !
No se pueden ejecutar programas en chat, no me dejan.
Me repusiste un cgi-bin con chat.pl VIEJO.

**Comment by FAAREIA** [comment]
no no, ese chat.pl lo tenia descargado en mi PC.
El chat.pl que buscas esta en la carpeta "__BORRAR" o dentro de "chat > cgi.bin"
Fijate y decime cual es asi hago backup tmb

**Comment by mkreyness** [comment]
Ok, como sea, me lo pisaste.
Ahi lo copie de __BORRAR/cgi-bin a www/cgi-bin, que es donde tiene que 
estar.
www/cgi-bin es donde residen todos los programas ejecutables desde web.
Backupealo de ahi.
Hay que ver si el cgi-bin que bajaste de tu maquina es realmente ejecutable.
El que era ejecutable quedo dentro de __BORRAR

**Comment by FAAREIA** [comment]
Ahi moví la carpeta desde "__BORRAR" a "public_html", tendría que ser lo mismo que antes

**Comment by FAAREIA** [comment]
Ya que estamos con esto de la carpeta cgi-bin, qué archivos son los que sirven ahi? Asi backupeo esos archivos. Ya aprendí que la carpeta no se borra, ni reemplaza

**Comment by mkreyness** [comment]
chat.pl en ESTE momento, pero voy a seguir agregando muchas otras cosas 
(subcarpetas, programas) por lo del CMS.
Siempre lo que se tenga que ejecutar desde web va ahi.

**Comment by FAAREIA** [comment]
Ok joya.

**Comment by FAAREIA** [comment]
Ahi ya backupié todo lo del sitio de benteveo actual, al futuro server.

Lo único que no subí fue:
- Los archivos del casting. Son 773 archivos. ¿Esto sigue vigente?
- Una carpeta llamada "cardtest" que creo que no tiene uso desde que yo llegué al menos.
- Todo lo relacionado a las landing page que son de versión vieja. La nueva versión sería la del CMS.

Si delegan los DNS, solo faltaría crear los emails. No digo de hacer backup de emails, porque seguro eso implica a Federico e imagino también que usan algo como Outlook, el cual baja los emails a la maquina. Cualquier cosa decime Lea.

**Comment by mkreyness** [comment]
Ya esta listo el CMS, y cargue todas las marcas viejas que me paso Fede.
Igual supongo que las que valen son las nuevas.
Cuando quieran me las pasan y las cargo en bloque, lo que necesito es un 
excel con titulo-safe y titulo ok (con todos los acentos, mayusculas, etc.).

CMS:

http://chat.benteveo.tv/cgi-bin/cms.pl

user admin, pass la de siempre.
Hay una opcion del menu "Marcas" que dentro tiene una subopcion 
"Actualizacion de Marcas", donde está todo.

Una vez por minuto cualquier marca <X> que hayas agregado se genera la 
carpeta, accesible como

http://chat.benteveo.tv/<X>

Si por algun motivo hubiera que regenerar las ya existentes (por un 
cambio en el template general), puse que una vez cada media hora se 
regeneren todas.

OJO la eliminacion de una marca del CMS no hace que automaticamente se 
borre la carpeta, al menos por ahora.

Fede: el template que se usa está en 
/user/benteveo/www/template/indexT.html (notar la "T", eso es para 
evitar que por error un template pise una index real)

**Comment by LeandroBraier** [comment]
Ok, gracias Marce!

Fede, avisame cuando podemos empezar a cargar las marcas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-05 19:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Marce, te pregunto porque vos capas lo sacas al toque.
Si bien puedo ir archivo por archivo copiando el <title> de cada HTML,
también se que puedo buscar con regex cualquier cosas que este escrita
entre <title> y </title>. Tenés idea de como es? Nunca entendí las
expresiones regulares. =/

**Comment by FAAREIA** [comment]
Ahora hago 6 marcas más para completar las 25 y le paso a Marce lo nuevo.

**Comment by mkreyness** [comment]
```
Depende con que programa, yo estas cosas las hago entrando con SSH y
usando comandos de linux.
Lo que complica es si <title> y </title> estan en
distinta linea, porque en general estos comandos operan en base a
linea por linea.

Ademas "</title>" incluye "/" que en las expresiones regulares
(de linux) se usa como separador, asi que hay que ponerlo asi: "\/"
para que sea tomado literalmente.

Igual no entiendo como lo aplicarias porque cada uno lleva un title
DIFERENTE, o queres ponerle el mismo a todo ?

Yo si tuviera que ponerle el MISMO titulo a todos los titles de
todos los HTML que estan en una carpeta por ejemplo

s "/<title><\/title>/<title>El Nuevo
Titulo<\/title>/" -i *.html

o mas facil para evitar problemas con la /:

s "/<title></<title>El Nuevo Titulo</" -i *.html

pero eso es suponiendo que entre <title> y </title>
actualmente no hay nada.
Si hubiera algo y no te importa que, lo queres eliminar, seria:

s "/<title>[^<]*</<title>El Nuevo Titulo</" -i
*.html


El 06/11/2014 a las 9:48, Federico
  Arena escribió:

Marce, te pregunto porque vos capas lo sacas al toque.

  Si bien puedo ir archivo por archivo copiando el <title> de
  cada HTML,

  también se que puedo buscar con regex cualquier cosas que este
  escrita

  entre <title> y </title>. Tenés idea de como es? Nunca
  entendí las

  expresiones regulares. =/


  El 5 de noviembre de 2014, 19:47,
  LeandroBraier<notifications@github.com>

  escribió:


  > Ok, gracias Marce!

  >

  > Fede, avisame cuando podemos empezar a cargar las marcas.

  >

  > abrazo

  >

  > Leandro Braier

  > Producción Audiovisual & Social Media

  > Benteveo Producciones <http://benteveo.tv>

  > Móvil 1158717399

  >

  > 2014-11-05 19:46 GMT-03:00 mkreyness
  <notifications@github.com>:

  >

  > > Ya esta listo el CMS, y cargue todas las marcas viejas
  que me paso Fede.

  > > Igual supongo que las que valen son las nuevas.

  > > Cuando quieran me las pasan y las cargo en bloque, lo
  que necesito es un

  > > excel con titulo-safe y titulo ok (con todos los
  acentos, mayusculas,

  > > etc.).

  > >

  > > CMS:

  > >

  > > http://chat.benteveo.tv/cgi-bin/cms.pl

  > >

  > > user admin, pass la de siempre.

  > > Hay una opcion del menu "Marcas" que dentro tiene una
  subopcion

  > > "Actualizacion de Marcas", donde está todo.

  > >

  > > Una vez por minuto cualquier marca <X> que hayas
  agregado se genera la

  > > carpeta, accesible como

  > >

  > > http://chat.benteveo.tv/<X>

  > >

  > > Si por algun motivo hubiera que regenerar las ya
  existentes (por un

  > > cambio en el template general), puse que una vez cada
  media hora se

  > > regeneren todas.

  > >

  > > OJO la eliminacion de una marca del CMS no hace que
  automaticamente se

  > > borre la carpeta, al menos por ahora.

  > >

  > > Fede: el template que se usa está en

  > > /user/benteveo/www/template/indexT.html (notar la "T",
  eso es para

  > > evitar que por error un template pise una index real)

  > >

  > > On 04/11/2014 01:53 p.m., Federico Arena wrote:

  > > >

  > > > Ahi ya backupié todo lo del sitio de benteveo
  actual, al futuro

  > server.

  > > >

  > > > Lo único que no subí fue:

  > > >

  > > > * Los archivos del casting. Son 773 archivos. ¿Esto
  sigue vigente?

  > > > * Una carpeta llamada "cardtest" que creo que no
  tiene uso desde que

  > > > yo llegué al menos.

  > > > * Todo lo relacionado a las landing page que son de
  versión vieja.

  > > > La nueva versión sería la del CMS.

  > > >

  > > > Si delegan los DNS, solo faltaría crear los emails.
  No digo de hacer

  > > > backup de emails, porque seguro eso implica a
  Federico e imagino

  > > > también que usan algo como Outlook, el cual baja
  los emails a la

  > > > maquina. Cualquier cosa decime Lea.

  > > >

  > > > —

  > > > Reply to this email directly or view it on GitHub

  > > > <

  > >

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61672718
      > > >.

```
  > >

  > > >

  > >

  > > —

  > > Reply to this email directly or view it on GitHub

  > > <

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61895809>
      >

```
  > > .

  > >

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/18#issuecomment-61895979
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Buenísimo, la última era justo lo que necesitaba.

Te lo paso linea por linea, espero que sirva:
Son las viejas, en 30 te paso las nuevas

abuela-goye
Abuela Goye
ag-underwear
AG Underwear
airborn
AIRBORN
akiabara
AKIABARA
alfajores-jorgito
Alfajores Jorgito
alimento-raza
Alimento RAZA
alimentos-granix
Alimentos Granix
allo-martinez
ALLO MARTINEZ
alpargatas
Alpargatas
alternativa-comunica
Alternativa Comunica
ancayco
ANCA&CO
aretha
ARETHA
atomik
ATOMIK
avicar
Avicar
awada
Awada
bedson
Bedson
bensimon
Bensimon
biferdil
Biferdil
blaque
Blaqu&#232;
boating
Boating
bowen-london
Bowen London
brandel
BRANDEL
bras-panties
Bras &amp; Panties
budeguer
Budeguer
cafe-martinez
Café Martinez
calzados-california
Calzados California
caramelos-lipo
Caramelos Lipo
cardon
CARDON
carrousel
Carrousel
catan-shopping
Catan Shopping
cbse
CBSé
cebra
Cebra
cerini
Cerini
chibel
chibel
citykids
Citykids
class-life
Class Life
clona
Clona
codere
codere
colombraro
Colombraro
complot
Complot
cresta-roja
Cresta Roja
cristobal-colon
Cristobal Colon
delaostia
DELAOSTIA
diezindiecitos
Diez Indiecitos
diuff
Diuff
don-satur
Don Satur
establecimiento-las-marias
Establecimiento Las Marias
fachitas
Fachitas
farmesa
Farmesa
frigorifico-calchaqui
Frigorifico Calchaqui
gaelle
Gaelle
galletitas-cilo
Galletitas Cilo
galletitas-trio
Galletitas TRIO
general-cereals
General Cereals
genomma-lab
Genomma Lab.
georgalos
Georgalos
getien
Getien
gimos
Gimos
giro-didactico
Giro Didáctico
gravagna
Calzados Gravagna
grupo-gaona
Grupo Gaona
heredia-infusiones
Heredia Infusiones
hileret
Hileret
hojalmar
Hojalmar
iberia-hogar
IBERIA
icbc
ICBC
india-style
India Style
jaguar-kids
JAGUAR Kids
jaguar
JAGUAR
keek
KEEK
key-biscayne
Key Biscayne
kiero
Kiero
kinderland
Kinderland
laboratorio-internacional-argentino
Laboratorio Internacional Argentino
lacteos-veronica
Verónica
lady-comfort
Lady Comfort
little-akiabara
Little Akiabara
lucerna
LUCERNA
marolio
Marolio
mervick
Mervick
natacha
NATACHA
nazaria-zapatos
NAZARIA ZAPATOS
neosol
Neosol
nevares
Nevares
new-plast
NEW PLAST
new-toys
New Toy's
nivea
NIVEA
pampagourmet
Pampagourmet
parnor
Parnor
perlea-maidenform
Perlea + Maidenform
peuque-jeans
Peuque
philips-healthcare
Philips Healthcare
plumitas
Plumitas
rosamonte
Rosamonte
royal-canin
Royal Canin
ruibal
RUIBAL
sibyl-vane
Sibyl Vane
soriano
Soriano
square
SQUARE
tapamania
TAPAMANIA
tia-maruca
Tía Maruca
toot
TOOT
top-toys
Top Toys
toyco
ToyCo
valdez
VALDEZ
valente
Valente
vie-tur
Vie Tur
wabro
WABRO
yetem
YETEM

**Comment by mkreyness** [comment]
```
Mandamelo en excel, asi cada columna viene como debe ser, una
columna.
Aca veo el titulo debajo del titulo-safe, y tengo que ponerme a
rearmar todo, y me puedo equivocar.
Los txt son el peor metodo de mandar datos en un mail...

El 06/11/2014 a las 10:17, Federico
  Arena escribió:


  Buenísimo, la última era justo lo que necesitaba.
  Te lo paso linea por linea, espero que sirva:
    Son las viejas, en 30 te paso las nuevas
  abuela-goye
    Abuela Goye
    ag-underwear
    AG Underwear
    airborn
    AIRBORN
    akiabara
    AKIABARA
    alfajores-jorgito
    Alfajores Jorgito
    alimento-raza
    Alimento RAZA
    alimentos-granix
    Alimentos Granix
    allo-martinez
    ALLO MARTINEZ
    alpargatas
    Alpargatas
    alternativa-comunica
    Alternativa Comunica
    ancayco
    ANCA&CO
    aretha
    ARETHA
    atomik
    ATOMIK
    avicar
    Avicar
    awada
    Awada
    bedson
    Bedson
    bensimon
    Bensimon
    biferdil
    Biferdil
    blaque
    Blaquè
    boating
    Boating
    bowen-london
    Bowen London
    brandel
    BRANDEL
    bras-panties
    Bras & Panties
    budeguer
    Budeguer
    cafe-martinez
    Café Martinez
    calzados-california
    Calzados California
    caramelos-lipo
    Caramelos Lipo
    cardon
    CARDON
    carrousel
    Carrousel
    catan-shopping
    Catan Shopping
    cbse
    CBSé
    cebra
    Cebra
    cerini
    Cerini
    chibel
    chibel
    citykids
    Citykids
    class-life
    Class Life
    clona
    Clona
    codere
    codere
    colombraro
    Colombraro
    complot
    Complot
    cresta-roja
    Cresta Roja
    cristobal-colon
    Cristobal Colon
    delaostia
    DELAOSTIA
    diezindiecitos
    Diez Indiecitos
    diuff
    Diuff
    don-satur
    Don Satur
    establecimiento-las-marias
    Establecimiento Las Marias
    fachitas
    Fachitas
    farmesa
    Farmesa
    frigorifico-calchaqui
    Frigorifico Calchaqui
    gaelle
    Gaelle
    galletitas-cilo
    Galletitas Cilo
    galletitas-trio
    Galletitas TRIO
    general-cereals
    General Cereals
    genomma-lab
    Genomma Lab.
    georgalos
    Georgalos
    getien
    Getien
    gimos
    Gimos
    giro-didactico
    Giro Didáctico
    gravagna
    Calzados Gravagna
    grupo-gaona
    Grupo Gaona
    heredia-infusiones
    Heredia Infusiones
    hileret
    Hileret
    hojalmar
    Hojalmar
    iberia-hogar
    IBERIA
    icbc
    ICBC
    india-style
    India Style
    jaguar-kids
    JAGUAR Kids
    jaguar
    JAGUAR
    keek
    KEEK
    key-biscayne
    Key Biscayne
    kiero
    Kiero
    kinderland
    Kinderland
    laboratorio-internacional-argentino
    Laboratorio Internacional Argentino
    lacteos-veronica
    Verónica
    lady-comfort
    Lady Comfort
    little-akiabara
    Little Akiabara
    lucerna
    LUCERNA
    marolio
    Marolio
    mervick
    Mervick
    natacha
    NATACHA
    nazaria-zapatos
    NAZARIA ZAPATOS
    neosol
    Neosol
    nevares
    Nevares
    new-plast
    NEW PLAST
    new-toys
    New Toy's
    nivea
    NIVEA
    pampagourmet
    Pampagourmet
    parnor
    Parnor
    perlea-maidenform
    Perlea + Maidenform
    peuque-jeans
    Peuque
    philips-healthcare
    Philips Healthcare
    plumitas
    Plumitas
    rosamonte
    Rosamonte
    royal-canin
    Royal Canin
    ruibal
    RUIBAL
    sibyl-vane
    Sibyl Vane
    soriano
    Soriano
    square
    SQUARE
    tapamania
    TAPAMANIA
    tia-maruca
    Tía Maruca
    toot
    TOOT
    top-toys
    Top Toys
    toyco
    ToyCo
    valdez
    VALDEZ
    valente
    Valente
    vie-tur
    Vie Tur
    wabro
    WABRO
    yetem
    YETEM
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Lea, ahi ya estan todas las marcas subidas a chat.benteveo.tv
Lo que si, falta el CSS de las marcas viejas, las nuevas, principalmente las que taché en el primer post de este issue, ya estan.

**Comment by LeandroBraier** [comment]
Gracias, Fede, pero no las encuentro. Me pasás la lista de URL de cada una así las puedo ver?

**Comment by FAAREIA** [comment]
Ponele asi:
http://chat.benteveo.tv/NOMBRE-MARCA

Te mando al mail la lista de los nombres de las marcas

**Comment by LeandroBraier** [comment]
Los veo perfectos. Pasamelos directamente a benteveo.tv así te doy feedback
final.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-06 12:19 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya esta subido a benteveo.tv

http://benteveo.tv/arancio/
http://benteveo.tv/bacchio/
http://benteveo.tv/chevanne/
http://benteveo.tv/chocorisimo/
http://benteveo.tv/copahue-helados/
http://benteveo.tv/cremolatti/
http://benteveo.tv/devas/
http://benteveo.tv/ditoys/
http://benteveo.tv/el-fundador/
http://benteveo.tv/eurocrem/
http://benteveo.tv/faricci/
http://benteveo.tv/frahel/
http://benteveo.tv/fraise/
http://benteveo.tv/grido-helado/
http://benteveo.tv/helados-schietto/
http://benteveo.tv/iglu-helados/
http://benteveo.tv/jazmin-chebar/
http://benteveo.tv/la-martina/
http://benteveo.tv/la-toscana/
http://benteveo.tv/las-pepas/
http://benteveo.tv/lazaro/
http://benteveo.tv/le-ble/
http://benteveo.tv/minicuotas-ribeiro/
http://benteveo.tv/tierra-norte/
http://benteveo.tv/triple-w/

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://benteveo.tv/ladder-propiedades/
http://benteveo.tv/lado-u/
http://benteveo.tv/emporio-dental/
http://benteveo.tv/upa/
http://benteveo.tv/dafaplast/
http://benteveo.tv/todo-para-cocinar/
http://benteveo.tv/gluia-tours/
http://benteveo.tv/agostina-bianchi/
http://benteveo.tv/elbita/
http://benteveo.tv/astton/
http://benteveo.tv/vanessa-strach/

Continuo con la cuarta tanda?

**Comment by LeandroBraier** [comment]
adelante fede!

gracias

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, estoy revisando. Las que ya hiciste están OK, pero me están faltando dos de esta lista:

Eurocream
http://www.eurocrem.com.ar/home.php

Il Cavallino
www.ilcavallino.com.ar

abrazo

**Comment by FAAREIA** [comment]
http://benteveo.tv/eurocrem/

Il Cavallino no existe más en realidad, es tierra norte ahora:
http://www.benteveo.tv/tierra-norte/

Los tipos habrán conservado el dominio por la popularidad del mismo. Lo correcto sería que hiciera una redirección de ese dominio a su nuevo dominio con el nombre de su marca actual.

**Comment by LeandroBraier** [comment]
Gracias Fede!
