### ISSUE TITLE
Cuarta Tanda de Landings Benteveo para el Jueves 13

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#19]
Va la cuarta tanda de landings:

~~Daniel Cassin~~
http://www.danielcassin.net/

~~Fotty~~
http://www.footy.com.ar/index.php

~~Giro didactico~~
http://www.girodidactico.com/

~~Grabatto~~
http://www.grabatto.com/

~~Jackie Smith~~
http://jackiesmith.com/

~~Janet wise~~
http://www.janetwise.com.ar/

~~keywhoss  Amar srl~~
http://www.keywhoss.com/

~~Leandro Dominguez~~
http://www.leandrodominguez.com/home.html

~~Lody~~
http://www.lody.com.ar/

~~Maggio Rossetto~~
http://www.maggiorossetto.com/

~~Koury~~
http://www.marcelakoury.com.ar/mkver15/index.asp

~~Maria Rivolta~~
http://mariarivolta.com/

~~Markova~~
http://www.markova.com/

~~Melocoton~~
http://www.e-melocoton.com.ar/

~~Muaa~~
http://www.muaa.com.ar/

~~Nasa jeans~~
http://www.nasa.com.ar/

~~Natacha~~
http://www.natachaweb.com.ar/

~~Ossira~~
http://www.ossira.com/pri_ver_2015/

~~Paruolo~~
http://www.paruolo.com.ar/

~~Perramus~~
http://www.perramus.com.ar/

~~Fantoche Dielo SA~~
www.fantoche.com.ar

~~apotex~~
https://www.apotex.com/global/worldwide/

~~arcano~~
http://www.arcanolab.com.ar/

~~aspen~~
http://www.aspen-lab.com/

~~Laboratorio austral~~
http://www.laboratorioaustral.com.ar/

~~Awer  ~~
http://www.awer.com.ar/

~~Bago~~
http://www.bago.com.ar/

~~Benitol~~
http://www.delaboratorios.com/wp-content/uploads/2011/05/Laboratoorios-Benitol-SACI.jpg

~~bioprofarma~~
http://www.bioprofarma.com/

~~FERRERO ROCHER/KINDER/TIC TAC FERRERO ARGENTINS SA~~
http://www.ferrero.com.ar/

~~La cabrera~~
http://www.parrillalacabrera.com.ar/

~~il gatto~~
http://www.ilgatto.com.ar/

~~rochas~~
http://www.rochasweb.com/

~~r301~~
http://www.r301.com.ar/

~~Mamy blue~~
http://www.mamyblue.com.ar/

abrazo

**Comment by FAAREIA** [comment]
http://benteveo.tv/daniel-cassin/
http://benteveo.tv/footy/
http://benteveo.tv/grabatto/
http://benteveo.tv/jackie-smith/
http://benteveo.tv/janet-wise/
http://benteveo.tv/keywhoss/
http://benteveo.tv/leandro-dominguez/
http://benteveo.tv/lody/
http://benteveo.tv/maggio-rossetto/
http://benteveo.tv/marcela-koury/
http://benteveo.tv/maria-rivolta/
http://benteveo.tv/markova/
http://benteveo.tv/melocoton/
http://benteveo.tv/muaa/
http://benteveo.tv/nasa/
http://benteveo.tv/ossira/
http://benteveo.tv/paruolo/
http://benteveo.tv/perramus/
http://benteveo.tv/fantoche/
http://benteveo.tv/apotex/
http://benteveo.tv/arcano-sa/
http://benteveo.tv/laboratorios-aspen/
http://benteveo.tv/laboratorios-austral/
http://benteveo.tv/awer-laboratorios/
http://benteveo.tv/laboratorios-bago/
http://benteveo.tv/laboratorios-benitol/
http://benteveo.tv/laboratorios-bioprofarma/
http://benteveo.tv/ferrero/
http://benteveo.tv/la-cabrera/
http://benteveo.tv/il-gatto/
http://benteveo.tv/rochas/
http://benteveo.tv/r301/
http://benteveo.tv/mamy-blue/

**Comment by LeandroBraier** [comment]
Gracias Fede! Hoy reviso y te doy feedback cualquier cosa. Funcionó lo del CMS parece no?

**Comment by FAAREIA** [comment]
Si, funciona, pero estan hechas a mano. El CMS esta en el hosting nuevo de Benteveo.
Habría que pasarlo cuanto antes, o cuando venga la próxima tanda

**Comment by LeandroBraier** [comment]
Fede, están OK estas. Solo te pido que la de Natacha la pases a negra con fondo blanco.

**Comment by FAAREIA** [comment]
Ahi esta listo el ajuste de Natacha, dale F5

**Comment by LeandroBraier** [comment]
Genial, Fede! Gracias!
