### ISSUE TITLE
Pop Up en web Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#2]
Fede, necesitamos sumar un Pop Up de solo texto en la Web de Benteveo en los casos en que alguien siga un link que viene de un determinado video de YouTube. El texto debería decir lo siguiente:

"Nos contactaremos a la brevedad para coordinar un encuentro. ¡Gracias!"

Al cerrarse, simplemente el pop up simplemente queda la web de Benteveo corriendo.

abrazo

**Comment by FAAREIA** [comment]
mmmmmmmmmmmmmm, preguntas:
- ¿Cual sería la url que van a poner detro del video de youtube?
- El texto dice algo como si recien hubiese completado y enviado un formulario de contacto, ¿se tiene que enviar algún email o algún aviso a benteveo?
- Por lo que eniendo el pop nunca se cierra a pesar de que hay una cruz para cerrar....puede ser?
- El popup va a permitir navegar en la web o la oscurece?
- Si se navega en la web, el popup sigue el scroll como si fuese el menú de paty?

**Comment by LeandroBraier** [comment]
Te respondo punto por punto:

. ¿Cual sería la url que van a poner detro del video de youtube? RESPUESTA: La que vos nos digas.
. El texto dice algo como si recien hubiese completado y enviado un formulario de contacto, ¿se tiene que enviar algún email o algún aviso a benteveo? RESPUESTA: Con que el sistema registre que esa url fue visitada nos alcanza para saber quién es la persona y contactarnos con él.
. Por lo que entiendo el pop nunca se cierra a pesar de que hay una cruz para cerrar....puede ser? RESPUESTA: No, me refería a la X para cerrar habitual, común y corriente. Quizá me expliqué confuso.
. El popup va a permitir navegar en la web o la oscurece? RESPUESTA: El pop la oscurece, luego de cerrada sí se puede navegar, obviamente. Es igual que los del sitio de Dánica pero con color azul ponele. O como te sea más fácil a vos.
. Si se navega en la web, el popup sigue el scroll como si fuese el menú de paty? RESPUESTA: Preferentemente no, pero como te sea más fácil a vos.

**Comment by FAAREIA** [comment]
Hola Lea, lo subí aca:
http://www.benteveo.tv/_btv2/?yt=1

El agregado de " ?yt=1 " es lo que dispara el mensaje inicial.
El ser simplemente un mensaje, me parece que al cerrarlo debería de desaparecer por completo. No tiene sentido que quede sobre o al costado del video, ya que bajas con el scroll y no lo ves más. Además por el tipo de mensaje, no veo necesario de que se quede ocupando espacio en alguna parte por la que el usuario simplemente ve y sigue.

Decime si te parece bien,
abrazo

**Comment by LeandroBraier** [comment]
Lo veo bien q cierre solo. Fijate si podes ponerlo en texto minúscula, que quede un poco más elegante, y estamos.

Abrazo

**Comment by FAAREIA** [comment]
ahi esta listo lea

**Comment by LeandroBraier** [comment]
Perfecto, Fede!

Gracias. Cualquier cosa te aviso.

**Comment by LeandroBraier** [comment]
Fede, no lo veo al pop up al ingresar al link. Lo reabro porque te tengo que pasar un cambio de texto y un pop up más con un texto distinto.

**Comment by FAAREIA** [comment]
Hola Lea, lo borré.
El nuevo link es: http://www.benteveo.tv/?yt=1
En el sitio oficial ya esta implementado

**Comment by LeandroBraier** [comment]
Genial. Me quedo el ticket para pasarte los textos finales cuando los tenga.

Saludos!

**Comment by LeandroBraier** [comment]
Fede, ya tengo los textos finales de estos pop ups.

Haciendo clic en el botón "Quiero que me contacten" le aparecería el siguiente mensaje:

TEXTO POP UP 1: ¡Genial! Nos contactaremos via mail para coordinar el encuentro. Gracias.”

Haciendo clic en el botón "Quiero que me inviten a almorzar." le aparecería el siguiente pop up.

TEXTO POP UP 2: ¡Qué bueno! Un almuerzo es el mejor aperitivo para una gran idea. Nos contactaremos vía mail. Gracias.

abrazo
