### ISSUE TITLE
Quinta Tanda de Landings Benteveo para el Jueves 20

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#24]
Fede, va otra tanda de landings. Para estas seguro ya podés usar el CMS. Te sugiero una URL para cada uno. Intentá respetarla todo lo posible por favor. abrazo

~~mimo~~
http://benteveo.tv/mimo/  
http://www.mimo.com.ar/

~~taller del Girasol~~
http://benteveo.tv/taller-del-girasol/  
http://www.tallerdelgirasol.com.ar/

~~Tannery~~
http://benteveo.tv/tannery/ 
http://www.tannery.com.ar/

~~Tascani~~
http://benteveo.tv/tascani/ 
http://www.tascani.com.ar/

~~Testorelli~~
http://benteveo.tv/testorelli/  
http://www.testorellionline.com/

~~theodosia~~
http://benteveo.tv/theodosia/  
http://www.theodosia.com.ar/v2/

~~Timberland~~
http://benteveo.tv/timberland/  
http://www.timberland.com/

~~tonel privado~~
http://benteveo.tv/tonel-privado/  
http://www.tonelprivado.com/

~~Uma~~
http://benteveo.tv/uma/ 
http://uma.com.ar/

~~Undici~~
http://benteveo.tv/undici/  
http://www.undici.com.ar

~~Vandalia~~
http://benteveo.tv/vandalia/  
http://www.vandalia.com.ar/

~~viamo~~
http://benteveo.tv/viamo/  
http://www.viamo.com/

~~vz~~
http://benteveo.tv/vz/  
http://www.vzproducciones.com/

~~Wanama~~
http://benteveo.tv/wanama/  
http://www.wanama.com/

~~Winery~~
http://benteveo.tv/winery/  
http://www.winery.com.ar/

~~wrangler~~
http://benteveo.tv/wrangler/  
http://www.wrangler-jeans.com.ar/

~~xl extra large~~
http://benteveo.tv/xl-extra-large/  
http://www.xlshop.com.ar/

~~yagmour~~
http://benteveo.tv/yagmour/ 
http://www.yagmour.com.ar/

~~yenny-el ateneo-tematika~~
http://benteveo.tv/tematika/  
http://www.yenny-elateneo.com/

~~ABERDEEN ANGUS~~
http://benteveo.tv/aberdeen-angus/
www.angusparrilla.com.ar

~~almacen de pizza~~
http://benteveo.tv/almacen-de-pizza/  
www.almacendepizzas.com

~~antares~~
http://benteveo.tv/antares/ 
http://www.cervezaantares.com/

~~balcarce~~
http://benteveo.tv/balcarce/  
http://www.postresbalcarce.com.ar/

~~bonafide~~
http://benteveo.tv/bonafide/  
http://www.bonafide.com.ar/

~~nucha~~
http://benteveo.tv/nucha/  
http://nucha.com.ar/

~~Piacere~~
http://benteveo.tv/piacere/ 
http://www.piacere.com.ar/

~~sushi club~~
http://benteveo.tv/sushi-club/  
www.sushiclubweb.com

~~the cofee store~~
http://benteveo.tv/the-cofee-store/ 
www.thecoffeestore.com

~~tienda de café~~
http://benteveo.tv/tienda-de-cafe/  
www.tiendadecafe.com.ar

~~atomik~~
http://benteveo.tv/atomik/  
http://www.atomik.com.ar/

~~advanced~~
http://benteveo.tv/advanced/  
http://www.advanced-adv.com/

~~camaron brujo~~
http://benteveo.tv/camaron-brujo/  
http://www.camaronbrujo.com/

~~Christian lacroix~~
http://benteveo.tv/christian-lacroix/  
www.christianlacroix.com.ar

~~Dufour~~
http://benteveo.tv/dufour/  
www.dufourarg.com

~~estancias chiripa~~
http://benteveo.tv/estancias-chiripa/  
http://www.estanciaschiripa.com.ar/

~~legacy~~
http://benteveo.tv/legacy/  
http://www.legacy.com.ar/

~~Newman~~
http://benteveo.tv/newman/  
www.newmanargentina.com.ar

~~5asec~~
http://benteveo.tv/5asec/  
http://www.5asec.com/es

~~europcar~~
http://benteveo.tv/europcar/  
http://www.europcar.com.ar/

~~la cartuchera ecologica~~
http://benteveo.tv/la-cartuchera-ecologica/ 
http://www.lacartuchera.com.ar/

~~arredo~~
http://benteveo.tv/arredo/  
http://arredo.com.ar/

~~carven~~
http://benteveo.tv/carven/  
http://www.carven.com.ar/

~~pioppa~~
http://benteveo.tv/pioppa/  
http://www.pioppa.com.ar/primavera-verano-2015/

~~positivo~~
http://benteveo.tv/positivo/  
http://www.positivodesign.com.ar

~~baby cottons~~
http://benteveo.tv/baby-cottons/  
http://www.babycottons.com/argentina/

~~cuesta blanca~~
http://benteveo.tv/cuesta-blanca/  
http://www.cuestablanca.com.ar/

~~kel ediciones~~
http://benteveo.tv/kel-ediciones/  
http://www.kelediciones.com/

~~koxis~~
http://benteveo.tv/koxis/  
http://www.koxis.com/

~~La argentina~~
http://benteveo.tv/la-argentina/  
http://www.clargentina.com.ar/

~~Maru Botana~~
http://benteveo.tv/maru-botana/ 
http://www.marubotana.com/

**Comment by FAAREIA** [comment]
Los siguientes nombres los tuve que cambiar porque faltaba una palabra o una letra o un "-" en la marca:

testorelli-1887
almacen-de-pizzas
the-coffee-store
camaronbrujo
new-man
babycottons

**Comment by LeandroBraier** [comment]
Perfecto, ya están todos entonces?

**Comment by FAAREIA** [comment]
No, estoy en eso. Esta vez empecé al revés, asi marce me generaba todos los html desde el cms

**Comment by LeandroBraier** [comment]
Ahora sí ya están no?

**Comment by FAAREIA** [comment]
Hola Lea, no, aún no estan. Faltan 19 creo. Con todo lo que hubo, se retrasó bastante esto.

**Comment by LeandroBraier** [comment]
Ok, mientras estén ponele para el viernes estamso OK, no problem.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://chat.benteveo.tv/mimo/
http://chat.benteveo.tv/taller-del-girasol/
http://chat.benteveo.tv/tannery/
http://chat.benteveo.tv/tascani/
http://chat.benteveo.tv/testorelli-1887/
http://chat.benteveo.tv/theodosia/
http://chat.benteveo.tv/timberland/
http://chat.benteveo.tv/tonel-privado/
http://chat.benteveo.tv/uma/
http://chat.benteveo.tv/undici/
http://chat.benteveo.tv/vandalia/
http://chat.benteveo.tv/viamo/
http://chat.benteveo.tv/vz/
http://chat.benteveo.tv/wanama/
http://chat.benteveo.tv/winery/
http://chat.benteveo.tv/wrangler/
http://chat.benteveo.tv/xl-extra-large/
http://chat.benteveo.tv/yagmour/
http://chat.benteveo.tv/tematika/
http://chat.benteveo.tv/aberdeen-angus/
http://chat.benteveo.tv/almacen-de-pizzas/
http://chat.benteveo.tv/antares/
http://chat.benteveo.tv/balcarce/
http://chat.benteveo.tv/bonafide/
http://chat.benteveo.tv/nucha/
http://chat.benteveo.tv/piacere/
http://chat.benteveo.tv/sushi-club/
http://chat.benteveo.tv/the-coffee-store/
http://chat.benteveo.tv/tienda-de-cafe/
http://chat.benteveo.tv/advanced/
http://chat.benteveo.tv/camaronbrujo/
http://chat.benteveo.tv/christian-lacroix/
http://chat.benteveo.tv/dufour/
http://chat.benteveo.tv/estancias-chiripa/
http://chat.benteveo.tv/legacy/
http://chat.benteveo.tv/new-man/
http://chat.benteveo.tv/5asec/
http://chat.benteveo.tv/europcar/
http://chat.benteveo.tv/la-cartuchera-ecologica/
http://chat.benteveo.tv/arredo/
http://chat.benteveo.tv/carven/
http://chat.benteveo.tv/pioppa/
http://chat.benteveo.tv/positivo/
http://chat.benteveo.tv/babycottons/
http://chat.benteveo.tv/cuesta-blanca/
http://chat.benteveo.tv/kel-ediciones/
http://chat.benteveo.tv/koxis/
http://chat.benteveo.tv/la-argentina/
http://chat.benteveo.tv/maru-botana/

**Comment by FAAREIA** [comment]
5asec aún no esta visible, no toma los estilos, Marce va hacer un ajuste en el cms para mañana.

**Comment by LeandroBraier** [comment]
Fede, veo que el de 5asec ya está listo. Solo queda que los pases todos a la url de BENTEVEO.TV y estamos.

**Comment by FAAREIA** [comment]
http://benteveo.tv/mimo/
http://benteveo.tv/taller-del-girasol/
http://benteveo.tv/tannery/
http://benteveo.tv/tascani/
http://benteveo.tv/testorelli-1887/
http://benteveo.tv/theodosia/
http://benteveo.tv/timberland/
http://benteveo.tv/tonel-privado/
http://benteveo.tv/uma/
http://benteveo.tv/undici/
http://benteveo.tv/vandalia/
http://benteveo.tv/viamo/
http://benteveo.tv/vz/
http://benteveo.tv/wanama/
http://benteveo.tv/winery/
http://benteveo.tv/wrangler/
http://benteveo.tv/xl-extra-large/
http://benteveo.tv/yagmour/
http://benteveo.tv/tematika/
http://benteveo.tv/aberdeen-angus/
http://benteveo.tv/almacen-de-pizzas/
http://benteveo.tv/antares/
http://benteveo.tv/balcarce/
http://benteveo.tv/bonafide/
http://benteveo.tv/nucha/
http://benteveo.tv/piacere/
http://benteveo.tv/sushi-club/
http://benteveo.tv/the-coffee-store/
http://benteveo.tv/tienda-de-cafe/
http://benteveo.tv/advanced/
http://benteveo.tv/camaronbrujo/
http://benteveo.tv/christian-lacroix/
http://benteveo.tv/dufour/
http://benteveo.tv/estancias-chiripa/
http://benteveo.tv/legacy/
http://benteveo.tv/new-man/
http://benteveo.tv/5asec/
http://benteveo.tv/europcar/
http://benteveo.tv/la-cartuchera-ecologica/
http://benteveo.tv/arredo/
http://benteveo.tv/carven/
http://benteveo.tv/pioppa/
http://benteveo.tv/positivo/
http://benteveo.tv/babycottons/
http://benteveo.tv/cuesta-blanca/
http://benteveo.tv/kel-ediciones/
http://benteveo.tv/koxis/
http://benteveo.tv/la-argentina/
http://benteveo.tv/maru-botana/

Habría que apurar la mudanza otra vez, es todo un tema pasar esto de un lugar a otro.

**Comment by FAAREIA** [comment]
Igual aguanta que tengo que corregir un bug de c/u ahora que veo

**Comment by LeandroBraier** [comment]
Ok. Coordiná la mudanza con MS y MK porfa. Si está para el lunes está OK.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-28 16:47 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Claro, el tema es que el otro Federico tiene que backupear los emails y mandarnoslos. Recien ahi, subimos ese backup y ahi empieza el proceso de poner claves y cambiar config de los clientes que usen.

**Comment by FAAREIA** [comment]
Ahi esta todo, por fa fijate si estan todos OK. No debería haber ningun problema.

**Comment by LeandroBraier** [comment]
Perfecto, yo las reviso. Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, están todas OK. Ya están en el server correspondiente? Confirmame esto porfa asi cierro el ticket..

**Comment by FAAREIA** [comment]
Si, ya estan todas en el server actual.
Me colgué en responder ^^

**Comment by LeandroBraier** [comment]
Genial!
