### ISSUE TITLE
Sexta Tanda de Landings Benteveo para el Martes 25

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#25]
Va la sexta. Necesitaría que intentes respetar también las URL propuestas.

~~body sculpt   http://benteveo.tv/body-sculpt/ http://www.bodysculpt.com.ar/~~
~~cara cruz http://benteveo.tv/cara-cruz/   http://www.caracruzjeans.com.ar/~~
~~chiarini  http://benteveo.tv/chiarini/    http://www.chiariniweb.com.ar/~~
~~admit one http://benteveo.tv/admit-one/   http://www.admitone.com.ar/~~
~~taverniti http://benteveo.tv/taverniti/   http://www.taverniti.com.ar/~~
~~adriana constantini   http://benteveo.tv/adriana-constantini/ http://www.adrianacostantini.com.ar/~~
~~grimoldi  http://benteveo.tv/grimoldi/    http://www.grimoldi.com/~~
~~sarkany   http://benteveo.tv/sarkany/ http://www.rickysarkany.com/~~
~~selu  http://benteveo.tv/selu/    http://www.selu.com.ar/~~
~~swatch    http://benteveo.tv/swatch/  http://www.swatch.com/es_ar/~~
~~via uno   http://benteveo.tv/via-uno/ http://www.viauno.com.ar/~~
~~class life    http://benteveo.tv/class-life/  http://www.classlife.com.ar/web/lookbook.php~~
~~kevingston    http://benteveo.tv/kevingston/  http://www.kevingston.com/~~
~~hannah collins    http://benteveo.tv/hannah-collins/~~
~~pantene   http://benteveo.tv/pantene/ http://www.pantene.com.ar/~~
~~silkey    http://benteveo.tv/silkey/  http://www.silkey.com.ar/index_esp.html~~
~~Le Coq    http://benteveo.tv/le-coq/  http://www.lecoqsportif.com/intl-es/~~
~~Angel ane http://benteveo.tv/angel-ane/   WWW.ANGELANE.COM.AR~~
~~Innocenza http://benteveo.tv/innocenza/   www.innocenza.com.ar~~
Sweet victorian http://benteveo.tv/sweet-victorian/ http://www.sweetvictorian.com/
~~peter pan http://benteveo.tv/peter-pan/   http://www.peter-pan.com.ar~~
~~piero http://benteveo.tv/piero/   http://www.piero.com.ar/~~
~~pigmento  http://benteveo.tv/pigmento/    http://www.perfumeriaspigmento.com.ar~~
~~algabo    http://benteveo.tv/algabo/  http://www.algabo.com~~
~~tsu   http://benteveo.tv/tsu/ www.tsucosmeticos.com.ar~~
~~Coty  http://benteveo.tv/coty/    www.coty.com~~
~~Lef cosmeticos    http://benteveo.tv/lef-cosmeticos/  www.esteticafrancesa.com.ar~~
Laca    http://benteveo.tv/laca/    www.lacacosmetica.com
~~Millanel http://benteveo.tv/millanel/ www.millanel.com.ar~~
Deisel  http://benteveo.tv/deisel/  www.cosmeticadeisel.com.ar
Dcc sa  http://benteveo.tv/dcc-sa/  www.dccsa.com.ar
iquisa  http://benteveo.tv/iquisa/  http://www.iquisa.com.ar
Adromaco    http://benteveo.tv/adromaco/    http://www.andromaco.com.ar/
laboratorio Victoria    http://benteveo.tv/laboratorio-victoria/    http://www.labvictoria.com/
Laboratorio Warnic  http://benteveo.tv/laboratorio-warnic/  http://www.warmic.com.ar/
nerova  http://benteveo.tv/nerova/  http://www.nerova.com/espanol.htm
Plumari http://benteveo.tv/plumari/ http://www.plumari.com.ar/
iyosei  http://benteveo.tv/iyosei/  http://www.iyosei.com.ar/2012/espanol/
amyris  http://benteveo.tv/amyris/  http://www.amyris.com.ar/
buplasa http://benteveo.tv/buplasa/ http://www.buplasa.com
chemoil http://benteveo.tv/chemoil/ http://www.chemoil.com.ar/
Domitec http://benteveo.tv/domitec/ http://www.domitecsa.com.ar/
eco oil http://benteveo.tv/eco-oil/ http://www.ecooil.com.ar
Fritzsche   http://benteveo.tv/fritzsche/   http://www.fritzschesaica.com/
Glas car    http://benteveo.tv/glas-car/    http://www.glascar.com.ar/
quimtia http://benteveo.tv/quimtia/ http://www.quimtia.com
Cantua  http://benteveo.tv/cantua/  http://www.laboratoriocantua.com.ar/esp/index.htm
escos   http://benteveo.tv/escos/   http://www.escos.com.ar/
Mi flora    http://benteveo.tv/mi-flora/    http://www.labmiflora.com.ar

**Comment by mkreyness** [comment]
```
Veo que aca incluis una URL del cliente, eso no estaba previsto en
el CMS.
Fede: decime si queres que lo agregue y pone el lugar para
reemplazarlo en el /template (y avisame el nombre)

El 12/11/2014 a las 20:08,
  LeandroBraier escribió:


  Va la sexta. Necesitaría que intentes respetar también las URL
    propuestas.
  body sculpt http://benteveo.tv/body-sculpt/
    http://www.bodysculpt.com.ar/
    cara cruz http://benteveo.tv/cara-cruz/
    http://www.caracruzjeans.com.ar/
    chiarini http://benteveo.tv/chiarini/
    http://www.chiariniweb.com.ar/
    admit one http://benteveo.tv/admit-one/
    http://www.admitone.com.ar/
    taverniti http://benteveo.tv/taverniti/
    http://www.taverniti.com.ar/
    adriana constantini http://benteveo.tv/adriana-constantini/
    http://www.adrianacostantini.com.ar/
    grimoldi http://benteveo.tv/grimoldi/
    http://www.grimoldi.com/
    sarkany http://benteveo.tv/sarkany/
    http://www.rickysarkany.com/
    selu http://benteveo.tv/selu/
    http://www.selu.com.ar/
    swatch http://benteveo.tv/swatch/
    http://www.swatch.com/es_ar/
    via uno http://benteveo.tv/via-uno/
    http://www.viauno.com.ar/
    class life http://benteveo.tv/class-life/
    http://www.classlife.com.ar/web/lookbook.php
    kevingston http://benteveo.tv/kevingston/
    http://www.kevingston.com/
    hannah collins http://benteveo.tv/hannah-collins/

    pantene http://benteveo.tv/pantene/
    http://www.pantene.com.ar/
    silkey http://benteveo.tv/silkey/
    http://www.silkey.com.ar/index_esp.html
    Le Coq http://benteveo.tv/le-coq/
    http://www.lecoqsportif.com/intl-es/
    Angel ane http://benteveo.tv/angel-ane/
    WWW.ANGELANE.COM.AR
    Innocenza http://benteveo.tv/innocenza/
    www.innocenza.com.ar
    Sweet victorian http://benteveo.tv/sweet-victorian/
    http://www.sweetvictorian.com/
    peter pan http://benteveo.tv/peter-pan/
    http://www.peter-pan.com.ar
    piero http://benteveo.tv/piero/
    http://www.piero.com.ar/
    pigmento http://benteveo.tv/pigmento/
    http://www.perfumeriaspigmento.com.ar
    algabo http://benteveo.tv/algabo/
    http://www.algabo.com
    tsu http://benteveo.tv/tsu/
    www.tsucosmeticos.com.ar
    Coty http://benteveo.tv/coty/
    www.coty.com
    Lef cosmeticos http://benteveo.tv/lef-cosmeticos/
    www.esteticafrancesa.com.ar
    Laca http://benteveo.tv/laca/
    www.lacacosmetica.com
    Millanel http://benteveo.tv/millanel/
    www.millanel.com.ar
    Deisel http://benteveo.tv/deisel/
    www.cosmeticadeisel.com.ar
    Dcc sa http://benteveo.tv/dcc-sa/
    www.dccsa.com.ar
    iquisa http://benteveo.tv/iquisa/
    http://www.iquisa.com.ar
    Adromaco http://benteveo.tv/adromaco/
    http://www.andromaco.com.ar/
    laboratorio Victoria http://benteveo.tv/laboratorio-victoria/
    http://www.labvictoria.com/
    Laboratorio Warnic http://benteveo.tv/laboratorio-warnic/
    http://www.warmic.com.ar/
    nerova http://benteveo.tv/nerova/
    http://www.nerova.com/espanol.htm
    Plumari http://benteveo.tv/plumari/
    http://www.plumari.com.ar/
    iyosei http://benteveo.tv/iyosei/
    http://www.iyosei.com.ar/2012/espanol/
    amyris http://benteveo.tv/amyris/
    http://www.amyris.com.ar/
    buplasa http://benteveo.tv/buplasa/
    http://www.buplasa.com
    chemoil http://benteveo.tv/chemoil/
    http://www.chemoil.com.ar/
    Domitec http://benteveo.tv/domitec/
    http://www.domitecsa.com.ar/
    eco oil http://benteveo.tv/eco-oil/
    http://www.ecooil.com.ar
    Fritzsche http://benteveo.tv/fritzsche/
    http://www.fritzschesaica.com/
    Glas car http://benteveo.tv/glas-car/
    http://www.glascar.com.ar/
    quimtia http://benteveo.tv/quimtia/
    http://www.quimtia.com
    Cantua http://benteveo.tv/cantua/
    http://www.laboratoriocantua.com.ar/esp/index.htm
    escos http://benteveo.tv/escos/
    http://www.escos.com.ar/
    Mi flora http://benteveo.tv/mi-flora/
    http://www.labmiflora.com.ar
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
No, Marce. La URL del cliente, es decir, el link a su página web, es sólo
para que Fede tenga a mano y pueda ver qué logo y colores necesita usar en
la landing local. Si es eso no afecta al CMS.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
```
Ah, ok.

El 12/11/2014 a las 21:30,
  LeandroBraier escribió:

No, Marce. La URL del cliente, es decir, el link a su
  página web, es sólo

  para que Fede tenga a mano y pueda ver qué logo y colores necesita
  usar en

  la landing local. Si es eso no afecta al CMS.


  abrazo


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  On Wed, Nov 12, 2014 at 8:52 PM, mkreyness
  <notifications@github.com> wrote:


  >

  >

  >

  >

  >

  > Veo que aca incluis una URL del cliente, eso no estaba
  previsto en

  > el CMS.

  > Fede: decime si queres que lo agregue y pone el lugar para

  > reemplazarlo en el /template (y avisame el nombre)

  >

  > El 12/11/2014 a las 20:08,

  > LeandroBraier escribió:

  >

  >

  > Va la sexta. Necesitaría que intentes respetar también las
  URL

  > propuestas.

  > body sculpt http://benteveo.tv/body-sculpt/

  > http://www.bodysculpt.com.ar/

  > cara cruz http://benteveo.tv/cara-cruz/

  > http://www.caracruzjeans.com.ar/

  > chiarini http://benteveo.tv/chiarini/

  > http://www.chiariniweb.com.ar/

  > admit one http://benteveo.tv/admit-one/

  > http://www.admitone.com.ar/

  > taverniti http://benteveo.tv/taverniti/

  > http://www.taverniti.com.ar/

  > adriana constantini http://benteveo.tv/adriana-constantini/

  > http://www.adrianacostantini.com.ar/

  > grimoldi http://benteveo.tv/grimoldi/

  > http://www.grimoldi.com/

  > sarkany http://benteveo.tv/sarkany/

  > http://www.rickysarkany.com/

  > selu http://benteveo.tv/selu/

  > http://www.selu.com.ar/

  > swatch http://benteveo.tv/swatch/

  > http://www.swatch.com/es_ar/

  > via uno http://benteveo.tv/via-uno/

  > http://www.viauno.com.ar/

  > class life http://benteveo.tv/class-life/

  > http://www.classlife.com.ar/web/lookbook.php

  > kevingston http://benteveo.tv/kevingston/

  > http://www.kevingston.com/

  > hannah collins http://benteveo.tv/hannah-collins/

  >

  > pantene http://benteveo.tv/pantene/

  > http://www.pantene.com.ar/

  > silkey http://benteveo.tv/silkey/

  > http://www.silkey.com.ar/index_esp.html

  > Le Coq http://benteveo.tv/le-coq/

  > http://www.lecoqsportif.com/intl-es/

  > Angel ane http://benteveo.tv/angel-ane/

  > WWW.ANGELANE.COM.AR

  > Innocenza http://benteveo.tv/innocenza/

  > www.innocenza.com.ar

  > Sweet victorian http://benteveo.tv/sweet-victorian/

  > http://www.sweetvictorian.com/

  > peter pan http://benteveo.tv/peter-pan/

  > http://www.peter-pan.com.ar

  > piero http://benteveo.tv/piero/

  > http://www.piero.com.ar/

  > pigmento http://benteveo.tv/pigmento/

  > http://www.perfumeriaspigmento.com.ar

  > algabo http://benteveo.tv/algabo/

  > http://www.algabo.com

  > tsu http://benteveo.tv/tsu/

  > www.tsucosmeticos.com.ar

  > Coty http://benteveo.tv/coty/

  > www.coty.com

  > Lef cosmeticos http://benteveo.tv/lef-cosmeticos/

  > www.esteticafrancesa.com.ar

  > Laca http://benteveo.tv/laca/

  > www.lacacosmetica.com

  > Millanel http://benteveo.tv/millanel/

  > www.millanel.com.ar

  > Deisel http://benteveo.tv/deisel/

  > www.cosmeticadeisel.com.ar

  > Dcc sa http://benteveo.tv/dcc-sa/

  > www.dccsa.com.ar

  > iquisa http://benteveo.tv/iquisa/

  > http://www.iquisa.com.ar

  > Adromaco http://benteveo.tv/adromaco/

  > http://www.andromaco.com.ar/

  > laboratorio Victoria http://benteveo.tv/laboratorio-victoria/

  > http://www.labvictoria.com/

  > Laboratorio Warnic http://benteveo.tv/laboratorio-warnic/

  > http://www.warmic.com.ar/

  > nerova http://benteveo.tv/nerova/

  > http://www.nerova.com/espanol.htm

  > Plumari http://benteveo.tv/plumari/

  > http://www.plumari.com.ar/

  > iyosei http://benteveo.tv/iyosei/

  > http://www.iyosei.com.ar/2012/espanol/

  > amyris http://benteveo.tv/amyris/

  > http://www.amyris.com.ar/

  > buplasa http://benteveo.tv/buplasa/

  > http://www.buplasa.com

  > chemoil http://benteveo.tv/chemoil/

  > http://www.chemoil.com.ar/

  > Domitec http://benteveo.tv/domitec/

  > http://www.domitecsa.com.ar/

  > eco oil http://benteveo.tv/eco-oil/

  > http://www.ecooil.com.ar

  > Fritzsche http://benteveo.tv/fritzsche/

  > http://www.fritzschesaica.com/

  > Glas car http://benteveo.tv/glas-car/

  > http://www.glascar.com.ar/

  > quimtia http://benteveo.tv/quimtia/

  > http://www.quimtia.com

  > Cantua http://benteveo.tv/cantua/

  > http://www.laboratoriocantua.com.ar/esp/index.htm

  > escos http://benteveo.tv/escos/

  > http://www.escos.com.ar/

  > Mi flora http://benteveo.tv/mi-flora/

  > http://www.labmiflora.com.ar

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/25#issuecomment-62817476
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Los siguientes nombres los tuve que cambiar porque faltaba una palabra o una letra o un "-" en la marca:

adriana-costantini
le-coq-sportif
angelane
lef
andromaco
laboratorios-victoria
laboratorios-warmic

**Comment by LeandroBraier** [comment]
Estos también ya están todos?

**Comment by LeandroBraier** [comment]
Fede, los que te falten de esta tanda y los de la séptima, quiero que los hagas sin logo ni color propios de las marcas. Simplemente customiza URL y botones, pero que todas las landings queden iguales. Fondo blanco y sin logo. Así ya te lo sacás de encima más rápido.

**Comment by FAAREIA** [comment]
Habría que poner algunos colores por defecto, sino es todo 100% negro. Pero si no ponemos ni colores de la maraca, ni logo, ya estaría todo hecho.

**Comment by LeandroBraier** [comment]
Buenisimo, avanzá así entonces. El color por defecto que te sirva y listo. Hacelos todos sin color ni logo de la marca.

abrazo

**Comment by FAAREIA** [comment]
Ok, entonces no grabo el video?

**Comment by LeandroBraier** [comment]
Si, grabalo así veo si es posible que lo hagamos nosotros y te lo saquemos
de encima, pero ya tenemos la quinta tanda. Esta sexta dejala para la
semana que viene. Necesito que te pongas con Siguit cuanto antes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, ahi grabé el video. Avisame si lo ves OK.
http://faareia.com/tutorial.7z

**Comment by LeandroBraier** [comment]
Gracias Fede, ahi lo estoy descargando. En qué formato está?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Lo intentó abrir y no puedo. No lo podrás subir a YouTube o algo así?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-28 20:30 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Fede, seguí nomás vos con las landings, es muy complejo para quitartelo. Pero recordá. Nada de logos y colores propios de la marca. Todo genérico, lo que hay que customizar son los links de los botones, las URL y títulos de las páginas.

abrazo

**Comment by FAAREIA** [comment]
Ok, primero siguit y dp esto no?

**Comment by LeandroBraier** [comment]
Fede, hablé con Eze y me pidió una reunión con vos la semana que viene para que nos expliques cómo modificar el código HTML y CSS nosotros. Asi ya te desentendés de la séptima tanda en adelante.

Respecto de la sexta tanda, la vamos a necesitar antes. Tenés posibilidad de tener toda la tanda lista para mañana? Siempre sin dejar de tener a Siguit como principal prioridad, claro.

**Comment by FAAREIA** [comment]
Ok, no hay problema con la reunion.
En total son como 44 las que faltan. Para mañana al mediodía pueden estar listas 20 más o 25 más.

**Comment by LeandroBraier** [comment]
Perfecto. Con eso tiramos jueves y viernes bien y después si el resto están
para el martes que viene estamos OK.

Podrías reunirte el martes o miércoles a las 10 am en la produ?

Supongo que veremos esto de HTML y CSS pero también lo de Siguit en el
estado en que esté.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-03 11:38 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si dale no hay prob.
Por otra parte, no esta confirmado aún pero el 24 me estoy yendo hasta el 2 de enero. Igualmente podría adelantar días antes de la fecha si es necesario.

**Comment by LeandroBraier** [comment]
Dale, seguramente, porque estamos justo en un momento de mucho laburo,
gracias por avisar. Lo charlamos en la reunión el miércoles entonces.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-03 11:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Perdón, hagamos la reunión el martes a las 10 am mejor. Eze no puede el miércoles a esa hora. Me confirmás?

abrazo

**Comment by LeandroBraier** [comment]
Fede, urgente necesito que me confirmes esto. 

Estoy probando las URL que aparecen tachadas en el ticket (entiendo que son las que ya hiciste) y todas me dan error. Por favor hacelas funcionar y que sean ESAS url, no otras. Si alguna la cambiaste acomodala a la URL que aparece en este ticket, porque ya tengo todos los mails armados con esas URLs.

Porfa confirmame urgente esto.

abrazo

**Comment by FAAREIA** [comment]
Lo de la reunion martes, si, todo OK. Me olvidé de responder.

Justo estoy con marce haciendo algo de los templates.
Estaban en el servidor de duplika, pero ahora hay que actualizarlas.
Las tachadas son las hechas por ahora, pero necesito terminar esto con marce para poder pasarlas al server actual

**Comment by LeandroBraier** [comment]
Entiendo. Ok, creés que lo tendrás para antes de las 13? Así coordino con la persona que envia los mails. Desde ayer no estamos enviando cadenas de mails por este tema.

**Comment by FAAREIA** [comment]
Le pregunto a marce.

**Comment by LeandroBraier** [comment]
Dale, gracias.

**Comment by FAAREIA** [comment]
Hola Lea, se me cayó internet, pero he aquí nuevamente. Marce me dijo que estaba en reuniones o en un reunion y no sabía cuando salia.
Lo que sí, ya le pasé la lista para que pruebe lo nuevo que se hizo.

Lo nuevo consiste en que, los colores los van a poder meter en el CMS. Ésto implica que para cargar una marca van a tener que primero cargar en el CMS y luego ubicar el logo donde corresponda, y nada más que eso. ;)

Con respecto a los nombres de las marcas de la sexta tanda, estos fuerons los que corregí:
Ojo que no los cambié por que quise sino que estaban mal. Lo ideal sería que los modifiques en tu lista, si no es mucho lio, sino los cambio yo

adriana-costantini
le-coq-sportif
angelane
lef
andromaco
laboratorios-victoria
laboratorios-warmic

**Comment by LeandroBraier** [comment]
Si, esos obvio. No hay problema. De hecho ya los había corregido en el mail
y en el doc mio también. Gracias por eso. Porfa avisame cuando estén
migrados entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-05 13:13 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi marce esta cargando la lista nueva que pasé:
Fijate que de este lista la mayoria estan tachados, pero entre los tachados, estas 2 páginas estan caidas:
Sweet victorian http://www.sweetvictorian.com/
Laca www.lacacosmetica.com

**Comment by LeandroBraier** [comment]
Gracias por avisar. Igual debe ser provisorio eso. Son marcas grandes. 

Cuando estén subidas las landings por favor pasame la lista de las que estén disponibles.

abrazo

**Comment by FAAREIA** [comment]
Aca va una tanda, aún faltan

http://benteveo.tv/body-sculpt/
http://benteveo.tv/cara-cruz/
http://benteveo.tv/chiarini/
http://benteveo.tv/admit-one/
http://benteveo.tv/taverniti/
http://benteveo.tv/adriana-costantini/
http://benteveo.tv/grimoldi/
http://benteveo.tv/sarkany/
http://benteveo.tv/selu/
http://benteveo.tv/swatch/
http://benteveo.tv/via-uno/
http://benteveo.tv/class-life/
http://benteveo.tv/kevingston/
http://benteveo.tv/hannah-collins/
http://benteveo.tv/pantene/
http://benteveo.tv/silkey/
http://benteveo.tv/le-coq-sportif/
http://benteveo.tv/angelane/
http://benteveo.tv/innocenza/
http://benteveo.tv/peter-pan/
http://benteveo.tv/piero/
http://benteveo.tv/pigmento/
http://benteveo.tv/algabo/
http://benteveo.tv/tsu/
http://benteveo.tv/coty/
http://benteveo.tv/lef/
http://benteveo.tv/millanel/

**Comment by FAAREIA** [comment]
Chequealas por las dudas lea!

**Comment by LeandroBraier** [comment]
Gracias Fede y Marce!

Revisadas y perfectas todas. Si el resto están para el martes estamos más
que ok.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, qué nos frena en esto? Necesitaría tener URGENTE las landings que faltan. Decime y te ayudo a gestionarlo pero para hoy a la noche tendrían que estar.

**Comment by LeandroBraier** [comment]
Fede, ¿qué pasa con esta tanda? Contestame algo al menos.

Estamos frenados por esto y nos quedan solo 6 días para mandar mails porque
después vienen las fiestas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-05 18:56 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Hola Lea, como te dije ayer nunca me llegaron estos mensajes.
Ahi estoy cargando las marcas, solo faltarían dos marcas en las que necesito que marce actualice algo del CMS
En un toque te paso la lista

**Comment by FAAREIA** [comment]
http://benteveo.tv/selu/
http://benteveo.tv/class-life/
http://benteveo.tv/sweet-victorian/
http://benteveo.tv/laca/
http://benteveo.tv/deisel/
http://benteveo.tv/dcc-sa/
http://benteveo.tv/iquisa/
http://benteveo.tv/andromaco/
http://benteveo.tv/laboratorios-victoria/
http://benteveo.tv/laboratorios-warmic/
http://benteveo.tv/nerova/
http://benteveo.tv/plumari/
http://benteveo.tv/iyosei/
http://benteveo.tv/amyris/
http://benteveo.tv/buplasa/
http://benteveo.tv/chemoil/
http://benteveo.tv/domitec/
http://benteveo.tv/eco-oil/
http://benteveo.tv/fritzsche/
http://benteveo.tv/glas-car/
http://benteveo.tv/quimtia/
http://benteveo.tv/cantua/
http://benteveo.tv/escos/
http://benteveo.tv/mi-flora/

**Comment by FAAREIA** [comment]
Ahi estan todas listas Lea.
Sigo con lo de Siguit.

**Comment by LeandroBraier** [comment]
Gracias Fede, ahora las reviso.

Por las dudas chequeá todos tus pendientes en estos 3 proyectos, así ves
todo lo que te pasé y no te llegó y me podés dar feedback de algo si no se
puede hacer o lo que sea.

https://github.com/LeandroBraier/SiguitFM/issues?q=assignee%3AFAAREIA+is%3Aopen

https://github.com/LeandroBraier/WebPuroRio/issues?q=assignee%3AFAAREIA+is%3Aopen

https://github.com/LeandroBraier/BenteveoTV/issues?q=assignee%3AFAAREIA+is%3Aopen

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, el logo de Benteveo te sale cortado en todas las nuevas. Revisalo por favor. Se tiene que ver bien en todas las resoluciones. Dale prioridad a esto y después Siguit. abrazo

**Comment by FAAREIA** [comment]
Hola Lea, me podes mandar screenshot?
No lo veo cortado en ningun navegador aca

**Comment by LeandroBraier** [comment]
Aqui va Fede.

![captura de pantalla 2014-12-12 a la s 10 30 45](https://cloud.githubusercontent.com/assets/6719872/5417897/a7efd31a-821c-11e4-91b8-b509cd5a9a4d.png)

**Comment by LeandroBraier** [comment]
Le falta la base del logo y el slogan de abajo.

**Comment by FAAREIA** [comment]
Hola Lea, ahi lo corregí!
Lo del slogan, la verdad que ya es muy chico a tamaño normal, por lo que en ese logo que ya esta chico, el navegador no llega a renderizar ni siquiera una línea de 1px. Esta en vector el logo.

Reconfirmo que no me llegan los mails de git a gmail, no se que onda

**Comment by LeandroBraier** [comment]
Fede, seamos prolijos. Si el slogan se ve chico o no se ve de última lo sacamos, pero no lo dejemos cortado o así:

![captura de pantalla 2014-12-12 a la s 19 02 50](https://cloud.githubusercontent.com/assets/6719872/5420159/29d0858c-8231-11e4-99d5-51b106c410a5.png)

Tema GitHub: De qué nos sirve entonces? Si no te funciona create una cuenta en Wunderlist y te paso las tareas por ahi. FIjate qué preferís, pero yo uso GitHub porque me lo pediste vos.

**Comment by FAAREIA** [comment]
Ahi me volví a suscribir, capas que gmail me esta rebotando los mails. Yo prefiero Git, esta bueno para seguir un issue.

Con respecto al logo, veo que ahora se te ve gigante, voy a investigar que es lo que pasa. Me parece raro que antes se te veia chico y ahora gigante, no le cambie nada de tamaño.

**Comment by FAAREIA** [comment]
Ahi esta corregido, selu y andromaco estaban apuntando a la base de las landing anteriores y no al sistema nuevo =/

**Comment by LeandroBraier** [comment]
Ah perfecto ahora. Gracias Fede!

Abrazo
