### ISSUE TITLE
Urgente: Landing tipo Casting Storydoing para Convocatoria nueva

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#27]
Fede, te estoy subiendo en un toque a Benteveo Maquetador/ Convocatoria Hotel un illustrator con la estética de una convocatoria que estamos haciendo para una sesión de fotos en Río Ancho.

Necesito que con esa estética armes una landing como la que hicimos para el casting de Storydoing TV, con los mismos entry de datos.

Bien bien simple, tenés la tipografía, los colores y los recuadros de las fotos para que uses a discreción, no más que eso.

El texto total sería:

"CASTING
En los próximos días estaremos produciendo fotos para un exclusivo hotel y restaurant gourmet. 

Si tenés entre 50 y 60 años, seas hombre o mujer, dejanos tus datos en esta aplicación web y nos contactaremos con vos"

Quiero que sea más simple, sin más explicación, pero si te parece poco le agregamos texto sobre la primera versión de la landing.

La necesito urgente, para mañana a la tarde, llegás?

**Comment by LeandroBraier** [comment]
Es pesado el illustrator. Está en PDF. Te paso el link de dropbox para descarga:

https://www.dropbox.com/s/9w6dz381x3wjmc9/casting_final.pdf?dl=0

Las fuentes están en BENTEVEO MAQUETADOR/ Convocatoria Hotel

**Comment by FAAREIA** [comment]
http://chat.benteveo.tv/ld/convocatoria-hotel/
El illustrator no lo encontré, pero usé el PDF

**Comment by LeandroBraier** [comment]
Perfecto. El PDF es editable en illustrator pero la veo OK de resolución a
la landing.
1. Funcionalmente está bien? A qué mail direcciona los datos? A
   info@benteveo.tv?
2. Quitale el logo de Río Ancho al pie
3. Cambiale el título y la url a "Convocatoria Exclusivo Hotel"

Con eso ya estamos OK para mostrarle a Eze.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Los links a Facebook y Twitter de Río Ancho también sacalos, junto con el
logo de Rio Ancho al pie.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-19 11:17 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
http://chat.benteveo.tv/ld/convocatoria-exclusivo-hotel/

El mail va a: mail.benteveo.tv
Lo manda: info@benteveo.tv

**Comment by LeandroBraier** [comment]
Gracias Fede!

Qué significa mail.benteveo.tv? Donde quedan guardados los archivos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si me confundí, en realidad va de info@ a info@

**Comment by LeandroBraier** [comment]
Perfecto. Ahora si, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Subilo ONLINE, está OK. Cuando intenté mandar mi cv y demás me tiró el error que adjunto. Además, necesito que la URL sea la siguiente:

http://benteveo.tv/casting-exclusivo-hotel/ 

![captura de pantalla 2014-11-19 a la s 12 39 18](https://cloud.githubusercontent.com/assets/6719872/5108471/58ba1372-6fe9-11e4-832c-219a66da8663.png)

**Comment by FAAREIA** [comment]
http://benteveo.tv/casting-exclusivo-hotel/
Fijate ahora, si sigue mal habría que hablarlo con marce. Aunque creo que tiene que ir bien ahora.

**Comment by mkreyness** [comment]
```
creaste la carpeta "archivos-subidos" ?

El 19/11/2014 a las 14:08, Federico
  Arena escribió:


  http://benteveo.tv/casting-exclusivo-hotel/
    Fijate ahora, si sigue mal habría que hablarlo con marce. Aunque
    creo que tiene que ir bien ahora.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ahi ya la cree, pensé que estaba en el root

**Comment by LeandroBraier** [comment]
AHora no me tira error al menos. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, me dice Eze que el mail le llegó, pero al hacer clic en los links para descargar los archivos adjuntos le tira error. Revisás eso porfa?

**Comment by FAAREIA** [comment]
Si, ahi hice un cambio. Ya debería estar bien

**Comment by LeandroBraier** [comment]
URGENTE

Fede, me dice Ezequiel que el mail del casting le llega con el nombre "Casting Storydoing". Cambiá eso, pero lo urgente es que tengo miedo que a la gente se le dispare automático el newsletter del casting de storydoing de "recibimos tus materiales". Por favor urgente revisá eso y después armamos el newsletter específico de este casting.

**Comment by FAAREIA** [comment]
Si, ahi lo modifiqué.
Marce cuando puedas revisa el .php que esta online en la carpeta "casting-exclusivo-hotel" a ver si me saltié algo. Comenté las líneas mandaban el newsletter, igual fijate.

**Comment by FAAREIA** [comment]
Para resumir Lea, el mail lo manda: "info@benteveo.tv"
Con asunto: "Convocatoria Exclusivo Hotel"

**Comment by LeandroBraier** [comment]
Yo me quedo tranquilo porque a mi no me llegó nada en la prueba que hice. Ahora va a haber que armar este newsletter automático. Te lo pido en tarea aparte y asigno a Marce la tarea así entra en la conversación.
