### ISSUE TITLE
Formulario Siguit

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#29]
Fede, necesito para hoy, aunque sea a última hora, que me armes un formulario nuevo para una marca nueva.

Es así. Tenemos un proyecto llamado Siguit, que es un hardware por el cual los clientes de un local tocan botones para dar un feedback sobre el servicio.

Mañana tenemos reunión con la empresa ISS World y nos van a pedir un Demo. Para eso, necesitamos un formulario que se vea bien pro, minimalista y pro, en el cual ingresar los datos necesarios para luego armar esa demo. Bastaría que esos datos lleguen por mail a info@benteveo.tv y listo.

La estética te la estoy mandando via WeTransfer. Tenés Logos, MockUps del hardware, pero en general hacete algo bien bien minimalista y sencillo, con botones que se vean bien pro, tipo apple, con los siguientes entrys de datos:

URL
benteveo.tv/Demo_Siguit

(TITULO) DATOS ANALISIS Y DESARROLLO DE DEMO SIGUIT:

NOMBRE EMPRESA:

CATEGORIA: PRODUCTO o SERVICIO

Datos de contacto 
NOMBRE / CARGO / email / Tel / Tel directo / DIRECCION

Conectividad: Wi Fi abierto / WI Fi protegido / 3G / Ethernet

Datos del access point:

Modelo Siguit:     SPOT / SPOT DUAL / SIGUIT SWTCH

Uso: Stand alone / Operador

Ubicación: Exterior / Interior
            Fija / Movil

Solo para modelo SIGUIT SWITCH:  Formulacion de la consulta 1: _______________________________

Solo para modelo SIGUIT SWITCH DISPLAY:   Formulacion de la consulta 1: _______________________________
                                        Formulacion de la consulta 2: _______________________________
                                        Formulacion de la consulta 3: _______________________________

Solo para modelos SPOT/ SPOT DUAL: Desarrollo Script demo:  

DISPLAY MENSAJE DE BIENVENIDA: Texto 1: ___________________________________
Ejemplo: "Día a día intentamos mejorar nuestro servicio…Tu opinión nos parece muy importante”

FORMULACION DE CONSULTAS: 
Formulacion de la consulta 1: _______________________________
Formulacion de la consulta 2: _______________________________
Formulacion de la consulta 3: _______________________________
Formulacion de la consulta 4: _______________________________
Formulacion de la consulta 5: _______________________________

Condiciones de alarmas:

Integracion alarmas movil: POR MAIL / POR SMS / AMBAS

Requerimientos técnicos especiales:

Observaciones generales:

Confirmame si recibiste el WETRansfer porfa y confirmame también si llegás a armarlo para hoy a última hora, antes de hacer el traspaso de servidor de mails. abrazo

**Comment by FAAREIA** [comment]
Hola Lea, estos meses estoy bastante complicado con los tiempos. También se hace dificil hacer el diseño, maquetación y programación del formulario (algunas opciones muestran otras) para entregarlo hoy. ¿Mañana a que hora tienen la reunion?

**Comment by LeandroBraier** [comment]
A las 11 de la mañana es la reunión. Es prioridad a full, lo demás se puede frenar hasta la semana que viene. Seguro no llegas?

No diseñes mucho. Ponele el logo, campos para completar y listo. No le des mucho vuelta más. Si se ve bien en un ipad 10 perfecto.

**Comment by FAAREIA** [comment]
Voy a tratar de llegar, pero estoy con mil cosas. Esas cosas me las tienen que decir antes de hacer las 4hs diarias.
Por otra parte, que modelo es el ipad 10? Link oficial para ver las especificaciones?

**Comment by LeandroBraier** [comment]
Gracias Fede. La próxima vez te aviso con más tiempo, te pido disculpas.

Respecto del iPad es el iPad 2. Estoy justo en una reunión con un cliente, por eso no te llego a pasar el link. Apenas puedo te paso pero fijate si con este dato te podes arreglar.

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/Demo_Siguit/index.html

Fijate si esta OK, la última parte del form, esta medio confusa en tu post inicial.

Abrazoo

**Comment by LeandroBraier** [comment]
Quedó excelente Fede!!!

Muchísimas gracias!!

Ya probé enviar el primer form.

Gracias por el esfuerzo extra, en serio.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
;)
Gracias Lea, fijense de probarlo en la tablet real asi no hay sorpresas y ven como queda. Igualmente no tiene nada raro.

**Comment by mkreyness** [comment]
```
Y con los datos que se cargan que hace ?

El 21/11/2014 a las 8:31, Federico
  Arena escribió:


  ;)
    Gracias Lea, fijense de probarlo en la tablet real asi no hay
    sorpresas y ven como queda. Igualmente no tiene nada raro.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Se mandan por mail nomás, eso por ahora. Después no sé como va a escalar esto.

**Comment by LeandroBraier** [comment]
No se hagan mucho problema por eso. Por ahora es solo para la reunión que
tiene Eze en un par de horas con una empresa, no hace falta que quede
sistemática de ahora en más. Si nos va bien en la reunión ahí vemos. No hay
problema.

Por ahora es solo cosmética para la reunión.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
