### ISSUE TITLE
Newsletter Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#30]
Fede, te estoy pasando en breve la estructura para maquetar un newsletter que haríamos desde Benteveo para enviarle a la base de marcas que estamos logrando con la campaña de Cadena de Mails (para la cual has hecho y hacés tantas landings)

La fecha de primera entrega sería recién el martes 25 a la tarde, no es urgente, pero te aviso para que te puedas organizar el tema horarios.

Te lo voy a pasar cuando esté resuelto el newsletter de Rio Ancho, así no te encimo todo.

abrazo

**Comment by FAAREIA** [comment]
Dale buenisimo, gracias

**Comment by LeandroBraier** [comment]
Fede, te paso la descripción de lo que necesitaríamos para el newsletter de Benteveo. Es literalmente un correo de noticias, pero noticias particulares de Benteveo. Se lo vamos a enviar a la base de prospectos que construimos con la campaña de Cadena de Mails.

DISEÑO

Te pasé un newsletter de referencia.

CONTENIDO

En el contenido tiene que haber info que le resulte atractivo al receptor y, a la vez, nosotros nos seguimos vendiendo como agencia. Por esto, el newsletter va a tener 4 cajas:

. 1 caso de Benteveo explicado: va un jpg y una breve descripción de un caso de Benteveo. El link lleva al video del caso dentro de la Web o Vimeo, como sea más sencillo. Esta caja va por igual a todos los mails.

. 1 peli recomendada producida por Benteveo. Imagen afiche de la peli, pequeña descripción debajo y link a la peli en IMDB. Esta caja va igual para todos los mails

. 1 nueva tecnología de lo que se viene. En estructura es como el caso de Benteveo pero sobre tecnología. Va por igual a todos los mails.

. 1 caso curado por Benteveo de la industria específica del cliente: Por ejemplo, si es Alimentos, un Caso de Knorr con un pequeño párrafo de nuestra opinión sobre el caso. Esta caja va customizada según rubros. Serán 10 rubros en total.

. 1 marca que promete innovación en Argentina. Imagen relativa a la marca, breve explicación de por qué queremos trabajar con la marca (casualmente la marca que lo recibe, obvio). Esta caja sí es customizada y diferente para CADA MAIL.

Necesitaría que armes un diseño maquetado con textos de relleno nomás para que podamos ir avanzando con Marce K en la parte de programación que no debe ser sencilla.

abrazo

**Comment by LeandroBraier** [comment]
Fede, este tema me lo quedo yo por ahora. Estoy investigando una manera de no tener que maquetarlo. Te aviso. abrazo

**Comment by FAAREIA** [comment]
Creo que lo que buscabas es esto:
http://benteveo.tv/mailing/benteveo-tv/benteveo-tv.html

Lo tenía hecho hace rato, me parecia raro que nunca me hayas respondido el email en su momento. Fijate si sirve.

**Comment by LeandroBraier** [comment]
Está muy bueno, Fede. Lo hablo con Eze la semana que viene y vemos cómo podríamos hacer para cargar los contenidos una vez que el template esté aprobado. Sería ideal cargarlo via CMS como las landings y mails de cadena de mails.

abrazo y feliz año!

**Comment by LeandroBraier** [comment]
Fede, lo vimos con Eze. Necesitamos que les una estética más actual, más moderna. 

Ejemplos:

http://appnew.embluejet.com/Online/VersionOnline.aspx?eQ2ek64aeVrcMOxPyq-R-30263-R-0-R-utm_source~emBlue+-+Newsletter+emBlue%7Cutm_medium~email%7Cutm_term~%7Cutm_content~%7Cutm_campaign~Newsletter+emBlue+-+Newsletter+Enero+2015

http://view.email.vimeo.com/?j=fec91770726c0479&m=fe8812717363017573&ls=fe1b1675726c017e721279&l=ff011570716001&s=fe521372746d01747211&jb=fef815707c6c01&ju=fe811c797c63067477&r=0

No hay apuro con esto, puede ser para la semana que viene.

abrazo

**Comment by FAAREIA** [comment]
Ahi va un preview sin terminar, faltaría el pié que cerraria el diseño

![nwlt](https://cloud.githubusercontent.com/assets/6184969/5858586/18036ea6-a233-11e4-8fa8-9446549a8e78.png)

**Comment by FAAREIA** [comment]
Si hay alguna data extra que quieran poner, avisenme.

**Comment by LeandroBraier** [comment]
Más allá de la data lo sigo viendo como antiguo. Comparado con el de
Embleu. FIjate si sacando el serruchito y poniendo todo centrado no queda
mejor. Eso me parece que llama la atención del de Embleu.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ok, vamos a ver que vuelta le damos. Pruebo como quedaría algo similar al embleu

**Comment by FAAREIA** [comment]
Hola Lea, ahi te adjunto otra muestra. Ésto si es mucho más visual, pero hay que tener en cuenta que TODO va a ser imágen, no es posible pasarlo a HTML para newsletter.
![nwlt-2a](https://cloud.githubusercontent.com/assets/6184969/5903749/421533fa-a562-11e4-9c2d-3bd6f922b466.png)

**Comment by LeandroBraier** [comment]
Estéticamente está buenísma, pero si es todo una sola imagen no nos sirve.
Por qué no lo podés hacer como Embleu, que es HTML?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-26 13:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
OK entiendo, ahi probé como quedarían las imagenes en el de Emblue y va bien. Lo arranco a hacerlo asi de una?

**Comment by LeandroBraier** [comment]
Si. La estética está excelente. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, ahi va el news:
http://www.benteveo.tv/mailing/benteveo-tv/benteveo-tv.html

**Comment by LeandroBraier** [comment]
Me gustó, che. Dejame que lo chequee con Eze.

De hecho creo que podríamos utilizar esta onda para algunos cambios en la
home que se vienen este mes. Te confirmo. abrazo!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Pero andá avanzando en ponerle a esto los contenidos de Benteveo que tenías.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-28 14:56 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Hola Lea, guarda que para mi, este tipo de estructuras funciona bien en cajas de poco ancho, hay que ver como quedaría en un sitio web que tiene al menos 300px más de ancho.

Avanzo maquetandolo o le pongo en photoshop una receta y pelicula?

**Comment by LeandroBraier** [comment]
Cargale los contenidos que tenías en las versiones anteriores de peli, etc
a esta misma versión maquetada. Así se la muestro a Eze.

No entiendo lo de la página web porque supuestamente esto es un mail. De
última si hace clic y la veo en versión web no importa que sobre espacio a
los costados, no?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-29 10:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ah, creo que te había entendido mal. Olvidate. La version web de este newsletter va a ser igual.

**Comment by FAAREIA** [comment]
Ahi lo actualicé!
Abrazo
