### ISSUE TITLE
Consulta por customización de landings

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#31]
Fede, necesito saber si se puede pasar un instructivo a alguien para que vos no tengas que hacer la customización de los botones de las landings. Es un HTML?

Si es solo Copy and Paste podríamos resolverlo nosotros así te liberamos para cosas mejores. En un ratito te estoy pasando los dos primeros screens de la página web estilo aplicación que te había comentado.

Preparate.

abrazo

**Comment by FAAREIA** [comment]
Se podría hacer un instructivo, pero el que lo haga sería necesario que sepa minimamente algo de CSS y HTML.
Ahora que se me ocurre, hasta podría grabar un video de ejemplo de como hago una y listo.

**Comment by LeandroBraier** [comment]
Dale, grabate uno y mandamelo. Así vemos si lo podemos hacer nosotros. Sino
te lo seguiremos pidiendo, si no nos queda otra.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-28 14:22 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día Fede! Como te decía el viernes, subime el video a youtube o mandamelo en mp4 porque no lo pude abrir en el formato que me lo pasaste.

abrazo

**Comment by FAAREIA** [comment]
Ok, hoy voy a tratar de hacerlo. El video pesa como 1GB, es formato avi, muy raro que no lo puedas abrir.

**Comment by LeandroBraier** [comment]
Me llegó comprimido en tz, que es un formato que no puedo abrir. Si vos
podés mandarmelo comprimido en zip mejor, sino en mp4 como las compresiones
que hicimos para los videos de las landings de marcas y me lo mandás por we
transfer.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-01 9:27 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://benteveo.tv/tutorial.zip
Ahi va en zip ^^

**Comment by LeandroBraier** [comment]
Ahora sí lo vi, Fede. Solo necesitaba la parte de los botones y la URL, no la parte de logos y demás, pero igualmente me alcanzó para ver que es complejo y sensible, te lo vamos a tener que seguir pidiendo a vos por ahora. Gracias igualmente

abrazo
