### ISSUE TITLE
Robot Google hace de las suyas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#32]
Fede, puede ser que hoy me haya llegado una visita del robot de google a un botón genérico?

Me llegó un mail de info@benteveo.tv que solo dice "Contacto" No dice ninguna marca y la visita en analytics dice que fue en esta url:

/?contacto=

Revisé en analytics y la única landing que se visitó durante suficiente tiempo como para clickear en un botón es la de Estancias Chiripa, pero esa aparentemente tiene las urls bien.

http://benteveo.tv/estancias-chiripa/

Consulté a Marce por los mails de remarketing que él envía y me dijo que los botones de los que envió estaban ok.

Qué puede estar ocurriendo?

**Comment by FAAREIA** [comment]
Mirá, esa es una de las nuevas landing y tiene la indicación de que el robot no la indexe ni la revise, y también tiene la indicación de que no siga los links.
El robot, cualquier que sea, google, yahoo, yandex, etc, puede ignorar esa indicación y hacer lo que quiera. pero Igual me parece raro ya que nadie conoce el link...

**Comment by LeandroBraier** [comment]
Ok, entiendo. Pero qué otra opción puede haber? Porque si fuera el robot de google no debería aparecer la visita que te mencioné dentro de Analytics, no?

**Comment by FAAREIA** [comment]
Creo que Google Analytics no registra a su robot, no tendría sentido porque no es una estadística real. Sería hasta erroneo hacerlo.
Capas que hay algun bug por ahi dando vueltas o anda a saber que, habría que sentarse e investigarlo con todas las herramientas a mano. Como analytics y mails. Habría que ver el código del mail también, no sé, me imagino que algo asi.

**Comment by mkreyness** [comment]
Cualquiera de nosotros que entre a la pagina para probar chat o lo que 
sea si hace un submit el efecto seria ese mismo, porque entró sin 
ninguna marca.
Lo que se puede hacer es que el mail NO se envie si no hay parametro de 
marca.

**Comment by LeandroBraier** [comment]
Claro, ese es el misterio. Quién de nosotros entró?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-02 13:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Capas que es algún flaco del servicio que contrataron que entra, ve y sin querer apreta el botón

**Comment by mkreyness** [comment]
Yo use el chat2 de rioancho, el sitio de benteveo en sí no creo haber 
entrado para nada.

**Comment by LeandroBraier** [comment]
Qué servicio, Fede?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-02 13:41 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Me refiero al servicio de marketing que contrataron, o capas que me estoy confundiendo....=/
