### ISSUE TITLE
Consulta técnica HTML Grupo Gaona

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#33]
Fede, consulta técnica rápida. Estamos presupuestando algo para Grupo Gaona. Necesito saber si es posible que nosotros, accediendo al código html de su página, podamos cambiar los banners que aparecen en la Home (a modo de sliders) 

http://catalogo.grupogaona.com.ar/

y en la sección Categorías, como por ejemplo este que dice 12 cuotas sin interés:

http://catalogo.grupogaona.com.ar/cuidado-personal/

Solamente necesito que te fijes en el código fuente y me digas si lo podríamos hacer o haría falta algún tipo de desarrollo o programa especial para hacerlo. En caso de que podamos, decime si llega a tener alguna dificultad o es sencillo.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo vi. Esos sitios tan grandes habitualmente tienen un CMS por detras, por lo que el slide debe cambiarse desde ahi.
Si es HTML, sería más simple, sin vueltas.
Cualquiera de las 2 se puede hacer, excepto que sea un CMS y no tengan los accesos.
También, cuando se haga el cambio, van a tener que actualizar el cache del CDN. Eso lo hace el servidor habitualmente.

**Comment by LeandroBraier** [comment]
Gracias Fede! Entiendo. El sitio tiene CMS pero para algunas cosas entiendo. Hay otras que están hechas con Tienda Nube por ejemplo. Chequeaste el código fuente?

PD: Qué pasó con la sexta tanda de landings? Nunca me llegó para el mediodía.

**Comment by FAAREIA** [comment]
Debe ser un solo CMS, nunca vi un sitio que funcione una parte con un
sistema y otra parte con otro. No sería nada bueno eso.
El código fuente lo chequié, pero eso lo genera el CMS. Osea, la imagen que
aparece en el código, viene de la imagen que se carga en el CMS.
Con la sexta tanda, ahora estoy en eso, esperemos llegar a 20+ hoy.

**Comment by LeandroBraier** [comment]
Genial ambas. Gracias!
