### ISSUE TITLE
Nuevo Formato de Cadena de Mails

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#34]
Marce, queremos agregar al mail que enviamos a las marcas (que es una "falsa cadena de mail") una imagen que parezca un video de youtube. En realidad es una imagen clickeable que lleva a la landing de cada marca.

Para esto, nos parece que podrías armar un CMS básico en que se carguen 4 cosas:

1) Nombre y mail del destinatario

2) Texto del mail con el formato que trae de Word (negritas, links, etc)

3) Imagen tipo YouTube

4) Link que lleva a la landing

Nos decís cuántas horas te llevaría y para cuando lo podrías tener?

abrazo

**Comment by mkreyness** [comment]
Son los mails que mando yo ? Digo para saber en que server.
Necesito tambien el template del mail y saber si la imagen la queres 
uploadear via el CMS o seria un link a algo fijo.

Ponele 4 horas con toda la furia, y se puede hacer para mañana.

**Comment by LeandroBraier** [comment]
Buenisimo!

No son esos mails, sino los primeros mails que mandamos a cada marca, la "falsa cadena de mails". El server sería el nuevo de Benteveo, el de Duplika.

El template del mail te lo mando Fede en breve. La imagen es la misma para TODOS los mails, por lo cual quizá ya la podés dejar seteada vos. Sí, sería via un link, via un inline. Fede ya te lo genera en el template. También él genera los espacios de variables.

Apenas tengo el template entonces te lo paso. Gracias!

**Comment by mkreyness** [comment]
Ok, entonces son campos a agregar al mismo CMS de las marcas que ya 
tenemos ahi.

**Comment by LeandroBraier** [comment]
Exacto. Marce, Fede ya está empezando hoy a armar el template de Cadena de Mails. Encontramos una herramienta que te puede servir para la parte del texto de mail:

http://ckeditor.com/download

Fijate qué te parece.

abrazo

**Comment by mkreyness** [comment]
En la medida en que se puedan dejar espacios reemplazables por lo que 
tengo que meter, todo bien.
Acordate que el HTML tiene que ser lo mas autosuficiente posible (no 
estar levantando datos de un servidor cuando la persona lo mire), ya que 
es un mail.
