### ISSUE TITLE
Template Nuevo Cadena de Mails

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#35]
Te subí el doc a carpeta BENTEVEO MAQUETADOR/Mail Landings

Cuando lo tengas pasaselo a MArce con copia a mi.

**Comment by LeandroBraier** [comment]
Fede, estoy viendo que el template que te pasé, en realidad no tenía todavía impactado el cambio de la imagen. Te lo volví a subir ahora bien. Avisame cualquier cosa.

abrazo

**Comment by FAAREIA** [comment]
El Lúnes con toda la mudanza lo hago. Metemos todo de un saque, total no puede usarse hasta la mudanza

**Comment by LeandroBraier** [comment]
Entiendo. Genial.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
