### ISSUE TITLE
200 landings nuevas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#37]
Marce, va el doc con los datos que me pediste. Decime si está ok y te sirve para arrancar a armarlas,

abrazo

https://docs.google.com/spreadsheets/d/1YIpyOvc6WSEnhukFnvxpmhqrJKVolEUtWn-TL7Z3A5c/edit#gid=0

**Comment by mkreyness** [comment]
Ese "link landing" es algo provisorio ?
Porque veo que no siempre coincide con lo que dice en <titulo-safe>, y 
si el <titulo-safe> no es para eso, no entiendo para que es.

O sea, cuando yo cargue esta base, automaticamente se van a generar 
todas las paginas

chat.benteveo.tv/<titulo-safe>

que el dia que se haga la mudanza, va a ser

www.benteveo.tv/<titulo-safe>

**Comment by mkreyness** [comment]
Lean ?
Estoy frenado con esto esperando entender que hacer con el campo 
"landing", lo pongo igual como una cosa provisoria para apuntar a las 
landing viejas ?.
Y me perdi con lo del nuevo texto del mailing, ya esta listo ? Tengo que 
agregar mas campos en el CMS para cosas que van ahi ?

**Comment by LeandroBraier** [comment]
Marce, por ahora necesitamos las landings solamente. Para eso te alcanza
con Titulo y Titulo Safe.

Respecto del mail, todavía Fede está armando el template para que vos lo
puedas incorporar, no está listo todavía. Avancemos con las landings. Ya te
borré la columna de Link Landing para no confundir.

Avisame si así podés avanzar.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-12 14:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero acordate que yo ya estoy cargando de aca el email y el nombre del 
contacto tambien.
O sea, todo esta quedando incorporado en una UNICA base de datos de 
marcas, evitemos tener varias versiones circulando de cada cosa.
Si yo cargo las 200 que ya me pasaste, instantaneamente se van a crear 
las NUEVAS landings con <titulo-safe>, pero siempre como chat.benteveo.tv.

Dame el OK final a esto y las cargo.

**Comment by mkreyness** [comment]
Listo ya cargue estas 200, creo que quedaron bien todas las cosas 
acentuadas.
Tendrias que poner a algun junior a probar una por una a ver si 
funcionan y/o se escapo alguna letra rara.
Yo veo muchos titulos en minuscula y sin acentos, me parece que esos va 
a haber que corregirlos (por ej, "jugos asuncion".

**Comment by LeandroBraier** [comment]
Te referís a los títulos de las páginas?

Cómo los corrijo ahora? Si los corrijo en el excel vos los corregís o los
corregimos directamente en el CMS?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-12 17:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si no fuera por lo de los acentos que hay que encodearlos, te diria lo 
hagan directo en el CMS.
Pasame en un excel nuevo SOLAMENTE los cambiados (titulo y titulo safe, 
que es lo que uso para identificarlos), asi le encodeo los acentos y los 
paso yo.

**Comment by LeandroBraier** [comment]
Marce, ya creé una solapa aparte llamada "A CORREGIR". Ahí tenés los Títulos y Títulos Safe de los que que corregí los Títulos.

Además, hay 2 que tenían mal también el Título Safe. Fijate que son dos: Ando Volando y Total Bags.

https://docs.google.com/spreadsheets/d/1YIpyOvc6WSEnhukFnvxpmhqrJKVolEUtWn-TL7Z3A5c/edit#gid=1712630746

Avisame porfa cuando estén corregidas.

abrazo

**Comment by mkreyness** [comment]
Esas que decis que tenian el titulo safe mal, como se llamaban antes ? 
Yo no las encuentro.

**Comment by LeandroBraier** [comment]
Antes se llamaban asi (aunque usted no lo crea)

anovolando

total-bgs

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-15 16:05 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero en el CMS no las tengo.
De hecho hay muchas de las que estan en la solapa de "total corregidos" 
que no tengo.
Voy a repasar todo.

**Comment by mkreyness** [comment]
Se habia cortado el SQL por el apostrofo de un tal D'Elia.
Ahi cargue todo lo que faltaba.
Hay un error mas: tenes dos cosas con titulo safe "della-casa". Uno es 
Della Casa, pero el otro es Dell.
Le pongo safe: dell al que es titulo: Dell ?

**Comment by LeandroBraier** [comment]
exacto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-15 17:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día Marce! Hoy podremos tener por lo menos las primeras quince landings subidas con el dominio correcto?

Me refiero a http://benteveo.tv. Lo ideal sería tener todas, pero no sé cómo viene la cosa y ya hoy necesitaríamos estar enviándolas.

**Comment by FAAREIA** [comment]
Alguien sabe algo de Marce S? Si delega apenas se levanta joya.

**Comment by LeandroBraier** [comment]
Ayer a la noche me escribió pero le dije de mejor hacerlo hoy, porque era
tarde y cualquier cosa que pasaba era un lío. Coordiná con él directamente,
él ya tiene todo listo pero quiere saber cómo vas a hacer el traspaso. Por
fa mandale un mail explicándole así ya coordinas el horario y copiame así
estoy al tanto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-16 9:22 GMT-03:00 Federico Arena notifications@github.com:

> Alguien sabe algo de Marce S? Si delega apenas se levanta joya.
> 
> El 16 de diciembre de 2014, 8:53 a. m., LeandroBraier<

**Comment by mkreyness** [comment]
```
Depende todo de la mudanza del dominio.
Una vez mudada, seria todo automatico, yo no pongo explicitamente
ningun "chat." en ningun lado.

Ojo que yo hasta las 4 no recalo en mi oficina, traten de no
depender mucho de mi hasta esta hora.

El 16/12/2014 a las 9:22, Federico
  Arena escribió:

Alguien sabe algo de Marce S? Si delega apenas se
  levanta joya.


  El 16 de diciembre de 2014, 8:53 a. m., LeandroBraier<

  notifications@github.com> escribió:

  >

  > Buen día Marce! Hoy podremos tener por lo menos las primeras
  quince

  > landings subidas con el dominio correcto?

  >

  > Me refiero a http://benteveo.tv. Lo ideal sería tener todas,
  pero no sé

  > cómo viene la cosa y ya hoy necesitaríamos estar enviándolas.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/37#issuecomment-67148490
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Mmm, metámosle pata a la mudanza del hosting, Fede, por favor. Le enviaste
mail a Marce S? Así coordinamos urgente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-16 9:26 GMT-03:00 mkreyness notifications@github.com:

> Depende todo de la mudanza del dominio.
> Una vez mudada, seria todo automatico, yo no pongo explicitamente
> ningun "chat." en ningun lado.
> 
> Ojo que yo hasta las 4 no recalo en mi oficina, traten de no
> depender mucho de mi hasta esta hora.
> 
> El 16/12/2014 a las 9:22, Federico
> Arena escribió:
> 
> Alguien sabe algo de Marce S? Si delega apenas se
> levanta joya.
> 
> El 16 de diciembre de 2014, 8:53 a. m., LeandroBraier<
>

**Comment by LeandroBraier** [comment]
Ahi le envío

**Comment by LeandroBraier** [comment]
Hecho, gracias!
