### ISSUE TITLE
Modificaciones en Home Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#38]
Fede, tenemos que actualizar el texto de web y agregar la sección INNOVACIÓN. Además del texto que te sumo, debajo de esa sección, a modo de "clientes" aparecerían 5 logos: los de Siguit, Smartshopping y 3 servicios más que ofrecemos, cada uno clickeable para acceder a una pequeña landing propia de la presentación de dicho producto. Te adjunto los logos de cada una, después avanzamos con las landings de cada una.

Ahora si va el texto. Lo que está en azul es lo que modifiqué. 

ENTRETENIMIENTO + COMUNICACIÓN

Somos una empresa dedicada al desarrollo de piezas de comunicación no tradicional. Generamos aplicaciones, experiencias interactivas, contenido para redes sociales, desarrollos web y mobile. Producimos piezas audiovisuales para televisión, cine y Web, pero básicamente nos enfocamos en crear ideas.

Nuestro objetivo va mas allá de comunicar un producto o un servicio. Creamos contenidos originales, para empresas u organizaciones que buscan ser originales. 

Tomamos el carácter de una marca y generamos acciones que la acercan y la conectan con sus clientes. Convertimos estas acciones en experiencias, momentos que merecen ser contados y compartidos; de esta manera logramos nuestro objetivo: el posicionamiento y la recordación. 

No buscamos ideas grandes y costosas, simplemente nos concentramos en hacerlas originales. 
- INNOVACIÓN 

En cada una de nuestras ideas están presentes los desafíos. Nos gusta innovar. Observamos el presente para generar propuestas superadoras, inspiradas con la pasión que nos moviliza a descubrir y a proponer soluciones nuevas. Usamos la tecnología como una herramienta fundamental para llevar adelante nuestras ideas. En este proceso de innovación integramos distintas plataformas  para concretar nuestra visión y la de nuestros clientes. 

Logos de Siguit + Logo de SmartShopping + Logos de los otros 3 servicios (SOCIAL MONITOR + SOCIAL SHOPPING + WEB CHAT)
- SUSTENTABILIDAD

La realidad nos desafía y la pasión nos motiva. Porque amamos lo que hacemos, dejamos huella en lo que producimos. Ya no buscamos solo mostrar el cambio, queremos ser parte de él. Por ello es que Benteveo integra un perfil de sustentabilidad. Nos proponemos dar a conocer nuestro lado más humano, el que más nos acerca como personas, haciendo de puente y participando activamente entre las ganas de ayudar y la necesidad de ser ayudado. 

Trabajamos con empresas y organizaciones del tercer sector, aportando soluciones creativas para comunicar valores y acciones de bien común. Porque creemos que es importante poner en juego nuestra sensibilidad como somos seres humanos, creando puentes y participando activamente entre las ganas de ayudar y la necesidad de ser ayudado. 

Ayudanos a ayudar (botón clickeable)
Entrá a nuestra plataforma de Spreadshout y convertite en un embajador de las causas sociales que impulsamos. 

Este botón clickeable lleva a una landing de Spreadshout de Benteveo con este link: pispeala para enteren bien de qué se trata.

https://www.spreadshout.com/benteveo/

Los logos te mandé también por We Transfer en:

https://www.wetransfer.com/downloads/509b72ec4a2e81bec2020965a929b40220141215202436/756451

**Comment by FAAREIA** [comment]
Hola Lea, fijate si esta todo ok:
http://benteveo.tv/index2.html

**Comment by LeandroBraier** [comment]
Está perfecto, Fede. Subilo a producción nomas y avisame.

Abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi lo subí

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Gracias!
