### ISSUE TITLE
Upgrade WebMail Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#39]
Fede, porfa pedile a Fede G las siguientes dos cosas respecto del webmail:

1) Que la url sea como la gente. No podemos estar usando esta url que encima tira acceso no seguro.

2) Buscar un sistema mejor que Round CUbe que al menos permita estas dos cosas que te menciono.

Puede ser para la semana que viene, no es tan urgente.

**Comment by FAAREIA** [comment]
Como me imaginé, puso esto:

Pueden armar una short-URL con https://bitly.com/. Por otro lado, Chrome tiene una opción para guardar siempre la excepción de seguridad.

RoundCube es el único webmail que tenemos.

Si quieren algo mejor les recomiendo GoogleApps for Domains. Ahí el webmail pasa a ser Gmail (obviamente tienen que migrar todo el email dentro de Google).

---

La short-url es buena, pero ustedes deberían tener un bookmark con la url del webmail

**Comment by LeandroBraier** [comment]
Me parece bien lo que dice. La URL es lo de menos.

Lo que dice de GoogleApps la verdad no lo entiendo, pero si nos va a
permitir manejar el mail desde gmail hagamoslo sin duda. Vos sabés cómo se
hace?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-19 17:24 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
La de GMail es buena, de hecho la hice para un cliente aunque me salió mal.
Para hacer la mudanza desde el servidor a Gmail, el servidor tiene que tener unas configuraciones muy particulares, que Duplika las hizo para mi cliente, pero aún asi no las tomaba.
También hay que tener en cuenta que el costo para hacerlo es de 50 dolares por año por cada cuenta.
=/

**Comment by LeandroBraier** [comment]
Ok, ya está resuelto esto, Fede. Era muy simple, en Settings/ Accounts & Imports de Gmail hay una opción para hacer esto. Los borra del servidor de Benteveo y los traslada a gmail, así que todo en orden.

abrazo
