### ISSUE TITLE
Analyticis Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#4]
Fede, necesito que hagas una cuenta de Gmail nueva para benteveoanalytics con password: xxxxxxxx.

Allí necesito que trackees la home de Benteveo, la landing del video y las 2 páginas de pop ups porfa.

Gracias!

**Comment by FAAREIA** [comment]
mmmmmmm, me pide teléfono, nombre, apellido, fecha de nacimiento, dirección
de correo actual (para cuando se pierda el pass de esta que creamos).
Pasame eso y la creo

2014-08-08 16:14 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Tel: xxxxxxxxxxx

 xxxxxxx

Direccion de correo actual: xxxxxxxxxxxxxxxx

Hay un bug en la página de Benteveo que ya subiste al front end. Los logos
e Facebook y Twitter no se ven. Fijate:

http://www.benteveo.tv/

Te lo paso aparte.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-08 17:22 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día Fede!

Porfa avisame cuando tengas esto listo y usuario y contraseña de la cuenta para ingresar. abrazo

**Comment by LeandroBraier** [comment]
Fede, genial! Cuando puedas subile entonces los referals a todas las páginas de la Web de Benteveo.

De todas formas Patyviena es prioridad. Estará para hoy al mediodía?

**Comment by FAAREIA** [comment]
Si, estoy en eso Lea

**Comment by FAAREIA** [comment]
Lea, acordate que esto ya esta listo y de sacar la clave y el nombre de usuario del primer post.

Abrazo

**Comment by LeandroBraier** [comment]
Si ya lo vi, pero ya pusiste todos los referals?

**Comment by FAAREIA** [comment]
Ahi estoy leyendo porque nunca lo hice, pero según lei hasta ahora, necesitaría saber las URLS desde donde viene el tráfico. Osea, saber todas las urls que le vamos a mandar a los clientes

**Comment by FAAREIA** [comment]
Lea, desde mañana habría que empezar a probar esto. Digo mañana, asi google ya lo empieza a trackear. El informe de los referentes lo hace google automaticamente.
Lo que leí es que a veces cuando son de twitter, pinterest o de esas urls acortadas, uno puede hacer algo para saber la url completa, pero no es nuestro caso.

**Comment by FAAREIA** [comment]
Las landing page van a estar en el server de benteveo, no?

**Comment by LeandroBraier** [comment]
Sip.

Gracias entonces!

Cuando tengamos todas las landings seguimos avanzando entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, tenemos un problema con analytics. Entramos a ver el video a la landing pero analytics registrar 00:00 segundos. Por qué puede ser esto? ¿Puede tener que ver con los últimos cambios que hicimos? Queremos resolver esto antes de seguir enviando. Te adjunto captura.
![captura de pantalla 2014-08-27 a la s 09 56 06](https://cloud.githubusercontent.com/assets/6719872/4059784/0eb25d12-2de9-11e4-91d6-c76c108a6e37.png)

**Comment by FAAREIA** [comment]
Con que url entraron ustedes? No soy experto pero capas que Google
Analytics tarda unos minutos en poner el promedio de tiempo en la página.
Los únicos que veo que no funcionaron fueron lacteos y nevares, diuff si.
Puede ser que el tipo ni bien entra a la url, sale porque no le interesa o
porque clickeo sin querer y cierra al toque. Fijate que los que tienen 0s,
tienen 100% de lo que se llama Rebote. Tocar y salir.

**Comment by FAAREIA** [comment]
pasame el mail y clave de analytics asi lo chequeo tmb

**Comment by LeandroBraier** [comment]
Tenés razón. El tema es que los 2 minutos 10 es promedio, que lo subió Eze
cuando entró a probar ayer. En Lacteos-Veronica, que no entramos nosotros a
probar, sigue diciendo 00:00. YO también pensaba que fue un rebote limpio y
claro, Analytics no se suele equivocar. Pero como Analytics demoró más de 4
horas enimpactar los minutos que vio Eze pensamos que era un error. Por
lástima no.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-27 11:00 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Vos fijate que analytics por defecto te muestra del día anterior y para
atras. Nosotros le ponemos que muestre el "hoy, ahora", pero por algo ellos
lo setean asi y seguramente lo del impacto tardío es común.

**Comment by LeandroBraier** [comment]
Es cierto eso. Raro que haya demorado como 4 hs pero tenés razón, Facebook
tarda también.

La cuenta me da que el gerente de Diuff entró y cerró enseguida, porque en
su sesión, Eze vio el video y lo dejó un rato abierto con los botones
desplegados. Si estuvo 4 minutos en total y el promedio es 2 minutos 10,
entonces el gerente real de Diuff estuvo 0.

Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-27 11:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Mira vos, bastante diferencia de minutos. Más allá del tiempo que diga ahi,
fijate que el de Diuff apretó uno de los botones, por lo que vió el video,
apretó el botón, entro al sitio, vió el mensaje y cerró.
También pensá que a veces puede calcularlo mal o bien, debe haber un rango
de % de imprecisión.

**Comment by LeandroBraier** [comment]
No, el que apretó el botón fue Eze jeje

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-27 12:25 GMT-03:00 Federico Arena notifications@github.com:
