### ISSUE TITLE
Landing Siguit

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#40]
Fede, en carpeta Benteveo Maquetador te dejo esta Landing en PSD para subir a la web de Benteveo. Es la landing que tiene que aparecer cuando se hace click en el logo de Siguit en la Sección Innovación.

Cualquier duda me avisás. Necesitaríamos tener las tres landings subidas para el viernes 9 de enero.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/siguit/

Faltaría que me pases los iconos en vector. Todo lo del photoshop estaba rasterizado

**Comment by LeandroBraier** [comment]
Buenisimo! Lo veo bien como versión mobile. Habría que hacer una versión más ancha para web, no?

No hace falta los íconos en Vector, se ve bien así. Para qué los necesitarías?
![captura de pantalla 2015-01-06 a la s 11 23 09](https://cloud.githubusercontent.com/assets/6719872/5629788/f135e712-9595-11e4-8b6c-20b20e64d3b5.png)

Lo único que veo desalineado es el "Desarrollado y producido por..." FIjate en la imagen que te adjunto.

**Comment by FAAREIA** [comment]
Lo que veo que me enviaste en todas las landing lo tomo como la versión desktop. Que tiene poco ancho, pero funciona igual.

Los iconos los necesito en vector asi uso SVG y no uso imágenes ampliadas para retina.

La versión que te pase se ve bien hasta 640px, en resoluciones menores hay que adaptarlo.

**Comment by FAAREIA** [comment]
Los iconos de los circulos de color nomas, lo otro es imagen

**Comment by LeandroBraier** [comment]
Ok, te los tramito a esos íconos. Entiendo lo que decís de la versión
desktop pero no veo que quede alineado con la estética que usamos en el
sitio de Benteveo en general. Recordá que esta landing se deriva de un
botón que está en la home del sitio de Benteveo. FIjate si podés adaptar el
diseño para que funcione mejor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si queres rediseño las 3 landing asi las hago desktop y luego las adapto a mobile, pero para el viernes no llegamos.

**Comment by LeandroBraier** [comment]
Ok, entiendo, pero me parece mejor hacerlo. Tengamos la de Siguit para el
viernes nomás y las otras dos para mediados de la semana que viene están
bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Ahi te subí los vectorizados a BENTEVEO MAQUETADOR.

**Comment by LeandroBraier** [comment]
Fede, cómo venimos con esta landing? Llegamos para mañana?

abrazo

**Comment by FAAREIA** [comment]
Esta terminando justo eso. Si esta ok, para fin de la semana ya esta
maquetada y responsiva

**Comment by FAAREIA** [comment]
Me falto mover el icono del mundo!

Abrazooooooo

El 13 de enero de 2015, 11:13 a. m., Federico Arena<arena.federico@gmail.com

> escribió:
> 
> Esta terminando justo eso. Si esta ok, para fin de la semana ya esta
> maquetada y responsiva
> 
> El 13 de enero de 2015, 10:18 a. m., LeandroBraier<

**Comment by LeandroBraier** [comment]
Perfecto. Después de eso si podés avanzar tranqui con las otras landings,
con prioridad la de SmartShopping.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
