### ISSUE TITLE
Landing SmartShopping

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#41]
Fede, en carpeta Benteveo Maquetador te dejo esta Landing en PSD para subir a la web de Benteveo. Es la landing que tiene que aparecer cuando se hace click en el logo de SmartShopping en la Sección Innovación.

Cualquier duda me avisás. Necesitaríamos tener las tres landings subidas para el viernes 9 de enero.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, cuando puedas pasame todos los iconos que usaste en vector.
Abrazo

**Comment by FAAREIA** [comment]
![smartshop](https://cloud.githubusercontent.com/assets/6184969/5838930/7f1b4200-a169-11e4-80bb-d1e0b28a8178.png)

**Comment by LeandroBraier** [comment]
Entiendo los cambios que hiciste para simplificar pero me parece que se
pierden cosas en el camino. ¿No se puede hacer más parecido al template que
te mandé? Respetando los textos y las gráficas explicativas? Porque así
queda puro texto y la imagen no te dice mucho.

Tené en cuenta que tengo (si bien no todas) las figuras vectorizadas como
me pedías. Algunas se pueden conseguir en
http://sp.depositphotos.com/purchased/. Es la lista de imágenes que
compramos en Deposit y podemos volver a bajar cuando queremos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, el tema con lo que me enviaste es que no es viable para desktop. Osea, no tengo forma de generar fondos infinitos/repetidos en base a las formas y vectores que usaste en algunos fondos. Por ejemplo, el fondo de la tienda con gente comprando, es irrepetible.

Entiendo lo que decis de que pierde esa cosa visual, pero el usuario gana en rapidez de lectura y evitamos que se asuste con una página tan larga y cargada de cosas.

Más allá de todo esto gráfico, igualmente creo el concepto de lo que se vende queda bien claro.

Avisame como seguimos
Abrazo

**Comment by LeandroBraier** [comment]
Entiendo. Entonces vamos con una versión así para que la vea Eze y si le
gusta ya está. Solo te pido dos correcciones:

1) Está mal escrito "Establecemos"

2) En esa primera parte incluí esa dinámica que quitaste del diseño
original, en la que se ve a la izquierda un teléfono, a la derecha 3
tipitos blancos y al medio Smart Shopping.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-21 13:36 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi van los cambios Lea
Abrazo
![smartshop](https://cloud.githubusercontent.com/assets/6184969/5856252/204864ee-a220-11e4-97ad-78f0af75b023.png)

**Comment by LeandroBraier** [comment]
Está OK!!

Solo corregí la palabra "bi-direccional" y subila nomás.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Te mando la image final o ya la empiezo a hacer HTML?

**Comment by LeandroBraier** [comment]
Hacela nomas con esa pequeña corrección

**Comment by FAAREIA** [comment]
Ok dale

**Comment by LeandroBraier** [comment]
Cuando le pongas el nombre de la página a la landing, corregí la de Siguit
también.

Nombre de página de la landing de Siguit: Siguit by Benteveo

Nombre de página de la landing de SmartShopping: SmartShopping by Benteveo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi va el sitio sin versio responsiva:
http://www.benteveo.tv/_smartshop/

La trama de fondo se ve bastante mal. El tema es que no puedo ponerle multiply o esos filtros photoshop en web, por lo que cuando tenga el logo adapto la img para que quede similar al original.

Abrazo!

**Comment by LeandroBraier** [comment]
Está perfecto. Que la url diga el nombre completo "smartshopping". Lo demás
joya. La versión responsiva cuando puedas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-23 15:02 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hola Lea, ahi esta listo:
http://www.benteveo.tv/_smartshopping/

Abrazo

**Comment by LeandroBraier** [comment]
Genial. Lo único, en los dos iconos de abajo tendrían que estar Siguit y
Social Monitor, no Social Shopping.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi esta actualizado lea

**Comment by LeandroBraier** [comment]
Perfecto. Subilo a la web directamente. El de WebChat también.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, vos decis que ponga los links en la web de benteveo?
¿Smartshopping y webchat no tienen urls propias?

**Comment by LeandroBraier** [comment]
Nop. Esas no.

**Comment by FAAREIA** [comment]
Todo listo Lea

**Comment by LeandroBraier** [comment]
Muy bien Fede!

Lo único que te pido es, en la de WebChat, que el logito verde de abajo no
se superponga con la frase "Desarrollado y producido por Benteveo"

Agregale una línea debajo. Lo demás perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, con el logito verde te referis al auricular?

**Comment by LeandroBraier** [comment]
Exacto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
