### ISSUE TITLE
Landing WebChat

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#42]
Fede, en carpeta Benteveo Maquetador te dejo esta Landing en PSD para subir a la web de Benteveo. Es la landing que tiene que aparecer cuando se hace click en el logo de WebChat en la Sección Innovación.

Cualquier duda me avisás. Necesitaríamos tener las tres landings subidas para el viernes 9 de enero.

abrazo

**Comment by FAAREIA** [comment]
Ahi va el diseño, avisame y avanzamos!
Abrazo

![webchat](https://cloud.githubusercontent.com/assets/6184969/5922924/2c696f18-a62e-11e4-9346-32024d45e070.png)

**Comment by FAAREIA** [comment]
El chat podría estar funcionando asi la gente lo prueba.

**Comment by LeandroBraier** [comment]
No entiendo la captura. No tiene nada que ver con el diseño que te había enviado, o si?

Está bueno que el chat esté ahí y funcione, pero cuál sería? El mismo que el de Benteveo o el que aparece embebido en el html?

**Comment by FAAREIA** [comment]
Claro, la pantalla la rehice. El tema es que el monitor y la lupa no pueden estar al corte porque en monitores anchos no funcionaría, solo en celulares.
El chat sería el mismo de siempre, pero con ese estilo.

**Comment by LeandroBraier** [comment]
Pero no la veo bien a la captura, se ve fea, cortada. Mirá como la veo. Seguro que no es tu adaptación eso.

![captura de pantalla 2015-01-28 a la s 10 52 43](https://cloud.githubusercontent.com/assets/6719872/5938584/24c29912-a6db-11e4-8bfa-e87966988284.png)

**Comment by FAAREIA** [comment]
El margen no lo tiene, pero en realidad la columna del blanco va al 100% del alto de pantalla, igual que la línea. Después no supe que mucho más agregarle, me veia con pocos elementos y contenido para jugar un poco =/

**Comment by LeandroBraier** [comment]
Ok, entonces buscale una vuelta más linda tomando cosas del diseño que te
mandé. La verdad que así es medio impresentable. Si querés pasarme una refe
y que lo rediseñemos con el diseñador en base a la refe lo hacemos. Tenemos
tiempo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-28 12:19 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Voy a tratar de darle otra vuelta. Lo que me habías enviado no puedo usar mucho, esta todo al borde o en diagonal. Ponerlo aislado en el centro, lo probé y no me cerraba mucho.

**Comment by FAAREIA** [comment]
Algo asi podría ser, le agregué unos títulos sino la verdad se hace muy dificil llenar los espacios y crear algo "sólido". Decime que te parece. Abrazo

![webchat](https://cloud.githubusercontent.com/assets/6184969/5960577/45119fda-a7b5-11e4-9092-3d40a513ef90.png)

**Comment by LeandroBraier** [comment]
Lo veo OK. Vamos adelante nomás. Está bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-29 12:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hola Lea, ahi va la landing.
Con respecto al chat, ¿queres que funcione igual que el chat de benteveo? ¿o lo mandamos a otro mail?

http://benteveo.tv/_web-chat/

Avisa!
Abrazo
