### ISSUE TITLE
Corrección en Template de Mails Cadena de mails: Links a Landings

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#43]
Fede, puede ser que los links del template los hayas armado así: http://benteveo.tv/marea?mail=1 ???

Si es así, necesito que lo corrijas para mañana. Antes los armabamos asi: http://benteveo.tv/marea/?mail=1

Esa es la única forma de que me aparezca la URL customizada en analytics. Ahora me aparece simplemente "/marea/" y no sé si es un testeo nuestro o el link único que viene del mail.

Confirmame cuando lo hayas corregido porfa.

abrazo

**Comment by FAAREIA** [comment]
Agrego a Marce K. a este issue. Desconozco porque te aparece la barra ahora.
La URL esa de donde se arma?

**Comment by mkreyness** [comment]
Es el template que armaste en su momento, mi programa reemplaza el 
titulo-safe, pero en el template falta la "/".

Aca:
www/mailing/marcas-alternativo/marcas.html

<a href="http://benteveo.tv/?mail=1

debe decir:

<a href="http://benteveo.tv//?mail=1

no lo hago yo para que tu backup este actualizado y no se pise por error.

**Comment by FAAREIA** [comment]
hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
