### ISSUE TITLE
Problemas de Metadata en Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#44]
Fede, fijate lo que me dice este reporte:

http://www.metricspot.com/www.benteveo.tv

Lo que más me preocupa es lo primero lo del redireccionamiento de WWW pero fijate todo lo que menciona el reporte y hagamos las correcciones necesarias, en caso de ser confiable la fuente.

abrazo

**Comment by FAAREIA** [comment]
Que haces Lea, ahi le corregí eso de no-www a www
Por otra parte, también corregí algunos atributos obsoletos en el html. Después todo lo otro es lo ya charlado, por ejemplo:
- Meta description de más de 145 caracteres. He leido que igual sirve
  Sitemap. No hace falta.
- URL limpias. Eso debe ser lo de marce y las landing page. PERO igual no influye porque no posiciona.
- Etiquetas repetidas. Es HTML5, es válido.
- Pagina 404. No la haría, los links que ponemos los chequeamos siempre.
- CSS para impresión. No hace falta, nadie va a imprimir el sitio de benteveo

**Comment by LeandroBraier** [comment]
Perfecto, gracias Fede.

Respecto de la metadescription, igual acortala si podés de la siguiente
manera:

Estrategia de comunicación, imagen de marca, campañas social media con
desarrollos interactivos, aplicaciones, acciones  y piezas publicitarias.

Y sumale el sitemap porfa, creo que en este caso vale la pena para Google.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-13 8:49 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi actualicé todo e hice el sitemap

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto. Gracias Fede!!

abrazo
