### ISSUE TITLE
Error en Landings de Marcas Campaña Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#45]
Fede, fijate, no anda ninguna landing. ¿Qué puede ser?

Pongo esto:

http://benteveo.tv/limite-vertical/

Y me lleva a acá:

http://www.mr.benteveo.tv/cgi-bin/simarca.pl?q=mr/limite-vertical

Puede ser este cambio de www que hiciste hoy?

**Comment by mkreyness** [comment]
Le agregaron algo para que fuerce un www delante ?
Eso es incompatible con todo lo que hicimos de que redireccione a 
mr.benteveo.tv

**Comment by LeandroBraier** [comment]
Si, creo que si.

**Comment by mkreyness** [comment]
No se que, pero habria que revertirlo, al menos que no aplique si YA hay 
un subdominio como es mr.

**Comment by LeandroBraier** [comment]
Si, a full. Fede, vos lo podés ver a eso? POrque en estos días estamos retomando la campaña de mails.

**Comment by FAAREIA** [comment]
Si, el redirect lo puse desde el htaccess
Comenté el redirect y ahora funciona como antes, habría que adaptarlo para
que no agarre subdominios ni nada. El código lo saqué de uno que siempre
uso, si podes adaptarlo Marce, joya. El regex nunca lo voy a entender.

Abrazo

2015-01-13 19:23 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by mkreyness** [comment]
```
ok, voy a ver que puedo hacer para restablecerlo sin que rompa lo
otro.

El 13/01/2015 a las 20:52, Federico
  Arena escribió:

Si, el redirect lo puse desde el htaccess

  Comenté el redirect y ahora funciona como antes, habría que
  adaptarlo para

  que no agarre subdominios ni nada. El código lo saqué de uno que
  siempre

  uso, si podes adaptarlo Marce, joya. El regex nunca lo voy a
  entender.


  Abrazo


  2015-01-13 19:23 GMT-03:00 LeandroBraier
  <notifications@github.com>:


  > Si, a full. Fede, vos lo podés ver a eso? POrque en estos
  días estamos

  > retomando la campaña de mails.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/45#issuecomment-69832608
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Gracias a los dos!

Igual siguen sin andar las landings. Puede ser?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-13 21:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No, andan bien.
Debes tener cacheado el redirect.

El 13/01/2015 a las 21:42,
  LeandroBraier escribió:

Gracias a los dos!


  Igual siguen sin andar las landings. Puede ser?


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2015-01-13 21:34 GMT-03:00 mkreyness
  <notifications@github.com>:


  >

  >

  >

  >

  >

  > ok, voy a ver que puedo hacer para restablecerlo sin que
  rompa lo

  > otro.

  >

  > El 13/01/2015 a las 20:52, Federico

  > Arena escribió:

  >

  >

  > Si, el redirect lo puse desde el htaccess

  >

  > Comenté el redirect y ahora funciona como antes, habría que

  > adaptarlo para

  >

  > que no agarre subdominios ni nada. El código lo saqué de uno
  que

  > siempre

  >

  > uso, si podes adaptarlo Marce, joya. El regex nunca lo voy a

  > entender.

  >

  >

  > Abrazo

  >

  >

  > 2015-01-13 19:23 GMT-03:00 LeandroBraier

  > <notifications@github.com>:

  >

  >

  > > Si, a full. Fede, vos lo podés ver a eso? POrque en
  estos

  > días estamos

  >

  > > retomando la campaña de mails.

  >

  > >

  >

  > > —

  >

  > > Reply to this email directly or view it on GitHub

  >

  > >

  > <

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/45#issuecomment-69832608
      > >

```
  > > .

  >

  > >

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/45#issuecomment-69849571
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Cierto. Ahora sí.

Gracias a los dos!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-13 21:51 GMT-03:00 mkreyness notifications@github.com:
