### ISSUE TITLE
Agregado de Video en Landings de Marcas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#46]
Fede, necesito agregar un video más a las landings para las marcas. Este video iría debajo del "VER MÁS" que viene después de "CÓMO LO HACEMOS"

Debería tener un título igual a COMO LO HACEMOS pero que diga:

"Así mejoramos el posicionamiento de tu marca"

El video es este:

https://vimeo.com/116121085

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi va:

Mail: http://www.benteveo.tv/mailing/marcas/marcas.html
Landing: http://mr.benteveo.tv/alternativa-comunica/

Si no ves la actualización en la landing, dale 30m+ porque capas que aún no se actualizó el template en el sistema.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

Es cierto, no la veo aún.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Che, revisé de nuevo y sigue sin aparecer. Lo chequeás porfa?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-15 10:51 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Le digo a Marce que lo renueve.

**Comment by mkreyness** [comment]
```
ya deberia estar, por favor confirmen.

El 15/01/2015 a las 13:23, Federico
  Arena escribió:


  Le digo a Marce que lo renueve.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Lo veo chiquito al video, puede ser?

Miren.

http://mr.benteveo.tv/alternativa-comunica/

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
```
El de abajo ? Si, yo tambien lo veo chiquito.

El 15/01/2015 a las 14:49,
  LeandroBraier escribió:

Lo veo chiquito al video, puede ser?


  Miren.


  http://mr.benteveo.tv/alternativa-comunica/


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  On Thu, Jan 15, 2015 at 2:15 PM, mkreyness
  <notifications@github.com> wrote:


  >

  >

  >

  >

  >

  > ya deberia estar, por favor confirmen.

  >

  > El 15/01/2015 a las 13:23, Federico

  > Arena escribió:

  >

  >

  >

  > Le digo a Marce que lo renueve.

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/BenteveoTV/issues/46#issuecomment-70121956
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ahi lo arreglé, estaba subiendo a otra ruta el mismo archivo. F5 y lo ven.
Por otra parte, la carpeta "_nucleo" que esta en "public_html" no la usa nadie no? Con esa me confundia

**Comment by LeandroBraier** [comment]
Ahora perfecto. Gracias!

**Comment by mkreyness** [comment]
En los templates se referencia a ../_nucleo, supuestamente eso se 
resuelve a mr/_nucleo porque se lo referencia desde mr/<marca>
Renombralo y vemos que pasa, si no pasa nada, matalo.
