### ISSUE TITLE
Firmas HTML Benteveo + Adaptación Apple

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#47]
Fede, para la semana que viene, tranqui, necesitaríamos esto para:

Mariana
Marcelo
Ezequiel
Leandro (yo)

Los mails sabes como son: NOMBRE DE PILA@benteveo.tv

El teléfono es el teléfono de Benteveo para todos. Tomá de referencia la firma mía o la de Eze en los mails.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, acordate de mandarme eso!
Abrazo

**Comment by LeandroBraier** [comment]
Cierto Fede!

Acá van las URL y firmas
![unnamed](https://cloud.githubusercontent.com/assets/6719872/5816593/a0188f60-a080-11e4-9bdb-6326f23c3229.png)

https://gm1.ggpht.com/JdHgydl5_6YTPeBzLZadU-ugUu4215jJNrFPtU9DbJafaDuOzpceJOViEhLOFF-T8jQqTGiX6bZuAgjZ4Isp5jybKYN32niyGsmuIg2XNkI4-4i9OJYu0cqyYk8-W7cQ3Rb4vCfqgkG3A5HbW68lg55JsXhpZGa9E__YxKqfEKcw49kOVRu8miBZdFS5pgENB6Anqg89imBRr6-LGImYDLXZX4hGWTCCbIxZFwH6Cg86oRdTroOBpVhKslV7sjTnh83sSEn_-lz4iyGxxONpcETMvB77hLG0TRPt6avKF9x1WTXJc8_KqZTB9xZC0mVefxazYY9SdaDbuBmNKr5Txcb8KgV2NwdQa-Cu0FIzZ133OCWB8ueKTyszuAN_CmhRRl58mo9vIlMCNeTsQ6uytS9RO6FW9eMs2n5XG4HI_u0E0S8EHT_owAeHpdv0mvJUJWq4zp9aWTqg8Bz4aeRrqC_eeBIoJFHpZbLAVKyfGgRa_aluybX44eChRCbzKOktmJ8gdORLtdUDGCxTmbIZmku-F1TbPa1PJO7iv_Mf6NN__fiR3eCFKNpL_VGek0-8BOfk9B0n=s0-l75-ft-l75-ft

El de Marce sería igual al de Eze pero que diga Marcelo Susevich y el mail diga marcelo@benteveo.tv

Todos tenemos el mismo teléfono, URL, todo.

abrazo

**Comment by FAAREIA** [comment]
Ok perfecto. En un rato ya lo pruebo y se los envío
Abrazo!

**Comment by FAAREIA** [comment]
Ahi va un ejemplo:
http://benteveo.tv/_email-firma-ms.html

Al logo le saqué esos efectos, ya que a las marcas no se les debe agregar nada extra en el logo.

**Comment by LeandroBraier** [comment]
Perfecta. Sería ideal que la palabra BENTEVEO debajo del nombre sea en
"Regular" no en "Bold" pero así está bien igual.

Si podés pasame los html de estas tres y, si alguien me pide una, la puedo
adaptar yo reemplazando simplemente en el html, verdad?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-21 8:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi actualicé la firma lea. Avisame!

**Comment by LeandroBraier** [comment]
Está perfecta. Pasame directamente los 3 códigos HTML y estamos.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_email-firma-ec.txt
http://www.benteveo.tv/_email-firma-lb.txt
http://www.benteveo.tv/_email-firma-ma.txt
http://www.benteveo.tv/_email-firma-ms.txt

**Comment by LeandroBraier** [comment]
Excelente, Fede. Gracias!!

**Comment by LeandroBraier** [comment]
Perdón, me las mandarías también como las de Río Ancho? Es decir, con el HTML subido como una página web?

Para GMAIL necesito eso, en el webmail de Benteveo ya me quedó joya.

abrazo

**Comment by FAAREIA** [comment]
El archivo es el mismo, osea, en vez de .txt ponele .html
En gmail tenes que subir un archivo de firma? Si tenes que copiar y pegar, copia lo del .txt y pegalo en gmail

Avisa!

**Comment by LeandroBraier** [comment]
Entendido!

Resuelto.
