### ISSUE TITLE
200 nuevas landings más

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#48]
Marce, tengo 200 nuevas landings más para hacer. Consulta: si te paso el doc corregido, para cuando es lo más pronto que llegás a subirlas?

**Comment by mkreyness** [comment]
```
hoy no plis, que estoy a mil con las cosas de ISS. Martes a la tarde
despues de la demo.

El 19/01/2015 a las 12:12,
  LeandroBraier escribió:


  Marce, tengo 200 nuevas landings más para hacer. Consulta: si
    te paso el doc corregido, para cuando es lo más pronto que
    llegás a subirlas?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ok, entiendo. Te lo paso apenas puedo y vos el martes a la tarde lo arrancás.

Gracias!

**Comment by LeandroBraier** [comment]
Felicitaciones por la presentación de hoy Marce!!

Me dijero que fue muy bien.

Acá están los datos de las 200 nuevas para hacer. Sería ideal tenerlo para mañana a la mañana. Avisame para cuando llegamos, al menos con las primeras 50.

https://docs.google.com/spreadsheets/d/11pguWyk1Rhfmgnh1NU2xivv8cfH_NiXsL4EnGxo5mEM/edit#gid=0

**Comment by mkreyness** [comment]
Ahora lo hago, pero no tengo claro QUE, porque fuimos cambiandolo con el 
paso de los dias.
Esto lo vuelco al CMS para que se generen las paginas ? Se va a manejar 
como cadena de mails para que los manden uno por uno con el editor de HTML ?

**Comment by LeandroBraier** [comment]
Ambas dos. NEcesito las landings y que estén cargadas en el CMS para mandar
los mails con el editor HTML uno por uno.

Tené en cuenta que sea la última versión de las landings, que tiene un
segundo video en el cuerpo de la landing.

http://mr.benteveo.tv/bowen-london/

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-20 18:02 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok.
Es todo automatico, yo las cargo y se generan todas de la unica manera 
posible.
Lo que no tengo previsto es usar un 2do email, tendria que modificar el 
CMS y los procesos para eso, vale la pena o lo hago todo con el primer 
mail y listo ?

**Comment by LeandroBraier** [comment]
Hacelo todo con el primer mail, no hay drama. Ya te borré los segundos
mails del doc.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-20 18:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, pero muchos me dieron que ya estaban, por ejemplo:
'oligra'.'corte-criollo','jugos-asuncion','tanoni','inalpa','prolum','iluminando','lunina-iluminacion','emege','plasticos-arenales','multilabel','saigra','arriavata','puerta-sur','polair'

Es correcto ?

**Comment by LeandroBraier** [comment]
Si ya están no los vuelvas a crear. Cualquier cosa te aviso. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-20 18:37 GMT-03:00 mkreyness notifications@github.com:
