### ISSUE TITLE
Posible nuevo video para la Home de Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#49]
Consulta técnica Fede.

Nosotros podemos poner un video en loop como este no?

https://www.airbnb.com.ar/

Entiendo que es similar a lo que ya tenemos.

**Comment by FAAREIA** [comment]
Si, es igual al que tenemos pero con otras dimensiones

**Comment by LeandroBraier** [comment]
Perfecto, me quedo el ticket para cuando tengamos el nuevo video entonces.

Consulta: ¿se puede hacer en FULL HD un video con ese codec? De forma que, si alguien tiene una banda ancha que se lo permite, pueda ver el video en HD, y si no lo tiene lo vea en menor definición.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, FULL HD es 1920x1080, es independiente de la extensión creo.
Por otra parte, si queres detectar la diponibilidad de banda ancha habría que verlo con Marce. Ya se habló en su momento algo similar y para ese proyecto no convenia. El tema de comprobar la banda ancha, al que tiene poca lo mata, y al que le sobra no le influye.

**Comment by LeandroBraier** [comment]
Ok, entiendo. No te preocupes.

Iremos probando distintas versiones entonces de resolución hasta que alguna
funciona bien en baja velocidad pero con buena calidad de imagen.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-22 9:38 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
En realidad estas medio atado ahi, tenes solamente 3 codec de video posibles y no sólo eso.....el navegador selecciona de esos 3, primero los válidos y luego el formato preferido. =/

**Comment by LeandroBraier** [comment]
No digo por formato sino por la calidad del video en si, la resolución, etc.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-22 10:44 GMT-03:00 Federico Arena notifications@github.com:
