### ISSUE TITLE
Iconos de Facebook y Twitter en Nueva Web Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#5]
Hay un bug en la página de Benteveo que ya subiste al front end. Los logos e Facebook y Twitter no se ven. Fijate:

http://www.benteveo.tv/

**Comment by FAAREIA** [comment]
Hay que darle F5 Lea, hay una imagen que se actualizó

2014-08-08 18:28 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Ok. Gracias Fede!
