### ISSUE TITLE
Landing Social Monitor

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#50]
Fede, en carpeta Benteveo Maquetador/ Landing Social Monitor te dejo el PDF editable de la presentación de credenciales de Benteveo.

En la página 9 explicamos en dos líneas un producto que se llama Social Monitor. Ahí mismo tenés el logo y un mock up de un mobile. Lo que necesito es que hagas una landing similar a la de WebCHat pero con este contenido. no te mando diseño ya armado porque así ya lo armás en la misma línea que WebChat.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi va el diseño. Decime que te parece! Abrazo
![home](https://cloud.githubusercontent.com/assets/6184969/6041287/bae25f12-ac59-11e4-8749-42e596d7836a.png)

**Comment by LeandroBraier** [comment]
Te había pasado este feedback, no sé si lo recibiste:

"Está barbara. Agregale nodos a las redes para que parezcan menos telarañas y subila nomas, con link en el icono de Social Monitor en Benteveo."

Avisame nomás cuando esté subida.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_social-monitor/
Ya puse el link en el sitio de benteveo también

**Comment by LeandroBraier** [comment]
Todo perfecto! Gracias!
