### ISSUE TITLE
Cambios en Landing Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#52]
Fede, necesitamos implementar cambios en las landings de Benteveo. Una vez que estén hechas le avisamos a MK para que lo implemente en el CMS. 

Los cambios son:

. Cambiar el video de inicio de la landing por el segundo, el de marketing de contenidos, incluido el título del video "Así mejoramos el posicionamiento de tu marca". No hace falta que tenga los botones al final del video.

. Poner el logo de Benteveo a la derecha.

. agrandar el "Leer más" como botón y cambiarlo por "Quiero saber más" (que sigue scrolleando para abajo, como ahora)

. agregar un segundo botón que sea igual que el de "Quiero saber más" pero que diga "Quiero que me contacten" y tenga el mismo link que el botón de contacto de abajo de todo.

. todo lo demás queda

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, preguntas:
- Los botones que al clickearlos mandan un email a ustedes.......no van más al finalizar el video? seguro? Si sacamos eso, también sacamos la placa final o queda?
- El logo ahora va a la derecha de donde? de la pantalla en general?
- Este segundo botón va al lado del botón "Quiero saber más"?

**Comment by LeandroBraier** [comment]
1. Ok, dejemos la placa final entonces, con los dos botones igual que al pie de la landing.
2. El logo va a la derecha de la pantalla, al pie del video.
3. Sip, y con la misma estética.

**Comment by FAAREIA** [comment]
Hola Lea, ya estan los cambios y la versión responsiva.
Fijate si esta todo OK

**Comment by LeandroBraier** [comment]
Falta. Lo chequeé en este link: http://mr.benteveo.tv/la-cardeuse/
1. El botón sigue diciendo "Para saber más", está chiquito y sin el otro al
   lado que te pedí que diga "Quiero que me contacten".
2. Arriba del video principal debe decir "Así mejoramos el posicionamiento
   de tu marca". El mismo video más abajo debe desaparecer, no queremos dos
   veces el mismo video en la landing.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-05 10:24 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
No esta bien, ahora le digo a MK que actualicé el template. Me había olvidado de eso. Te aviso

**Comment by LeandroBraier** [comment]
Dale, no problem.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ya esta listo eso Lea.
Cualquier cosa decime

**Comment by LeandroBraier** [comment]
Nop. No están.

Mirá el link:

http://mr.benteveo.tv/la-cardeuse/

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Le tenes que dar F5

**Comment by LeandroBraier** [comment]
Si, ahi lo vi. Está bien pero siguen faltando algunas cosas:
1. Los botones "Quiero saber más" y "Quiero que me contacten" siguen
   chicos. 2. Arriba del video debe decir "Así mejoramos el posicionamiento de
   tu marca".

Otro tema: Necesitaría recambiar el thumbnail que aparece en el mail que
generamos con el CMS. Eso se lo pido a Marce, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi agrando los botones. El título está, fijate que dependiendo del alto del navegador, como prioriza el video, a veces se oculta el título. Ésto sería para monitores viejos, si pones el navegador en full screen no pasa

**Comment by LeandroBraier** [comment]
Tenés razón, pero cuando oculta ese título igual le sobra espacio entre el
video y los botones. ¿No se puede aprovechar mejor el espacio para que ese
título se vea siempre?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-09 8:38 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Pruebo como queda entremedio, pero igual va haber momentos en que no va a entrar el título.

**Comment by LeandroBraier** [comment]
Perfecto. Me dijo Marce que el thumbnail lo cambiás vos.

Acá te la adjunto. Me avisás cuando está eso también?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-09 8:52 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si dale, pasame el thumb por mail

**Comment by FAAREIA** [comment]
Fijate ahora Lea, dale F5.

**Comment by LeandroBraier** [comment]
Está perfecto. Una cosita más:

¿habrá posibilidad de que el botón de "Quiero que me contacten" tenga un=1
en su link?

Es para diferenciarlo del botón de contacto de abajo de todo.

También me serviría que quede registrado si tocaron el botón "Quiero saber
más" pero si no se puede no hay problema.

Respecto del Thumbnail, lo recibiste? ya está cambiado?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi me fijo eso, habría que avisarle a Marce si hacemos ese agregado.
Recien me llegó el mail, ahi lo cambio

**Comment by LeandroBraier** [comment]
Gracias. Cuando esté si querés le aviso a Marce, como quieras.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi ya subí la nueva imagen del video.
Ya esta agregado el parametreo nuevo al botón "Quiero que me contacten". El parametro adicional es: "df=1"
Éste cambio lo vas a ver desde Google Analytics ya que te registra las url. El tema es decirle o preguntarle a Marce como podemos hacer para que a vos te quede registrado que clickean "Quiero saber más" que no es un link, sino un boton que baja el scroll.

**Comment by LeandroBraier** [comment]
Si es complicado no, no hace falta. Me basta con la permanencia en el
sitio. Gracias Fede! Ya le aviso a MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-09 10:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
```
y ese boton lleva a algun lado ? Si no hay un form que se dispare o
un link que redireccione a otra parte, no hay ninguna accion
registrable.

El 09/02/2015 a las 10:26, Federico
  Arena escribió:


  Assigned #52
    to @mkreyness.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
el boton es un div, que simplemente scrolea hacia abajo gracias a un jquery. Nada más.

**Comment by FAAREIA** [comment]
Pregunta adicional: ¿cada 1h se actualizaba el template no marce?

**Comment by mkreyness** [comment]
```
No, ya no hay actualizacion masiva, porque interfiere con estado de
los envios de mails.
Los que tuvieran mails sin enviar en ese momento no se
actualizarian.
Lo tengo que correr a mano en un momento en que se sepa que no estan
mandando los mails.
Si este es un buen momento, lo corro ya.

El 09/02/2015 a las 10:31, Federico
  Arena escribió:


  Pregunta adicional: ¿cada 1h se actualizaba el template no
    marce?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
y pero como le llega ALGO a Leandro ? Tiene que haber algun submit
en alguna parte.

El 09/02/2015 a las 10:31, Federico
  Arena escribió:


  boton es un div, que simplemente scrolea hacia abajo gracias a
    un jquery. Nada más.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Correlo si podes, le agregué un parametro a un botón.
Claro entiendo lo que decis, y si hacemos que se abra una ventana sin nada o que se cierre, va a quedar mal y sospechoso. =/

**Comment by LeandroBraier** [comment]
Chicos, no entiendo lo que dicen, pero necesito confirmación de que todas las landings están actualizadas. En caso de que algunas no lo estén, porfa avisenme cuales.

abrazo

**Comment by mkreyness** [comment]
```
Ya lo corri.
Se actualizan todas, pero si tenias justo algun mail por salir no
sale.
Hay una secuencia de estados que es: pendiente, pagina creada, mail
pendiente de envio, mail enviado.
Si lo fuerzo para que se reactualicen todas y alguna estaba en
estado "mail pendiente de envio" vuelve a estado "pagina creada" y
no sabe que tiene que mandar el mail.
Si estaba en "mail enviado" y vuelve a "pagina creada" no importa,
porque igual el mail que recibieron fue con la pagina vieja.

El 09/02/2015 a las 10:58,
  LeandroBraier escribió:


  Chicos, no entiendo lo que dicen, pero necesito confirmación de
    que todas las landings están actualizadas. En caso de que
    algunas no lo estén, porfa avisenme cuales.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto así, Marce. Me parece genial. Recién tiré un mail de prueba por
las dudas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-09 11:44 GMT-03:00 mkreyness notifications@github.com:
