### ISSUE TITLE
Cambiar Thumbnail de Mails CMS Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#54]
Marce, en el mail que se genera automáticamente hay una imagen de Thumbnail que parece pertenecer a un video y va al pie del mail junto con una firma.

Lo que necesito es cambiar esa imagen de thumbnail por la que te adjunto acá. Me avisás cuando la tengas cambiada?

abrazo

![captura de pantalla 2015-02-09 a la s 08 34 38](https://cloud.githubusercontent.com/assets/6719872/6105490/6b6ce908-b036-11e4-8be3-282a7f452490.png)

**Comment by mkreyness** [comment]
```
Todo lo que sea contenido lo maneja Fede, esta en un template.
Yo ni se que hay dentro del mail.

El 09/02/2015 a las 8:46, LeandroBraier
  escribió:


  Marce, en el mail que se genera automáticamente hay una imagen
    de Thumbnail que parece pertenecer a un video y va al pie del
    mail junto con una firma.
  Lo que necesito es cambiar esa imagen de thumbnail por la que
    te adjunto acá. Me avisás cuando la tengas cambiada?
  abrazo

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto. Ya le paso. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-09 8:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Marce, Fede ya lo subió. Lo actualizarías en el CMS?

abrazo

**Comment by mkreyness** [comment]
```
Si Fede toco (como supongo que hizo) el template que esta en
/mailing/marcas-alternativo/marcas.html, no hay que hacer nada mas,
el programa cuando mande los proximos mails que le pidas, ya va a
estar usando la version modificada, para eso son los templates.

El 09/02/2015 a las 10:30,
  LeandroBraier escribió:


  Marce, Fede ya lo subió. Lo actualizarías en el CMS?
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto, Marce! Gracias!
