### ISSUE TITLE
Agregado Simple de Link en HTML de Mails a Marcas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#55]
Fede, necesitaría agregar al html de los mails a marcas (el que tiene el thumbnail con el link y la firma) un link.

Arriba del thumbnail, debería ir simplemente el link común de la marca. 

Por ejemplo: http://benteveo.tv/la-cardeuse/

Y en el hipervínculo real de ese texto iría con el mismo agregado que el link del Thumbnail:

Por ejemplo: http://benteveo.tv/la-cardeuse/?mail=1

Para mañana está bien.

**Comment by FAAREIA** [comment]
Ahi esta listo Lea, pruebenlo y cualquier cosa decime.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!!!

Ahora lo pruebo.

abrazo
