### ISSUE TITLE
Base de mails de suscriptos a la landing "Ser parte"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#57]
Marce, tenés posibilidad de armar esta base de datos y mañana enviarles a todos un mail?

**Comment by mkreyness** [comment]
Si me pasas la base de datos y el texto del mail, si.
Si el mail es un HTML, que Fede lo arme y me pase donde lo dejó.
Lo que seguro que NO puedo es mandarlo desde el servidor de 
FranciscoLaPelicula, lo tendria que mandar del de Benteveo.
