### ISSUE TITLE
Mails de Benteveo no reciben mails

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#58]
Marce, acabo de crear dos cuentas de mail desde el CPanel de Benteveo.tv y no funcionan. Se puede acceder a las cuentas, pero los mails no les llegan.

Te paso el acceso al cpanel:

Usuario: benteveo
Contraseña: 9lKf10uP8r

http://www.benteveo.tv/cpanel

En caso de que haya que hablar con Duplika, porfa decime qué le pregunto.

**Comment by mkreyness** [comment]
Las agregaste donde no habia NINGUNA, es un poco sospechoso que no 
hubiera otras, no ?

Nunca te van a funcionar, hasta donde yo se, el mail de benteveo NO se 
migro al server de benteveo, se debe seguir manejando como antes.

**Comment by LeandroBraier** [comment]
Ah, ok. Me entero ahora.

Tenía entendido que sí se había migrado, porque Fede me pidió backupear
todos los mails, me pidió las contraseñas de todos los mails y los volvió a
cargar.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-19 15:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
tal vez se migró, pero no al actual servidor benteveo.tv, ya que ahi 
solo estan esas casillas que vos pusiste, pero ninguna otra.

**Comment by LeandroBraier** [comment]
Ok, consulto con Fede.

Fede, vos me podés crear tres cuentas nuevas de Benteveo?

serían:

nahuel@benteveo.tv

gabriela@benteveo.tv

florencia@benteveo.tv

En password ponele:

guatemala2015

**Comment by LeandroBraier** [comment]
Fede, Marce S dice que intentó entrar al CPanel de siempre y no puede crear las nuevas cuentas de mail. Lo hablarías con Fede Guillerón o quien corresponda?

**Comment by FAAREIA** [comment]
Ahi le digo, adjunto a todos en el mensaje.

Abrazo

**Comment by LeandroBraier** [comment]
Resuelto Fede! Gracias!
