### ISSUE TITLE
Cuenta de mail @faareia.com

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#6]
Fede, las tres primeras marcas que vamos a enviar de prueba (VieTur, Calzados California y Alternativa) no pueden salir desde la cuenta que queremos usar (cuentas@benteveo.tv) porque son empresas amigas y se van a dar cuenta enseguida de que estamos detrás de esto.

Como vos tenés registrado el dominio FAAREIA, me interesaba saber si no tenés problema en facilitarme el mail cuentas@faareia.com para enviar estos 3 mails de prueba. 

Desde ya muchas gracias

**Comment by FAAREIA** [comment]
Si dale, te lo creo.

2014-08-15 11:02 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Gracias Fede!

Sos un grande.

**Comment by FAAREIA** [comment]
http://faareia.com:2095/
cuentas@faareia.com
abc123

Elegí el icono grande el medio, que es el mejor creo.
Podes ir probando si queres

Abrazo

2014-08-15 11:21 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Mil gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-15 11:29 GMT-03:00 Federico Arena notifications@github.com:
