### ISSUE TITLE
Botón "Pedir un Demo" en Landing Siguit

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#61]
Fede, necesito sumar el botón "Pedir un Demo" a la landing de Siguit. El botón funcionaría de forma similar a los botones de contacto de las landings de Benteveo. Al clickear, un pop up le pediría el nombre, empresa y dirección de mail al usuario con el mensaje "Por favor déjanos tu dirección de mail y nos pondremos en contacto para generar un demos."

A nosotros nos llegaría a cuentas@benteveo.tv un mail similar al de las landing de Benteveo solo que el subject tiene que decir "Contacto Demo Siguit" y en el cuerpo del mail tiene que tener el nombre, la empresa y la dirección de mail.

abrazo

**Comment by FAAREIA** [comment]
Ahi va Lea:
http://siguit.com/

Probalo a ver si llega bien y cualquier cosa decime

Abrazo

**Comment by LeandroBraier** [comment]
Gracias, Fede. Estéticamente quedó bueno. El tema es lo funcional.

1) El mail no me llega a cuentas@benteveo.tv

2) El mensaje que me aparece cuando ingreso los datos es "Por favor complete todos los campos" en rojo, lugar de un texto de fondo verde que diga "Gracias por dejarnos tus datos. Nos pondremos en contacto para responder a tu pedido." Entiendo que esto significa que dio un error el formulario pero la verdad no entiendo por qué debería darlo, siendo re simple y yo ingresé todos los datos pedidos.

![captura de pantalla 2015-02-23 a la s 10 16 58](https://cloud.githubusercontent.com/assets/6719872/6328337/1fa4f80c-bb45-11e4-8c5c-6de285d9a375.png)

**Comment by FAAREIA** [comment]
Ahi lo arreglé Lea, estaba mal algo en el código que manda el email.

Abrazo

**Comment by LeandroBraier** [comment]
Ahorá el mensaje sale verde bien, pero el mail no me llega. Puede ser?

**Comment by FAAREIA** [comment]
Fijate en spam, sino avisame.

**Comment by LeandroBraier** [comment]
Confirmo. Sigue sin llegar el mail, ni en Basura ni en Inbox.

Si querés te doy el acceso para que hagas las pruebas o probá con un mail
tuyo, como prefieras.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Esa casilla de email esta llena por casualidad?

**Comment by LeandroBraier** [comment]
No, está al 40% de su capacidad nomás.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-23 11:34 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si, estoy probando y tampoco me llega. Voy a ver bien que puede ser.

**Comment by FAAREIA** [comment]
Ahi lo estuve viendo y no puedo ver que es lo que esta fallando, esta todo bien.
Pongo a Marce K en el issue a ver si sabe que puede ser.

**Comment by FAAREIA** [comment]
Aca esta la URL: http://siguit.com/index2.html

**Comment by mkreyness** [comment]
Voy a cambiar el destinatario por mi a ver que pasa.

**Comment by mkreyness** [comment]
No salen los mails de ese servidor, quedan en un estado "queued".
No importa quien lo mande o a donde se manden.

Recuerden que es un servidor de garron prestado por Alternativa.
Habria que consultar con Luciano Cesare.

**Comment by LeandroBraier** [comment]
No se pueden mandar desde el servidor que usamos en la web?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-23 17:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Es que no se pueden mandar de un lugar donde no estan.
Para eso habria que haber hecho la pagina en el server de Benteveo, no 
en el de Siguit.

Yo justamente cuando hice apuntar el dominio siguit.com a este servidor 
(que es de prueba, de garron, para desarrollo, de uso interno, etc. 
etc.) justamente a proposito NO hice apuntar www.siguit.com. Eso podria 
estar apuntando al mismo servidor de benteveo.tv y manejar todo desde ahi.

Se le puede pedir a Cesare (que administra el DNS donde esta cargado 
siguit.com) que haga que www.siguit.com apunte al IP de benteveo.tv, 
siempre y cuando el plan que tengamos con Duplika permita cargar otro 
dominio (www.siguit.com) ahi.

**Comment by LeandroBraier** [comment]
No, no tiene multidominio. Por eso no está apuntando ahí. Vamos a tener que
hablar con las personas que decís Marce y que nos solucionen ese tema para
el servidor de Siguit.com.

Vos lo hablás Fede?

No hay tanto apuro, si lo resolvemos esta semana está bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-23 17:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No core que Fede conozca a Cesare. Yo tampoco lo conozco personalmente, 
pero intercambié algunos mails y entiendo que a veces anda por la 
oficina de ustedes.
Lo otro que se me ocurre es que podrias Fede poner en el form que el 
action llame a http://www.benteveo.tv/<lo que sea> y pasar el script 
ahi, tendria que andar igual.

**Comment by mkreyness** [comment]
Donde dice "No core" lease "No creo"

**Comment by FAAREIA** [comment]
Ahi ya lo probé con los archivos del mail en el hosting de Benteveo y funciona. Me había olvidado por completo que era otro server de esos raros.

Abrazo

**Comment by LeandroBraier** [comment]
Excelente, ya funciona. Gracias!
