### ISSUE TITLE
Posible Maquetador

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#62]
Fede, fijate qué te parece el curriculum de este pibe.

http://grafitodd.com.ar/BraulioEvangelisti/

Lo estoy entrevistando ahora por Skype. Decime si querés que le consulte algo en particular.

abrazo

**Comment by LeandroBraier** [comment]
Fede, recién hablé con Braulio y me parece que es el perfil justo. Todos los lenguajes que me dijiste los conoce y los trabaja y es un diseñador que terminó trabajando en maquetación porque es lo que más laburo le dio. Le gusta, pero le gusta también el diseño.

Ahora les mando un mail a los dos para que se pongan en contacto y, si vos me das el ok, ya avanzamos en la negociación para contratarlo.

abrazo

**Comment by FAAREIA** [comment]
dale buenisimo, pasame el skype asi hablo con el asi hablo un toque pero por lo que me decis es el perfil que buscamos asi que excelente.

Abrazo

**Comment by LeandroBraier** [comment]
Buenísimo!

el skype es braulio.evangelisti

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ya hablé con el pibe y va a ir bien. Avanzá tranqui

**Comment by LeandroBraier** [comment]
Genial! Buenisima noticia.

Abrazo

**Comment by LeandroBraier** [comment]
Fede, hoy arranca Braulio. Podés ya contactarlo para empezar a laburar y darle su propio mail de Benteveo.

es braulio@benteveo.tv y su password es: guatemala2015

Vos sabés el link de acceso al webmail.

Cualquier cosa que necesiten hacer un skype o algo me decís.

abrazo
