### ISSUE TITLE
Newsletter Simple Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#63]
Fede, necesito tener para hoy a la tarde un newsletter HTML lindo pero muy simple para Klaukol. Es para generar cierta intriga a los empleados de la empresa para que vayan a la presentación del producto el miércoles.

El texto es el siguiente:

Asunto: Una presentación. Un lanzamiento. Y vos

Contenido del mail:

¡Te invitamos a conocer lo nuevo de Klaukol! El miércoles 11 de marzo será un día a pura potencia donde conoceremos la nueva propuesta para 2015.

¿Dónde?

En las Oficinas de San justo

¿A qué hora?

A las 12hs.

¿Voy comido?

No, tendremos un almuerzo esperándote.

¡No te lo pierdas!

Llegamos?

**Comment by FAAREIA** [comment]
Teniendo en cuenta que es algo interno, simplificaría la maquetación y haría que todo sea imagen.
Decime que te parece, Abrazo

![mailing](https://cloud.githubusercontent.com/assets/6184969/6507105/98686364-c32e-11e4-9325-e825c8d65689.png)

**Comment by FAAREIA** [comment]
Ahi va con borde gris!
Abrazo

![mailing](https://cloud.githubusercontent.com/assets/6184969/6507139/d03a82f4-c32e-11e4-8e87-b2cc898c1410.png)

**Comment by LeandroBraier** [comment]
Excelente Fede! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Avisame y generamos el newsletter.
Abrazo

**Comment by FAAREIA** [comment]
En que quedó esto lea?

**Comment by LeandroBraier** [comment]
Está resuelto Fede!! Les pasé la imagen sola.

abrazo
