### ISSUE TITLE
Sumar logos Parex, Klaukol, Lanko y Revear a la Web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#64]
Sin apuro, sumalos donde están los logos de todas las marcas en la sección Entretenimiento + Comunicación.

Si no los tenés avisame y te los paso.

abrazo

**Comment by FAAREIA** [comment]
http://benteveo.tv/index2.html
Avisame si lo ves OK
Abrazo!

**Comment by LeandroBraier** [comment]
Excelente! Si pudieran estar los 4 seguidos mejor pero así está bien también.

abrazo

**Comment by LeandroBraier** [comment]
Fede, nunca corregiste ni subiste esto a la versión online. Subilo urgente porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea

Fijate ahora, ya esta hecho y subido.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Braulio. Gracias.

Avancemos con los pendientes de Klaukol y Francisco.

abrazo
