### ISSUE TITLE
Link Google Maps en Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#65]
Fede, necesito linkear la pagina de Benteveo con Google Maps. Para esto, entiendo que habría que actualizar el mapa que figura en la web abajo de todo.

Este link habla de eso:

http://googlegeodevelopers.blogspot.com.ar/2014/03/adding-new-google-maps-to-your-website.html

Lo que necesitamos es que aparezca en el buscador de Google Maps.

abrazo

PD: esto no es urgente. Dentro de la semana está bien.

**Comment by braulio-evangelisti** [comment]
Lea, como primera medida para que pueda buscarse como lugar en google maps, hay que darle de alta a la empresa en Google Places(Ahora es Google Business).

https://www.google.com/business/

preferentemente usar una cuenta de gmail que sea del estudio, la misma que se usaria para un perfil en Google+ por ejemplo, y para registrarse en diferentes productos de Google como empresa.

**Comment by LeandroBraier** [comment]
Listo,ya estamos esperando verificación. Gracias!
