### ISSUE TITLE
¿Con qué tecnología podríamos hacer esto?

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#69]
http://lacriaturacreativa.com/2015/06/canal-crea-el-formulario-de-suscripcion-mas-divertido/

Sería para Benteveo.

**Comment by mkreyness** [comment]
Que BUENA idea !
En nada que yo conozca, pero debe haber formas de hacerlo en flash, 
supongo, y habria que programar cada formulario en forma individual.
Cualquier otra cosa en que para cada campo o pagina haya un video 
independiente tendria seguramente transiciones muy poco naturales.
A su vez el flash muere a corto plazo.

**Comment by LeandroBraier** [comment]
Podría ser esta tecnología entonces?

https://interlude.fm/

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-02 17:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No se, no veo que permita input. Mas bien parece una forma sofisticada 
de hacer menues, pero sin un input real, o viste alguna de las demos en 
las que se pueda tipear ?

**Comment by LeandroBraier** [comment]
Vos decís Interlude, no?

Yo no lo vi, por eso te preguntaba si por ahi pensabas con esa misma
tecnología se podía. La verdad que un misterio.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-02 17:41 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Interlude, mire las demos y todas me parecen que son "interactivos" en 
el sentido de que podes elegir que camino tomar, pero no INGRESAR info.
Hacer esto en un app o un software de PC seguro que se puede, pero el 
asunto es que ande via web en cualquier plataforma, no ?.

**Comment by LeandroBraier** [comment]
Claro. Difícil. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-02 17:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Claro, habría que ver como se accede a ese formulario y es probable que sea un desarrollo personalizado usando video html para aplicación o para web
Esta bueno pero como dice MK, vamos a excluir a X cantidad de gente seguro.

**Comment by LeandroBraier** [comment]
Claro. Pero entonces es una sucesión de páginas web html 5 con fondos de video distintos. En el spot editaron las partes de la carga.

 Vos pensa que en francia no debe haber cavernicolas con Explorer 6 y Pentium 4 como aca, que encima tienen pretensiones. Jeje

Abrazo y gracias a los dos!

**Comment by FAAREIA** [comment]
Y es más dificil, pero más allá de eso hay una campaña detras de eso, si no podes usarlo te quedas afuera, probablemente el público objetivo tampoco sea de los que tengan un navegador viejo.
No se si será una sucesión de videos, habría que investigarlo bien y analizar todo lo que ofrece un video HTML5 en programación.
