### ISSUE TITLE
Problema de responsive en imagen puntual de la web de Benteveo. 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#70]
@FAAREIA : esto me parece que es para braulio, pero lo dejo a tu criterio nomás. 

![captura de pantalla 2015-07-13 a la s 13 07 32](https://cloud.githubusercontent.com/assets/6719872/8664580/673d29cc-29af-11e5-9c3f-28c0e0a87628.png)

Como ves en la captura, el fondo rosa no queda bien como responsive para esa imagen. El fondo debería ser azul, no?

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Perfecto!

Gracias.
