### ISSUE TITLE
Landing para Presentaciones a Clientes de Benteveo. 23/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#71]
@FAAREIA para el jueves necesito que me propongas una landing donde poder embeber una presentación tipo Powerpoint de Google Doc.

La idea es tener 10 urls fijas donde vamos a ir embebiendo las distintas presentaciones que le hacemos a un nuevo cliente.

En la reunión le regalaríamos al cliente un mantel de papel brandeado de Benteveo que tendría un código QR con esa URL, con lo cual tendríamos 10 versiones distintas del mantel para ir entregandole a los sucesivos clientes.

Cualquier duda avisame.

abrazo

**Comment by FAAREIA** [comment]
Ahi podes ver una URL con un documento embebido:
http://www.benteveo.tv/_codigo-qr/

La pregunta es si van a estilizar la landing para el cliente dentro del PowerPoint o si esa estilización la quieren por fuera del archivo y que sea HTML. En caso de elegir la última opción, vamos a tener que idear un recuadro para mostrar el visor del PPT

**Comment by LeandroBraier** [comment]
La estética en principio sería nuestra, de Benteveo. Pero ojo que el embed
es de un documento de drive. Un Google Slide de Google Drive, no un ppt así
nomás. Está preparado para eso?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-21 11:58 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Pasame la url de uno que tengan e investigo

**Comment by LeandroBraier** [comment]
Te paso el embed por mail.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_codigo-qr/?noredir=1

Ahi va actualizado Lea.

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Dos cosas nomás:

1) Fijate si podés hacer que arranque en PLAY la presentación, el embed que te pasé yo le había puesto esa opción me parece.

2) Necesito que me armes un landing así en 10 URLs distintas que se llamen así:

/propuesta-creativa/

/estrategia-creativa/

/propuesta-2015/

/estrategia-2015/

/presentacion-propuesta/

/presentacion-propuestas/

/presentacion-estrategia/

/presentacion-creativa/

/presentacion-ideas/

/propuesta-presentacion/

Después te voy a ir pasando el embed a cambiar en cada uno cuando le presentemos al cliente las propuestas.

Más adelante, cuando tengamos nuevos clientes y ya hayamos utilizado las 10 landings, iremos renovando las mismas cambiando el embed.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_codigo-qr/propuesta-creativa/
Ya tiene play automático y las carpetas estan creadas.

**Comment by LeandroBraier** [comment]
Genial. Gracias! La carpeta codigo-qr se le puede cambiar el nombre a /ideas/ ?

Pensando en la prolijidad frente al cliente.

**Comment by FAAREIA** [comment]
Ahi lo cambié a "_ideas"

**Comment by LeandroBraier** [comment]
Gracias Fede!

**Comment by LeandroBraier** [comment]
Fede, me funciona solo el primer link. Todo el resto no. Serían:

http://www.benteveo.tv/_ideas/estrategia-creativa/

http://www.benteveo.tv/_ideas/propuesta-2015/

http://www.benteveo.tv/_ideas/estrategia-2015/

http://www.benteveo.tv/_ideas/presentacion-propuesta/

http://www.benteveo.tv/_ideas/presentacion-propuestas/

http://www.benteveo.tv/_ideas/presentacion-estrategia/

http://www.benteveo.tv/_ideas/presentacion-creativa/

http://www.benteveo.tv/_ideas/presentacion-ideas/

http://www.benteveo.tv/_ideas/propuesta-presentacion/

Avisame cuando esté porfa.

abrazo

**Comment by FAAREIA** [comment]
Es que necesito que me pases el código para embeber para cada uno. Sino va a estar repetido lo que ya viste.

**Comment by LeandroBraier** [comment]
Entendido! Por ahora ponele el mismo embed asi puedo armar el codigo qr con la url confirmada y despues a medida que voy teniendo los embed te los paso por tickets aparte.

Abrazo

**Comment by FAAREIA** [comment]
Listo a todo

**Comment by LeandroBraier** [comment]
Gracias Fede! abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA , necesito URGENTE que subas los siguientes embeds de Google Slides a las siguientes URL:

EN:

/propuesta-creativa/

VA EMBED 1 PATY (te lo mando por mail)

EN: 

/propuesta-creativa2/

VA EMBED 2 IRSA (tambien por mail)

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_ideas/propuesta-creativa/
http://www.benteveo.tv/_ideas/propuesta-creativa2/

**Comment by LeandroBraier** [comment]
Gracias Fede! excelente!

**Comment by LeandroBraier** [comment]
HOla @FAAREIA 

necesito que lo antes posible me armes una nueva url con un embed.

Sería esta URL:

http://www.benteveo.tv/_ideas/propuesta-2016/

El embed te lo estoy pasando en breve.

**Comment by LeandroBraier** [comment]
Ante la duda (poruqe lo acabo de corregir) la url correcta a crear es:

http://www.benteveo.tv/_ideas/propuesta-2016/

abrazo

**Comment by LeandroBraier** [comment]
Fede, acá está el embed. Porfa confirmame cuando esté todo arriba.

`<iframe src="https://docs.google.com/presentation/d/18B0uUT3GxnnuiarXU141A28E4w7xsRjW6cwFhqci53k/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="629" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>`

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!!! abrazo grande
