### ISSUE TITLE
Blog Benteveo. 29/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#72]
Buen día @braulio-evangelisti !

Te paso un pedido nuevo. NEcesito si podés tunear con la misma estética que el newsletter de Benteveo este blog de blogger:

https://www.blogger.com/blogger.g?blogID=7350974466103458504#allposts

El acceso para editar te lo mando por mail. Confirmame si llegás para mañana. Es muy simple la edición pero vos tenés todos los elementos ya para armarlo más fácil.

abrazo

**Comment by braulio-evangelisti** [comment]
Estoy con la maquetación de la landing de paty, capas mañana a la tarde pueda estar esto, depende cuanto nos lleve paty.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto. Para mañana a la tarde está más que bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-28 9:02 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Cómo venimos con este blog?

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate si ahi va queriendo Lea. Ya para poner una entrada de diferente color a la otra nose si se puede dentro del motor de blogger, tendria que investigarlo.

Abrazo

**Comment by LeandroBraier** [comment]
Quedó muy bueno Brau!!

En base a eso lo retoco, le corrijo los posts y estamos. Gracias!!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-30 11:59 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Buenisimo.

Tene cuidado cuando pegas texto copiado desde otro lado en el editor del post que te pega los estilos tambien. Hay un boton en el editor que es para borrarle todo estilo al contenido que pegaste (Una T con una x chiquita). Los textos de los post de prueba tenian el fondo blanco y cuando le cambie el color al gris ese recien ahi se noto.

Abrazo

**Comment by LeandroBraier** [comment]
Excelente info. Gracias Brau! recién me entero de ese botón.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-30 14:04 GMT-03:00 Braulio Evangelisti notifications@github.com:
