### ISSUE TITLE
Blog Benteveo. 10/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#73]
Brau, estuve intentando retocar el blog pero me está costando dejarlo como necesitamos.

Te paso una referencia:

http://blog.nextperience.net/

Queremos que el blog de una imagen más pro como esta, pero con la estética actual, que está buena. Para eso, le saqué los dos widgets de la derecha, pero habría que sumarle lo siguiente:

1) Una barra arriba como la de Nextperience en la que figure Benteveo. Agencia + Productora y los links a Facebook, Vimeo, Google + y Linkedin.

2) Que en lugar del listado clásico de artículo que te pone BLogger aparezcan recuadros con solo el título y los GIFs animados de cada artículo. Al clickear en esos recuadros sí llevaría al clásico artículo de blogger tal como está.

3) En la columna derecha necesito 

a) Un primer recuadro como el de Nextperience que diga 

"No buscamos ideas grandes y costosas, simplemente nos concentramos en hacerlas originales.
Benteveo. Agencia + Productora. 
En este blog contamos todas las novedades del mundo de la comunicación masiva y digital."

b) Debajo de eso al igual que en la refe que pregunta: ¿Querés recibir nuestras novedades? Subscribite a nuestro newsletter. El campo de mail y el botón de "Suscribite"

Arrancá el lunes con esta prioridad porfa.

abrazo

**Comment by LeandroBraier** [comment]
Va logo nuevo Brau!

![logo-benteveo-agencia-productora](https://cloud.githubusercontent.com/assets/6719872/9152522/85c4cdd4-3e02-11e5-88b2-43169009a695.png)

**Comment by LeandroBraier** [comment]
Hola @braulio-evangelisti ! Como venis con esto?

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti !! Hoy metamosle a full para tener esto a la tarde. Confirmame por favor.

abrazo

**Comment by braulio-evangelisti** [comment]
Hola lea. Le estuve dando a la mañana. Lo del encabezado y footer en todo el ancho es medio complejo y me va a llevar mas tiempo.
Si lo queres terminado hoy lo puedo dejar con el estilo del newsletter como estaba antes.
Abrazo

**Comment by LeandroBraier** [comment]
No hace falta que sea todo el ancho. Hacé una primer versión que tenga la estética que te pido pero no todo el ancho por ahora. Que todo el ancho sea en versión 2.0.

**Comment by braulio-evangelisti** [comment]
Lea anda fijandote como va quedando y me vas tirando asi voy corrigiendo sobre la marcha.
Los iconos de las redes sociales los voy a tratar de meter en el header como pediste. Es un poco mas complejo.
Mañana sigo
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Está quedando bueno. Va feedback en base al pedido que te había hecho

1) Estamos bien con ese header. Los links a redes no uses los mismos botones exactamente que los que tiene el blog de Nextperience. Elegí íconos que combinen con nuestra estética, por ejemplo los que usaste en nuestro newsletter.

2) Esto no está, va a estar mañana?

3) 

a) El recuadro está bueno, simplemente ponele un color para que se destaque, puede ser el amarillo del pájaro del logo, pero decidilo en función de lo que quede mejor.

b) Esto quedó perfecto. Necesito que lo hagas funcionar. Pedile a Fede eso.

4) Header negro de abajo: Necesito que diga solamente @2015 Benteveo Agencia Productora.

5) Cambiar la URL del blog a benteveo.tv/blog/ Pedile a Fede cómo hacerlo. La opción de hacerlo en blogger está en Configuración.

ACLARACIÓN GENERAL IMPORTANTE: No quiero que tomes NADA tal cual del blog de Nextperience. Te lo paso como REFERENCIA no como fuente para sacar cosas. Por lo cual todo lo que hayas puesto calcado de ahí (por ejemplo, el botón MÁS naranja, que no tiene nada que ver con nuestra estética) sacalo urgente y reemplazalo por otro que siga nuestra estética. Imagino que fue provisorio que lo hiciste, que no iba a quedar así, pero por las dudas lo aclaro.

abrazo

**Comment by LeandroBraier** [comment]
Sumo un punto más y te aviso que hice agregados en la entrada anterior. abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea

2) Comentame un poco mas como te imaginas los recuadros, si de a 2 por fila, mas chicos, mas grandes, ubicacion de los elementos, etc.

3) b) Esta funcionando, te suscribe al feed del blog y te manda mail cada vez que se sube un artículo nuevo al blog.

5) Me pide que sea una direccion tipo "blog.benteveo.tv" en vez de "benteveo.tv/blog". Tendrian que crear el subdominio desde el cpanel del hosting y avisarme asi lo paso.

OK a todo el resto de los puntos y aclaraciones, te aviso apenas este listo.

Abrazo

**Comment by LeandroBraier** [comment]
2) Brau, espero propuestas de uds para esto. Yo me lo imagino tipo mosaico de imágenes, es un estilo muy habitual en las nuevas web de hoy. Pueden no ser todos GIF animados, concuerdo que no quedaría del todo bien. De todas formas dejemos este punto 2 para la versión 2.0, asi me pasás varias propuestas y lo hacemos bien.

3) b) Buenisimo. Puedo acceder de alguna manera a ese listado de mails para sumarlos a la lista de newsletter?

5) Te lo gestiono y te lo paso.

A qué hora estaría todo el resto salvo el punto 2?

abrazo

**Comment by braulio-evangelisti** [comment]
Ok. Claro el tema de los gifs redondos es muy especifico. Para el mediodia tendria que estar todo listo.

El punto 4 del footer las frases "Plantilla Simple. Con la tecnología de Blogger." Te lo agrega solo, voy a ver si lo puedo eliminar modificando el codigo de la plantilla.

Los suscriptores los vas a poder ver aca: https://feedburner.google.com/ una vez estes logueado con la cuenta de gmail de btv. Tiene la opcion para decargar un excel con las casillas de los suscriptores.

**Comment by LeandroBraier** [comment]
Excelente Brau. Gracias!!!

**Comment by LeandroBraier** [comment]
5) Ya hice los pasos que pide Google hacer. Creo que lleva 24 hs hasta que efectivamente está funcionando. En un día chequeamos.

abrazo grande

**Comment by LeandroBraier** [comment]
Brau, lo veo muy bien ahora al blog. Ya se efectivizó el traspaso de URL también.

Si te parece OK, te pido los últimos detalles de hoy y el resto lo seguimos para la versión 2.0:

1) En el Newsletter, necesito que cambies los links de las 3 notas para que lleven a las respectivas notas del blog.

2) El recuadro amarillo que dice "Benteveo Agencia + Producto y el slogan" necesito que tenga el link a nuestro sitio web también, al igual que el header del blog, que hoy lleve a blog.benteveo.tv

Con esos cambios ya estamos por hoy. Avisame cuando estén porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea. 
Estuvo caido un rato el blog y no podia sacar los links de las notas para ponerlo en el news pero ya estan los dos puntos hechos.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Brau! Quedó muy lindo la verdad. Lo vamos a seguir trabajando pero la versión 1.0 ya está

Detalles que veo en el newsletter:

1) Falta el tilde en "¿está nuestra empresa preparada para hablarle a un Prosumidor?"

2) Falta el tilde en: "...descubrí los próximos pasos para que tu marca no quede afuera en el mundo digital."

3) Falta el tilde en: "Mirá los talentos Argentinos que ganaron."

Hacé esas pequeñas correcciones en el news nomás y tranqui para el viernes pasame la propuesta de cómo implementar el punto 2.

abrazo

**Comment by LeandroBraier** [comment]
Lo del footer que dice Plantilla Simple no lo pudiste sacar no?

**Comment by braulio-evangelisti** [comment]
Listo los tildes.
Si lo del footer inserta todo el bloque, esta como protegido para que no puedas borrarlo si hay un footer puesto.

**Comment by LeandroBraier** [comment]
Mmmm, ok. Dejemoslo así entonces. Gracias Brau!!

abrazo

**Comment by LeandroBraier** [comment]
Buen día Brau, pequeños cambios para el blog:

En el recuadro amarillo: 

a. que diga Benteveo arriba y Agencia + Productora en una segunda línea con tipografía más chica.

b- Agregarle debajo de la frase, el texto "www.benteveo.tv" y que linkee también al sitio.

Confirmame cuando lo tengas porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Hola Lea

Fijate ahi

Abrazo

**Comment by LeandroBraier** [comment]
Está bien pero ponelo debajo de la frase, no arriba. Y en color azul mejor, no rojo.

Gracias!

**Comment by braulio-evangelisti** [comment]
Listo. 
Pense que "la frase" era "Agencia + Productora" en vez del texto de abajo.
Ahi lo pase de lugar y de color.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Brau! Gracias!!

Ya andás mejor de salud?

**Comment by braulio-evangelisti** [comment]
Si por suerte, me guarde bien el finde y ya casi se fue todo jeje gracias por preguntar un abrazo

**Comment by LeandroBraier** [comment]
Brau, te pido un cambio mínimo más nomás y ya cerramos esto.

Necesito que le agregues la posibilidad de dejar comentarios en los posteos. No lo quiero hacer yo en blogger por si te cago algo del diseño que customizaste.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! Una cosita más: FIjate que el link a la web de benteveo al pie del recuadro amarillo está mal. Lleva a: http://blog.benteveo.tv/www.benteveo.tv

**Comment by braulio-evangelisti** [comment]
Corregido.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! Queda cerrado esto por ahora. Tené en el tintero lo otro que nos quedó de los mosaicos para la versión 2.0

abrazo

**Comment by LeandroBraier** [comment]
Pequeño detalle Brau. Es posible que en la home hagas que solo se muestren 3 artículos de blog por vez? Ahora por ejemplo subimos 3 nuevos artículos y se ven 6 en total.

**Comment by braulio-evangelisti** [comment]
fijate ahora

**Comment by LeandroBraier** [comment]
Perfecto Brau. ya quedó seteado así de ahora en más?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Asi es, va a mostrar 3 entradas por página solamente

**Comment by LeandroBraier** [comment]
Perfecto, gracias Brau!
