### ISSUE TITLE
Ultimos trabajos/ Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#74]
@braulio-evangelisti necesito subir el trailer de la peli Francisco la pelicula en la pagina de Benteveo.

Para eso vamos a subirlo a Vimeo. Lo que voy a necesitar es:

1) Que en Últimos trabajos aparezca este ultimo video subido a Vimeo.

2) Que al pie del video, donde ahora dice Corro con Jonas, se lea lo siguiente:

"Francisco, el padre Jorge" -Trailer Oficial-

3) Un link directo que me lleve a esa sección de "últimos trabajos" (el link de "Volando" que hay en el menú me lleva al reel.

Para qué hora lo podrías tener a esto?

Consultá con @FAAREIA ante cualquier duda sobre cómo esta maquetado eso.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea mañana a la mañana lo puedo hacer a esto.

Pasame el link del video en vimeo cuando lo tengas.

En el punto 3 seria agregar un link nuevo en el menu es correcto?

**Comment by LeandroBraier** [comment]
No hace falta que en el menu este el link. Lo que necesito es una url para poner en un mail que lleve directo a la sección de ultimos trabajos. 

Mañana a la mañana bien temprano está bien. Gracias!

**Comment by LeandroBraier** [comment]
Brau, ya tengo el link del video. Te paso link y embed:

https://vimeo.com/138124275/

`<iframe src="https://player.vimeo.com/video/138124275" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

**Comment by braulio-evangelisti** [comment]
Lea ya lo tengo hecho en local a esto. Estoy sin luz hasta las 10, estoy saliendo para algun bar asi lo subo.

**Comment by LeandroBraier** [comment]
Gracias Brau!!! Se agradece muchísimo el esfuerzo, se lo voy a comentar a
Eze. abrazo grande

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Listo Lea ahi subio.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! Quedó muy bien. Ahora necesito el link directo porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahi va

http://benteveo.tv/#ultimos-trabajos

**Comment by LeandroBraier** [comment]
Gracias Brau!! Ahora si!!
