### ISSUE TITLE
Agregado de sección a Web Benteveo. 22/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#75]
Fede, necesito sumar una sección a la web, que es el área de cine. La estructura es idéntica a la de Entretenimiento + Comunicación. Se ubicaría después de últimos trabajos y antes de Contacto

TÍTULO: Cine + Entretenimiento

TEXTO: 

El texto incluye algo que dice: Nos interesa recibir proyectos bla boa

Desde un principio el corazón de Benteveo siempre estuvo en la producción audiovisual. Realizamos largometrajes, programas de tv, spots publicitarios, contenidos de video online, proyecciones en 3D, video en 360º y mucho más. Lo hacemos con gran pasión y oficio y con un equipo de larga trayectoria en el cine argentino.

Nuestros últimos largometrajes fueron Amor a Mares (2013), El Inventor de Juegos (2014) y Francisco, el padre Jorge (2015). Para todos ellos no solo participamos en la producción del filme sino en acciones creativas y audiovisuales de comunicación de su lanzamiento.

Hoy en día seguimos produciendo y pensando nuevos proyectos, así como recibimos cotidianamente propuestas del gran ecosistema creativo que tiene nuestro país. Si tenés un proyecto y te gusta lo que hacemos, aquí tenés un espacio para presentárnoslo.

FOTOS (acomodales el tamaño si te es necesario para que queden homogéneas, pero yo busqué eso):

http://www.abasto-shopping.com.ar/mundoabasto/wp-content/uploads/2012/11/amor-a-mares-en-todos-los-cines-499x288.jpg

http://andresgabrielli.com.ar/wp-content/uploads/2014/07/el-inventor-de-juegos.jpg

http://1.bp.blogspot.com/-TB5nKOIV7O8/VbJpRrl6IqI/AAAAAAAAPik/Rgljg3oXDG8/s320/691x295_francisco_4932.jpg 
o esta:
https://i.vimeocdn.com/video/533431714_640.jpg

Misma plantilla que Entreteniiento + Comunicación, con 3 fotos de las pelis: Amor a mares, El inventor de Juegos, Francisco el padre Jorge

BOTÓN: Al pie del texto va un botón que dice: "Envianos tu proyecto"

AL hacer clic se abre un pop up con un formulario que se reenvia a cine@benteveo.tv

El Formulario se llama "Ficha de tu proyecto" y tiene las siguientes entradas:

Titulo original:
Autor/es:
Num. deposito de registro de propiedad intelectual:
Fecha del registro:
Genero:
Storyline (5 lineas)
Sinopsis (1 pag max)
Definir el atractivo del proyecto: (3 lineas mas)
Nº de páginas:
CV director: (aquí se sube un PDF o DOC)
CV autor: (aquí se sube un PDF o DOC)
Comentarios:

abrazo

pd: No es prioridad, pongo fecha del 22/09 por eso. Cualquier cosa lo hablamos.

**Comment by braulio-evangelisti** [comment]
Lea el campo sinopsis seria un campo de texto muy grande o un boton como los de cv para subir un doc de una pagina maximo?

**Comment by LeandroBraier** [comment]
Un campo de texto grande pero no más de 500 caracteres.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Fijate ahi una primer pre-version, falta trabajar el form y hacerlo andar todavia pero asi se va viendo y vamos depurando de entrada.

http://benteveo.tv/index-cine.html

Abrazo

**Comment by LeandroBraier** [comment]
Está perfecto. Solo quitale la frase de arriba chiquita "Nos interesa recibir proyectos..." que fue un error mio, una linea de más en el pedido que te hice.

abrazo

**Comment by braulio-evangelisti** [comment]
listo

**Comment by LeandroBraier** [comment]
Genial. Poné que donde dice "Fecha" haya un calendario de fecha para elegir
como en Rio Ancho y en "Número de páginas" que sólo se puedan escribir
números.

Después de eso mandame a mi mail una muestra de como sale el formulario
porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Ya le agregue el datePicker a fecha y el campo paginas lo pase a numérico.

Habría posibilidad de consultar con quien haya programado el sitio si ya hay alguna librería para envío de mails o esta contemplado de alguna forma?

**Comment by LeandroBraier** [comment]
Gracias Brau! Consultalo con Fede a eso que sabe.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-22 18:25 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Perfecto. Te aviso cuando este listo.

Abrazo

**Comment by braulio-evangelisti** [comment]
Lea ya que el form envia un par de archivos adjuntos me confirmo Fede que habria que hablar con el programador

@mkreyness

**Comment by LeandroBraier** [comment]
Genial, Brau. 

MK, decinos qué necesitás de nosotros para avanzar acá.

abrazo

**Comment by mkreyness** [comment]
Donde esta el form asi lo miro ?

**Comment by braulio-evangelisti** [comment]
http://benteveo.tv/index-cine.html#cine -> "Envianos tu proyecto"

**Comment by mkreyness** [comment]
O sea tiene un par de adjuntos, cual es la idea Lean, que los adjuntos vengan en el mail o que queden almacenados en un repositorio y en el mail venga un link ?  A que direccion tiene que llegar ?
Tambien esto es una puerta abierta a robots que metan archivos con todo tipo de virus les aviso.

**Comment by LeandroBraier** [comment]
Ok, MK.

Esto tiene que ser igual que como fue el casting de Benteveo te acordás?
Tal cual. Repositorio y link en el mail que llega a info@benteveo.tv

La limitación a los virus es que el formulario debe estar completo si o si
para poder enviarse. No puede faltar nada.

Si se pudiera limitar los archivos que pueden adjuntar solo a PDF o .doc de
un máximo de 3 mb de tamaño sería ideal también.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-23 9:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok, lo que pasa es que el casting creo que se hizo desde el servidor viejo de Benteveo, que estaba super cerrado a todo, aca es un entorno mas abierto y por lo tanto mas expuesto.
En teoria se puede limitar pero depende del browser respetar o no esas limitaciones, y justamente los robots que inyectan viruses no son precisamente respetuosos.
Para cuando tiene que estar esto ?

**Comment by mkreyness** [comment]
Pregunta: no se le pide un email al que carga esto, asi que por lo tanto tampoco se le manda una confirmacion de que fue recibido, ok ?

**Comment by mkreyness** [comment]
Ya quedo implementado en el boton enviar de ESTE html:

http://benteveo.tv/index-cinemk.html

No te pise el otro porque no sabia si estabas trabajando.
Si no cambiaste nada, directamente reemplazalo por este.
Si lo tenes que combinar, fijate los cambios que hice en el encabezado del form y en los elementos de tipo   input type="file" para forzar el tipo de archivos que queremos (igual eso no asegura nada contra los virus).

**Comment by braulio-evangelisti** [comment]
Perfecto. 
No, de mi parte el ultimo cambio lo hice ayer asi que el html que agarraste hoy tenia lo ultimo.

**Comment by LeandroBraier** [comment]
Excelente chicos!

Solo agreguenle al formulario que cargue una dirección de mail, como sugiere MKKreyness.

Con eso ya estamos.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo el campo mail.

**Comment by mkreyness** [comment]
No es realmente "email del autor", yo diria ponerle "email de contacto", lo modifico yo, no te preocupes.

**Comment by LeandroBraier** [comment]
Gracias MK! Ya se lo mandé a Eze, a ver qué dice.

**Comment by mkreyness** [comment]
ojo falta programar que incluya ese email en el texto y la idea seria que le mande en el mismo momento una confirmacion de que recibimos sus datos y archivos, no ?

**Comment by LeandroBraier** [comment]
Si tal cual.

**Comment by mkreyness** [comment]
listo ya complete eso.

**Comment by LeandroBraier** [comment]
Gracias MK!! Espero la aprobación de Eze y les aviso.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA Está OK este agregado!

Simplemente les pido que pongan en negrita la siguiente frase del texto: "Si tenés un proyecto y te gusta lo que hacemos, aquí tenés un espacio para presentárnoslo.”

Con ese detalle modificado ya subanlo a producción directamente.

abrazo

**Comment by LeandroBraier** [comment]
Chicos, apenas puedan subanlo a producción por favor.

**Comment by FAAREIA** [comment]
Fijate ahora lea, dale F5 y confirmame si esta todo OK.
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede. Está ok pero le falta la negrita que te pedí. FIjate arriba,
la última frase del texto antes del botón va en negrita.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi va

**Comment by LeandroBraier** [comment]
Perfecto, gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA el formulario no está funcionando.

Te paso captura de lo que está llegando al mail de Benteveo.

<img width="570" alt="captura de pantalla 2016-02-10 a las 12 05 37 p m" src="https://cloud.githubusercontent.com/assets/6719872/12950490/37b61ae0-cfec-11e5-9915-ed5da2b25ef7.png">

Te fijás qué puede ser?

**Comment by LeandroBraier** [comment]
@FAAREIA vos estás probando?

Eze está recibiendo pruebas vacias como las que te pasé pero en tandas de a 5 o 6 seguidas. Yo hice 1 sola prueba.

**Comment by FAAREIA** [comment]
No estoy probando ni estuve.
Ahora lo chequeo

**Comment by FAAREIA** [comment]
De que evento es ese formulario de contacto?
URL de la landing?

**Comment by LeandroBraier** [comment]
http://benteveo.tv/#enviar-proyecto

**Comment by FAAREIA** [comment]
Ahora voy a ver de ponerle un captcha.

**Comment by LeandroBraier** [comment]
Gracias Fede. Igual lo importante es que el formulario llega vacío y ojo
que yo puse enviar una sola vez y llegaron 7 mails. Son problemas de como
está funcionando el formulario no del spam en el uso.

**Comment by FAAREIA** [comment]
El formulario debe llegar vacio porque un robot se mete y lo manda como si nada. Si bien los campos son obligatorios, esto robots no entran desde un navegador moderno a los sitios. Un captcha los pararía.
Lo de que se envio 7 veces con solo click recien ahora lo entendí, voy a verlo, sino le digo a marce.

**Comment by LeandroBraier** [comment]
Dale, ahora entiendo. Perfecto, gracias!

**Comment by FAAREIA** [comment]
Bueno, ahi estuve revisando todo y la verdad no encontré nada anormal en el código que enviá el formulario ni nada.
Lo que si ahora el formulario tiene un captcha que por ahora no funciona al enviar.
@mkreyness 
- Ver si se puede reproducir el error de que cuando envias 1 formulario, llegan 7 mails replicados.
- Ver si el bug puede ser algo relacionado a los archivos adjuntos. Éste item es un supuesto mio nomás
- Impementar el captcha en el código del formulario. [Ver documentación online](https://www.phpcaptcha.org/documentation/quickstart-guide/)
- Las primeras 14 líneas del archivo `/cine/email-cine.php` corresponden a lo que intenté implementar del captcha pero la verdad es que el formulario no me dio bola y me tiro un mensaje de satisfactorio a pesar de que el captcha estaba mal. El formulario si estaba bien completado.

**Comment by LeandroBraier** [comment]
@FAAREIA Recibido OK la nueva prueba!!

Te paso captura:

<img width="516" alt="captura de pantalla 2016-02-11 a las 10 36 49 a m" src="https://cloud.githubusercontent.com/assets/6719872/12977333/dfb18d08-d0a8-11e5-9d10-81cdd86b1d38.png">

Creo que ahora está funcionando bien, no sé si falta corregir algo más. Avisen nomás.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no comenté antes porque estaba a full con lo de Revear. Este último tema no esta solucionado. Hay que implementar el captcha asi no llegan mails vacios.
@mkreyness revisate mi comentario anterior: https://github.com/LeandroBraier/BenteveoTV/issues/75#issuecomment-182855057

**Comment by mkreyness** [comment]
cual es el URL en uso de todo esto ?

**Comment by FAAREIA** [comment]
es el sitio de Benteveo TV en la parte de cine, hay un botón que levanta un modal con el formulario.

**Comment by mkreyness** [comment]
la documentacion del captcha dice que la primera linea del php debe decir esto:

`<?php session_start(); ?>`

y no veo que este puesto, lo probaste y no andaba ?

**Comment by FAAREIA** [comment]
Si lo probé y nada, como que no lo interrupia al código

**Comment by FAAREIA** [comment]
Lo reabro porque esto no fue resuelto. Esta mezclado el issue pero no importa.
@mkreyness fijate si podes aplicar lo del captcha al formulario ese. Cualquier cosa lee desde [aca](https://github.com/LeandroBraier/BenteveoTV/issues/75#issuecomment-182855057)

**Comment by LeandroBraier** [comment]
@FAAREIA en qué quedó esto?

**Comment by FAAREIA** [comment]
Quedó en la nada. Capas que en este issue estaría bueno involucrar a la persona nueva asi marce no anda con mil cosas al mismo tiempo

**Comment by LeandroBraier** [comment]
Ok, veanlo entre uds porfa. Necesito que funcione el formulario lo antes
posible. Nos sigue llegando mails con formularios vacíos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-09 14:14 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Los pongo en contacto con Amalia y le explican ustedes directamente ? Si no yo estoy en el medio y es lo mismo. El tema es que yo hasta ahora no le di acceso al servidor, siempre me mando las cosas a mi y yo las instale.

**Comment by FAAREIA** [comment]
Si dale, pasale el link de este issue pero [desde aca](https://github.com/LeandroBraier/BenteveoTV/issues/75#issuecomment-182855057)

**Comment by mkreyness** [comment]
Ahi le pase por mail el link, supongo que para agregarla aca al thread lo tiene que hacer Leandro.
Su direccion es amalia_garcia82@hotmail.com

**Comment by LeandroBraier** [comment]
Como es su usuario MK? Así la busco por el usuario y la agrego.

**Comment by mkreyness** [comment]
Usuario de github ? Ni idea, capaz no tenga. Veremos si puede acceder al link que le mande.

**Comment by LeandroBraier** [comment]
Entonces hablalo vos con ella Marce, ella es tu junior. Derivaselo como te
parezca mejor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-09 16:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ya le mande mail, pero si me tengo que poner a buscar los elementos y mandarselos y recibirselos hago mas rapido en arreglarlo yo ! La idea es que puedan trabajar con ella directamente sobre todo para estas cosas aisladas.

**Comment by LeandroBraier** [comment]
Ok, entonces Fede comunicate vos con ella puede ser? Para estas cosas más
simples.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-09 16:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
ahi le mando un mail para decirle que cualquier cosa me pregunte

**Comment by FAAREIA** [comment]
Ya esta funcionando el captcha

**Comment by LeandroBraier** [comment]
Gracias Fede! Probaste ahora si el formulario ahora carga los datos? Sino yo pruebo, pero tené en cuenta que si Eze vuelve a recibir un formulario vacío por mail vamos a estar igual que al principio. Pudiste confirmar por qué llegaban vacíos? Me suena que no es solo el capcha.

**Comment by FAAREIA** [comment]
El formulario ya lo probé y con el captcha mal tira error y con el captcha bien lo manda.
Imagino que recibian el formulario vacio porque un robot enviaba el formulario pero al no poder reproducir el envío vacio del formulario no puedo solucionarlo.
Si vuelve a pasar vemos pero ahora que esta el captcha dudo que suceda.

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Ahí acabo de probar. Dos detalles:

1) Vos decís que si da error el captcha le aparece el mensaje igual pero el formulario no llega? Si pone mal el captcha le debería decir: "Captcha incorrecto" y que lo complete bien.

2) Estoy viendo una sección de la web que ya no funciona bien. Tiene que ver con el mail que mandó MK a Duplika hoy?

<img width="1003" alt="captura de pantalla 2016-03-14 a las 9 46 24 a m" src="https://cloud.githubusercontent.com/assets/6719872/13744573/59d0264e-e9c7-11e5-8a3f-2058a26fa0a1.png">

**Comment by FAAREIA** [comment]
Hola Lea, ahi ya cambié el texto del mensaje de error.
Con respecto al sitio, lo veo todo perfecto. Habrá sido una mala conección con instagram o un error porque te tardó mucho en cargar, dudo que sea algo del hosting sino se verían varias cosas rotas.

**Comment by LeandroBraier** [comment]
@FAAREIA testeaste el formulario? Quedó funcionando bien al final?

**Comment by FAAREIA** [comment]
Si, cuando lo probé mandaba con el captcha correcto y no mandaba si el catpcha era incorrecto. Si queres testealo una última vez asi te quedas tranquilo

**Comment by LeandroBraier** [comment]
Gracias Fede! Ahi lo testeé y estoy esperando que Eze me confirme si recibió todo bien. Igual probé con capcha malo y cuando falla me obliga a subir todo de nuevo, no hay forma de evitar eso? Digo, que el error del captcha sea dentro del mismo formulario?

**Comment by FAAREIA** [comment]
Si pasa eso, habría que pasarselo a amalia nuevamente si queremos que sea diferente ya que la forma de enviar los mails que siempre usamos funciona asi, se envia el form y recien ahi te dice bien o mal, no te lo hace en el momento para luego enviarlo o no.

**Comment by LeandroBraier** [comment]
Perfecto, entonces dejemoslo así. Cuando Eze me confirme que le llegó bien cierro el ticket.

abrazo

**Comment by LeandroBraier** [comment]
Funciona joya Fede!!! abrazo grande
