### ISSUE TITLE
Newsletter Benteveo de Septiembre. 18/9

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#76]
@braulio-evangelisti necesitaría que diseñes este news para mañana. Es la misma estética que el de agosto pero nuevos contenidos. LO único que falta hacer (porque no lo pude hacer yo) es convertir en círculos los GIFs.

https://docs.google.com/document/d/1BbEQjwa-kZNfRelnEgZPCf7mXcdFXVeqo-f1Gh9aoyA/edit

Los links van a estar mañana a la tarde. SI mañana a la tarde ya lo tenés cuando te los pase los subís y ya queda. 

Decime si necesitás algo más.

abrazo

**Comment by braulio-evangelisti** [comment]
Perfecto Lea. Si podes enviame los gifs por mail o subirlos a algun lado si son muy pesados que no encuentro como bajarlos del google doc. 
Mañana temprano reviso bien si falta algo mas.
Abrazo

**Comment by LeandroBraier** [comment]
Dale, ahi te los envio.

abrazo y gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-17 23:12 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
Brau, esto podrá estar para la tarde?

**Comment by braulio-evangelisti** [comment]
http://www.benteveo.tv/mailing/septiembre/

Me falta la imagen de la 3° nota, mandamela por separado por favor.

**Comment by braulio-evangelisti** [comment]
Listo ahi subi la 3er imagen

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Quedó muy bueno.

Te paso los links
http://blog.benteveo.tv/2015/09/tu-marca-me-emociona-el-caso-jonas.html
http://blog.benteveo.tv/2015/09/ahora-pauta-en-todos-los-canales.html
http://blog.benteveo.tv/2015/09/por-que-google-y-facebook-cambiaron-sus-logos.html

Y te pido un par de cambios de texto. 

En nota 2, donde dice:

"Cada vez son más las herramientas que existen para que tu publicidad llegue a su objetivo y las marcas puedan alcanzar las audiencias reales de interes. Sin embargo, hasta el momento cada anunciante debía recurrir en forma individual a un mainstream channel o a una agencia especializada para poder pautar en cada tipo de plataforma. 
Desde hoy, gracias a una iniciativa inédita en Latinoamérica, nace una nueva forma de publicitar en medios en Argentina y en distintas plataformas a la vez. 
Competencia a Google? Tiembla Facebook? Averigualo

Cambialo por:

"Cada vez son más las herramientas que existen para que tu publicidad llegue a su objetivo y audiencia pero ahora, por una iniciativa inédita en Latinoamérica, nace una nueva forma de publicitar en medios en Argentina y en distintas plataformas a la vez. ¿Tiemblan Google y Facebook? Averigualo" 

En nota 3, donde dice:

"Ya viste el nuevo logo de Google y Facebook? El avance de todo lo "mobile" llegó a tal punto con el concepto responsive (en pocas palabras un diseño versátil que se adapta o todo tipo de dispositivos) que dos gigantes como Google y Facebook comenzaron una batalla por el diseño de mejor llegada y lectura para estas tecnologías dinámicas. Modificando su logo apostaron ambas así a una estética estilizada, minimalista y, sobre todo, más amigable."

cambialo por:

"¿Ya viste el nuevo logo de Google y Facebook y no entendés a qué viene? El avance de todo lo "mobile" llegó a tal punto que dos gigantes como Google y Facebook comenzaron una batalla por el diseño de mejor llegada y lectura para todo tipo de dispositivos. Enterate qué hay detrás de este polémico cambio."

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea.

Abrazo

**Comment by LeandroBraier** [comment]
Impecable Brau. Gracias!

**Comment by LeandroBraier** [comment]
Pequeño pedido, Brau. 

Donde dice "¿Necesitás asesoramiento o querés consultarnos algo?" 

Cambialo a que diga:

"¿Necesitás ideas o querés consultarnos algo?"

abrazo

**Comment by braulio-evangelisti** [comment]
Hecho
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti !

Pedidos de cambio de texto muy simples, en función de que ayer ganamos el Oro en los Premios Obrar y estamos chochos. 

Porfa corregilo hoy sin falta así lo podemos mandar

DONDE DICE

Las últimas investigaciones científicas demuestran que las marcas que emocionan son las más recordadas por los consumidores. Mirá el video de esta campaña que hicimos y enterate por qué.

REEMPLAZAR POR

Según una investigación las marcas que eligen la emoción como parte de su comunicación son las más recordadas. Mirá esta campaña que ganó el Oro en los Premios Obrar 2015 para entender por qué.

DONDE DICE

Cada vez son más las herramientas que existen para que tu publicidad llegue a su objetivo y audiencia pero ahora, por una iniciativa inédita en Latinoamérica, nace una nueva forma de publicitar en medios en Argentina y en distintas plataformas a la vez. ¿Tiemblan Google y Facebook? Averigualo

REEMPLAZAR POR

Nace una nueva forma de publicitar en medios masivos y en distintas plataformas. Descubrí una solución centralizada y pensada para impactar directamente en la mayor cantidad de consumidores.

DONDE DICE

¿Ya viste el nuevo logo de Google y Facebook y no entendés a qué viene? El avance de todo lo "mobile" llegó a tal punto que dos gigantes como Google y Facebook comenzaron una batalla por el diseño de mejor llegada y lectura para todo tipo de dispositivos. Enterate qué hay detrás de este polémico cambio.

REEMPLAZAR POR

¿Ya viste el nuevo logo de Google y Facebook y no entendés a qué viene?  Enterate qué hay detrás de este polémico cambio.

abrazo y gracias!

**Comment by braulio-evangelisti** [comment]
oh si, felicitaciones!

Actualiza la news que ya apliqué los cambios.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto BRau!! Gracias!!

abrazo
