### ISSUE TITLE
Resolver el Misterio de Nisuta

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#77]
En la produ.

**Comment by ghost** [comment]
Cuando vaya a revisar los monitores me fijo

**Comment by ghost** [comment]
Hice un monitoreo de las redes, vi que la gran mayoria de las redes cercanas estaban en el canal 1 y en el canal 11, por lo tanto, puse al nisuta en el canal 8. La velocidad de descarga fue de 18 Mbits
Hay que probar con todas las maquinas conectadas a ver si no es un tema de que se satura la memoria del router. 

![image](https://cloud.githubusercontent.com/assets/16599421/12521548/f21cbf00-c129-11e5-8743-94e041465bd8.png)

**Comment by LeandroBraier** [comment]
Sos un genio Valentin!!!! El lunes la probamos por las dudas, pero confio
en que encontraste el problema.

abrazo y gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-22 17:04 GMT-03:00 valentinsabbath notifications@github.com:
