### ISSUE TITLE
Intervención en Archivo 360º MSC

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#78]
Buen día @FAAREIA ! Necesito que me confirmes esto.

MSC, un cliente nuestro, quiere que editemos esta página 360º agregando gráficos e íconos. Podemos hacerlo?

http://mscpodcast.msccruises.com/Podcast/VirtualTourMusica/ar_es/index.html

A mi me da la sensación que es un archivo flash por lo cual no podemos pero espero tu confirmación.

**Comment by FAAREIA** [comment]
Hola Lea, es un archivo flash y esta combinado con otro programa/plugin que no conozco:  http://krpano.com/

**Comment by LeandroBraier** [comment]
Es un viewer ese, pero está pensado tanto para Flash como para HTML5. Lástima que lo hicieron en Flash.

**Comment by FAAREIA** [comment]
Si pero no creo que haya otra opción. Capas que hoy en día si se pueden combinar varios plugins y rearmar algo similar pero no funcionaría en todos los dispositivos y navegadores.

**Comment by LeandroBraier** [comment]
Entiendo. Ya le respondí a Eze entonces.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA me pasaron una especie de editables y un instructivo.

http://www.msccrucerosargentina.com/mails/2014/VtourMusicaClass_ID6624_1CE6CD5D03.zip

[Offline_navigation_instructions.pdf](https://github.com/LeandroBraier/BenteveoTV/files/138702/Offline_navigation_instructions.pdf)

Necesito nomás que me digas si con esto podemos meter alguna gráfica dentro de la navegación.

abrazo

**Comment by FAAREIA** [comment]
Si hay un editable y un instructivo es muy muy probable que se puedan agregar cosas. Lo que habría que hacer es consultar este tema con alguien que la tenga clara con flash ya que el archivo y lo hecho se ve bastante complejo.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

Consulto con un diseñador que tenemos que sabe trabajar Flash. abrazo grande
