### ISSUE TITLE
Primeros Templates para Siguit Digital Signage PARA EL LUNES

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#79]
@FAAREIA cómo andás?

Estamos desarrollando un sistema de cartelería digital con @mkreyness y necesitamos hacer una serie de templates estéticos para distintas industrias a las cuales podríamos venderles el servicio.

Te paso acá un documento que armamos con el perfil de cartelería digital que requieren 5 industrias.

[Referencias para templates Siguit DS (1).pdf](https://github.com/LeandroBraier/BenteveoTV/files/145774/Referencias.para.templates.Siguit.DS.1.pdf)

Está pensado para que trabajemos en base al modelo de 4 o 5 industrias (Inmobiliarias, Centros Comerciales, Heladerías, Hotelerías, etc). Lo que necesitamos es el mock up de como quedaría cada una, puede ser un Photoshop nomás.

Cualquier duda escribime, no te quiero cargar de info al cuete. Por las dudas acá tenes una presentacion provisoria del producto.

[SIGUIT DS.pdf](https://github.com/LeandroBraier/BenteveoTV/files/145775/SIGUIT.DS.pdf)

**Comment by FAAREIA** [comment]
Resolución 1920x1080?
Cuanto más grande más cómodos vamos a estar para poner la info

**Comment by LeandroBraier** [comment]
Si, esa sería la resolución.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-25 10:29 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lea, no creo que lleguemos para el lúnes teniendo en cuenta lo de Bayer y lo del nuevo diseño de newsletter. Hbaría que hacerlo para otro día de la semana que viene, diría que para el viernes seguro si no hay ninguna otra urgencia

**Comment by LeandroBraier** [comment]
Está bien Fede. Esto no es prioridad frente a Bayer y al diseño de
newsletter asi que me parece bien. Gracias!

**Comment by FAAREIA** [comment]
Ahi va el primero: Inmobiliaria
![inmobiliaria](https://cloud.githubusercontent.com/assets/6184969/13493474/18e9351a-e11d-11e5-865f-94c27d724cba.png)

**Comment by LeandroBraier** [comment]
Excelente Fede!! Muy bueno!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-03 8:52 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hoteles

![hoteles](https://cloud.githubusercontent.com/assets/6184969/13529933/7cdba022-e1fd-11e5-94da-8c2abe1be1b2.png)

**Comment by FAAREIA** [comment]
Lea, estuve tratando de hacer algunos otros modelos y me faltaría data más precisa.
Por ejemplo en salud hay varios modelos, ¿qué les interesa mostrar? ¿turnos? ¿solo la empresa?
En comidas lo mismo: ¿qué les interesa mostrar? ¿promociones? ¿especiales? ¿listado de precios?

**Comment by LeandroBraier** [comment]
Para Salud podemos tener el de Bayer. Fijate si podés adaptar algo parecido para un Farmacity ponele.

En cuanto a comidas te paso la referencia del cliente de Digital Signage de heladerías que ya tenemos, para que tomes de referencia:

https://drive.google.com/drive/folders/0B_6ywYX9PGKLdXRUUnp5NkE1Ums

Decime si te sirve.

abraoz

**Comment by LeandroBraier** [comment]
Muy bueno este de Hoteles eh!

**Comment by FAAREIA** [comment]
Perfecto, justo estaba haciendo el de Heladería.
El ejemplo de bayer no lo veo en el PDF, me lo mandarías?

**Comment by LeandroBraier** [comment]
Es el que hiciste vos mismo! En este ticket:

https://github.com/LeandroBraier/Bayer/issues/1

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ah joya y donde estan las novedades+transitio pongo los servicios ofrecidos? lo del tiempo lo cambio por un texto introductorio?
Osea que de datos en el de salud, habría un texto introductorio y un listado de servicios y/o productos con descuento capas

**Comment by LeandroBraier** [comment]
En salud no. Dejá lo del clima y las noticias y dejá el video. Solo agregá
algo destacado que muestre los turnos ponele, como que es gente esperando
para entrar al médico y listo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-04 12:36 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi va heladería

![heladeria](https://cloud.githubusercontent.com/assets/6184969/13570077/d4922fbc-e44a-11e5-973c-a0826fb202f5.png)

Abrazo

**Comment by LeandroBraier** [comment]
Buenísimo Fede!! El video quedaría de fondo no?

**Comment by FAAREIA** [comment]
Si puede ser una foto o un video, la data no se veria afectada por uno u otro

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi va salud, lo modifiqué un poco asi "Turnos en curso" tenía más presencia.
![salud](https://cloud.githubusercontent.com/assets/6184969/13605365/fe4c5388-e525-11e5-8587-81a251c6af96.png)

**Comment by FAAREIA** [comment]
Faltaría el de restaurantes no?

**Comment by LeandroBraier** [comment]
No hace falta Fede!! Dejemoslo asío por ahora. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
