### ISSUE TITLE
Agregar Logo de FUCA en sección Sustentabilidad

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#8]
No es urgente. Te pasé el logo recién por mail.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_btv10/

**Comment by LeandroBraier** [comment]
Gracias. Dejalo centrado hasta que vengan más y ya está.

abrazo

**Comment by FAAREIA** [comment]
Listo Lea:
http://www.benteveo.tv/_btv10/

**Comment by LeandroBraier** [comment]
Perfecto, podés subirlo a la web actual. Gracias! cerrado.
