### ISSUE TITLE
Investigación de nuevos lenguajes. 28/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#80]
@faareia Eze estuvo viendo 2 tecnologías que se vienen en lo que es lenguajes web:

Accelerated Mobile Pages: https://www.ampproject.org/

y Progressive Web Apps https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/

Fede, cuando puedas investigate un poco estas y decime si te parece que podemos ofrecerle a nuestros clientes actuales o a nuevas algun update en este sentido.

Si es así, decime qué cambios nos implicarían en los desarrollos que estamos haciendo y si va a ser necesario adaptar algo de lo que ya tenemos armado. También si nos permite hacer nuevas cosas o nuevas propuestas.

abrazo

**Comment by FAAREIA** [comment]
Se puede aplazar esto? No creo que llegue con todo lo que hay para hacer

**Comment by LeandroBraier** [comment]
Obvio que si, todo bien.

**Comment by LeandroBraier** [comment]
@FAAREIA Esto te lo paso para después de la primera semana de mayo, después de Revear.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA revivo este tema y actualizo el ticket. Para el viernes fijate si podés echarle un ojo y responderme las consultas. abrazo

**Comment by FAAREIA** [comment]
Estuve viendo lo de AMP y esta bueno pero me parece que es para proyectos de público masivo como un diario. Por supuesto que puede aplicarse a cualquier tipo de proyecto pero tiene su propio lenguaje de como armar el HTML y algunas cosas poco prácticas que son asi para lograr una "optimización absoluta" de todos los elementos del HTML renderizado.

El otro aún no pude verlo

**Comment by LeandroBraier** [comment]
Genial @FAAREIA Justo MS nos pasó este link hace un rato: https://www.ampproject.org/learn/about-amp/

Creés que podrás implementarlo a nuestros mailings? Sería ideal, porque desde Klaukol (no newsletter, sino los otros) nos están pidiendo rediseñarlos para el año que viene.

**Comment by FAAREIA** [comment]
El tema del AMP es que uno tiene que escribir el HTML de cierto modo y luego un script hace y reemplaza todo lo necesario. En los mailings no hay forma de incluir un script y busqué a ver si había algo especial pero no hay nada.

**Comment by LeandroBraier** [comment]
OK, entonces tengamoslo en cuenta para la nueva web de benteveo que se
viene.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2016-12-05 17:02 GMT-03:00 Federico Arena <notifications@github.com>:
