### ISSUE TITLE
Landing Cachafaz 22/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#81]
@FAAREIA para mañana necesitaría que me armes una nueva landing como esta:

http://mr.benteveo.tv/bowen-london/

1) La marca en este caso sería cachafaz, es decir que la URL sería:

/cachafaz/

2) Quitale la frase de arriba de todo: "Así mejoramos el posicionamiento de tu marca"

3) Reemplazá el video que aparece ahí por este:

https://vimeo.com/163736724/

El embed es este:

`<iframe src="https://player.vimeo.com/video/163736724" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

Confirmame mañana porfa si lo podés tener mañana.

abrazo

**Comment by FAAREIA** [comment]
http://mr.benteveo.tv/cachafaz/
No puse el embed, pase el video a html5 porque acordate que al final aparecian unos botones clickeables.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Fede! Mil gracias!

abrazo grande
