### ISSUE TITLE
Pedido 360 de nuevo prospect en Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#83]
@mkreyness un nuevo prospect que estamos pitcheando en Chile nos pide un Video 360º (que sabemos como hacer) pero embebido dentro de una aplicación que le permita hacer play, pausa, retroceder y adelantar. De qué manera te parece mejor hacerlo?

A mi se me ocurre una web en locked up browser o una aplicación web HTML5 aprovechando el Construct. Qué decís?

Es solo para saber cuál sería la mejor forma, poder calcular tiempos y estimar costos para presupuestar. No es que hay que hacerlo si o si, es un pitch.

abrazo

**Comment by mkreyness** [comment]
El asunto es tener el player que lo permita ver y que funcione dentro de ese browser. A mi algunos pocos videos 360 me funcionan bien en Youtube desde Chrome y otros (la mayoria) no.
Usar el construct no le veo sentido, salvo que sea para algo del resto de la aplicacion. En realidad todo depende de eso, con que lo tenes que integrar. Porque hacer una pagina HTML5 con un youtube player con controles es trivial.

**Comment by LeandroBraier** [comment]
Ah, genial. Me quedo más tranquilo entonces. No tenemos muy claro cuál es el pedido. Por momentos nos parece que nos están hablando de Realidad Virtual incluso, cuando sepa algo más te aviso.

Trivial es un par de hs nomás y lo puede hacer Fede solo?

**Comment by mkreyness** [comment]
Por eso te digo, depende de la integracion con el resto de la aplicacion, si por moverse dentro del video 360 hay que interactuar con otras cosas, sonamos (con Construct o lo que sea, hay que ir a otra plataforma mas especifica y seguramente que requiere un muy buen hardware), ahora si es solo poner un video de youtube embedded, si, eso lo puede hacer Fede.

**Comment by LeandroBraier** [comment]
Claro pero el tipo no quiere hacer clic en un Play en la pantalla. Quiere
un control remoto desde donde pueda hacer play, pause, rewind, forward. Eso
implica interacción con el teclado o dispositivo de entrada que usemos no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-05-05 18:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero  para moverte dentro del video 360 tendrias que tener tambien con que hacer izquierda-derecha/arriba-abajo, no solo play-pause-rewind-forward.
Hay teclados inalambricos que incluyen mouse, todo eso se podria hacer sin que el browser se entere de que no es un teclado/mouse real.

**Comment by LeandroBraier** [comment]
Claro, entiendo. El izquierda derecha etc es con el cardboard o el casco de
oculus, lo que nos contratan.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-05-05 19:13 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ah, entonces no hay una computadora realmente, esto se va a ver en un celular o casco, pero el tipo va a tener en la mano algo para parar/rebobinar. En tal caso ojo que al celular no se le puede poner cualquier cosa, habria que ver si no se venden controles remotos especificos para esto.

**Comment by LeandroBraier** [comment]
Claro. Complicado.  Mañana lo hablo con Eze a eso.

Abrazo y gracias!

**Comment by mkreyness** [comment]
Si es asi, no te puedo asegurar que funcione con un HTML5, porque una cosa es estar en un browser desktop y otra cosa un browser mobile. El cardboard en si es una aplicacion especifica, ni que hablar de Oculus.

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath Te paso un pedido urgente. Necesitamos que nos investigues como es la tecnología de realidad virtual colectiva que usan acá en Argentina, por ejemplo, en Temaiken o Tecnopolopis. Llevan grupos de chicos a una carpa, cada uno con un oculus pero todos ven el mismo video, centralizado y manejado por una especie de guía. Por fa averiguate lo que puedas de qué elementos usan y cómo lo hacen.

Acá te paso un ejemplo de explicación de un sistema pero muuuuucho más elaborado que esto.

http://www.xd-cinema.com/es/zhuoyuan-9d-vr-virtual-realitysimulator/

Cualquier consulta avisame.

abrazo

**Comment by ghost** [comment]
@LeandroBraier esto lo fui respondiendo por mail, pero por aca aclaro que en Tecnópolis  y Temaikén crean una experiencia 360 con una pantalla circular. No tiene relación con una experiencia inmersiva con un cardboard o cualquier casco VR

**Comment by LeandroBraier** [comment]
Gracias Valen!! Alertados entonces.
