### ISSUE TITLE
Cambiar Contraseñas Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#87]
@mkreyness habrá alguna forma de que cada usuario cambie la contraseña?

**Comment by mkreyness** [comment]
Estas hablando del mail ? No, me las tienen que pasar a mi.

**Comment by LeandroBraier** [comment]
Pero no es poco práctico? No hay alguna alternativa? Es un chino.

**Comment by mkreyness** [comment]
Si, es muy poco práctico.
Pero no conozco ningun servicio que permita que se cambie la contraseña desde el cliente de mail.
Son funciones del administrador del sitio, que es MS, y me lo delegó a mi.

**Comment by LeandroBraier** [comment]
Ok, te paso por este ticket entonces los pedidos jeje.

2016-09-08 19:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
lo mas complicado es sincronizar el cambio con los usuarios, avisales primero y recien cuando tengas confirmacion de que saben que tienen que cambiar la clave, me la pasas.

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! porfa cambiá la password de nicolas@benteveo.tv a **doremifasollasi** y avisame.

abrazo

**Comment by mkreyness** [comment]
Listo

**Comment by LeandroBraier** [comment]
Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mk
