### ISSUE TITLE
Mail Nuevo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#88]
@mkreyness necesito que me crees un mail nuevo: marino@benteveo.tv

Y que le pongas de password: b3nt3v30

Cuando lo tengas pasame porfa.

abrazo

**Comment by mkreyness** [comment]
Listo, avisame (siendo que es Marino) si necesita alguna quota especial de disco, porque el default es 1Gb.

**Comment by LeandroBraier** [comment]
No, 1gb está más que bien. Que él vaya borrando y listo. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
