### ISSUE TITLE
Investigar para futuras aplicaciones si puede ser util

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#89]
https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/

**Comment by ghost** [comment]
Puede ser una muy buena manera de generar páginas web y apps web para celu,
mas livianas que las aplicaciones nativas quizás

**Comment by LeandroBraier** [comment]
Genial Valen! Tengamoslo en el tintero por si surge la necesidad o el cliente.

abrazo
