### ISSUE TITLE
Landing Casting StoryDoingTV

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/BenteveoTV#9]
Buen día Fede!

Te paso un WeTransfer de donde podés bajar el PSD con el diseño de la landing para subir al sitio de Benteveo.Tv. El formulario lleva al siguiente mail: benteveotv@gmail.com

https://www.wetransfer.com/downloads/82484f0c64415523e7cd96a38441ae6c20140918004117/182dc70aee505fb0fcebba1fe1f8c87820140918004117/2895b4

Confirmame si llegás a tenerla maquetada y funcional para el viernes a la tarde así planeo el lanzamiento del casting.

En la carpeta "RIO ANCHO MAQUETADOR/Casting Benteveo" tenés la fuente Gobold, que es la que utilizamos en el PSD. Cualquier otra duda a tu disposición.

Lo ideal sería que la url sea: benteveo.tv/casting.

Trabajemos impactando directamente online, total en la home de Benteveo todavía no lo linkeamos.

abrazo

**Comment by FAAREIA** [comment]
Es más prioritario esto que lo de Río ancho?

2014-09-18 9:47 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Sip. Dale primera prioridad a esto. Después Rio Ancho, total para Rio Ancho recién vamos a tener las fotos definitivas la semana que viene.

**Comment by LeandroBraier** [comment]
El mensaje en pop up que aparece cuando se submite el formulario, debería decir esto:

"¡Gracias por dejarnos tus datos! Seguí el avance de esta convocatoria en nuestro muro de Facebook." y que la palabra "muro de Facebook" tenga el link "https://www.facebook.com/benteveoproducciones"

Una vez cerrado el pop up, que la lleve directamente al facebook de Benteveo, no a la home del sitio.

abrazo

**Comment by FAAREIA** [comment]
Lea, te mando algo sin terminar:
http://www.benteveo.tv/casting/

Fijate que la imagen queda muy grande, y el formulario lo modifiqué porque no se va a entender de que pueden subir 2 fotos, y también se tiene que notar que archivo subió. Ésto alargó el formulario, yo diria de ponerlo horizontal, con el texto arriba y sin foto, decime que opinas.

**Comment by LeandroBraier** [comment]
Entiendo lo que decís Fede. Poné todo mucho más chico: la cara de la chica,
el logo, todo. El formulario efectivamente hacelo como decís, en horizontal
y que quede claro qué archivo subiste y demás.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-18 14:46 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi subi una actualización lea, el formulario aún no anda. Tengo que hablar con MK

**Comment by LeandroBraier** [comment]
Gracias Fede! 

Mientras solucionás el tema formulario, te pido los siguientes cambios:

1) El friso de pantallas del fondo hacelo más grande, como estaba antes, para que no quede tanto blanco a los costados. El resto de las imágenes déjalas igual.

2) El Benteveo presenta cambiado de acuerdo al PSD que te paso aquí vía We Transfer:

https://www.wetransfer.com/downloads/17fe1f3b49abea914ab6d383e598f3c220140919142327/69985d

3) Agrégale los logos de Facebook, Twitter y YouTube que te paso también en ese mismo PSD.

4) Agrandá más el logo de SmartDoingTV y un poco más el slogan.

5) Fijate si podés agregar las manos que habías sacado

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/casting2/
El otro link lo esta laburando marce K
Los brazos no los puse porque necesitan estar en los extremos de la pantalla y encima que el dedo no quede apuntando a la nada. Logralo significaría que la imagen quede tan grande como antes, o quede un brazo desproporcional.

**Comment by FAAREIA** [comment]
en el link de youtube que va?

**Comment by LeandroBraier** [comment]
Nop, lo que te había pedido no era poner links a Facebook, Twitter y
YouTube abajo. Abrite el PSD que te mandé y vas a entender a qué me
refería. SIno avisame pero es otra cosa. Lo del ancho del friso y la foto
de la mina quedó perfecto. Solo falta cambiar el lugar del benteveo y
agregar los íconos de youtube, facebook y twitter sobre el friso como está
en ese PSD.

Igual está bueno que pusiste los íconos al pie. Cambiá el de YOuTube por
Vimeo y poné el canal de Benteveo ahí.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
ahhhh, ya me parecia raro. Había abierto el archivo anterior, jajajaja.

**Comment by FAAREIA** [comment]
Dale F5
http://www.benteveo.tv/casting2/

**Comment by LeandroBraier** [comment]
Muy bueno quedó!
1. Fijate si le podés sacar un poco el glow al logo de Twitter.
2. Meté el carrito en naranja de e-commerce adentro del friso, que no quede
   suelto.
3. No funciona aún el formulario, no?
4. Quitá el logito de twitter que lleva en este momento al vimeo pero no va
   a estar habilitado ese twitter para cuando lancemos esta landing.
5. Justificá todo los textos, que no queden centrado sino justificado.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ya anda el formulario, el mail es de info@benteveo.tv a info@benteveo.tv
http://www.benteveo.tv/casting/

Pregunta:
Los archivos quedan en una carpeta del FTP, son accesibles por cualquiera que conozca la URL. Sin embargo, si quieren más seguridad, se le puede pedir a Federico que le ponga usuario y clave a la carpeta.

**Comment by LeandroBraier** [comment]
Buenisimo Fede!

Una pregunta: ¿te acordás que te había pedido que derive a
benteveotv@gmail.com? No hay forma de hacer eso ¿no? En caso contrario, por
favor que quede todo con el mismo asunto: Casting StoryDoing TV. Por
seguridad no hay problema. Si no puede ir todo a gmail, pasame el acceso al
ftp así puedo ir vaciando regularmente las carpetas y que no se llene la
casilla tan fácil. Me refiero al acceso por un cliente FTP, no a través de
una URL web.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 17:44 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Otra pregunta: seguro que justificaste los textos?

Que queden bien alineados de ambos márgenes y con menos espacio entre un
párrafo ("Mejor que decir..." y "StoryDoing es un programa...").

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 17:54 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Che, probé el formulario y me dice: "Por favor completá todos los campos."

Yo había completado todo, salvo que el teléfono era cualquier número. Si es
un filtro, quitale ese filtro al formulario. Si en un casting ponés tu
teléfono mal te jodés. Lo mismo nombre. El mail si querés dejale el filtro
para que no nos spameen los hackers.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 17:57 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Si era obligatrio, ahora lo saco.
Me olvidé, el justificado no lo puse porque en la web van a quedar unos
espacios notables entre palabra y palabra, no es como los programas de
Adobe que son más inteligentes, aca es bruto.
Lo del mail se lo pregunto a Marce, pero lo que si estoy seguro es que a
Fede se le puede pedir que cree ua cuenta casting@benteveo.tv y que luego
redirija a gmail.com

**Comment by LeandroBraier** [comment]
No hace falta cambiar el mail, que quede el asunto Casting y listo.

Lo del justificado entiendo, decme de cuántos caracteres debería ser el
texto para que no queden los espacios y lo corregimos. No hay problema.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 18:47 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi te subi un ejemplo, asi nomás, de como queda el justificado. Pensá que
puedo poner: left, right, center o justify. Ninguna combinada.

**Comment by LeandroBraier** [comment]
Así quedó perfecto!

Quitale el espacio debajo de "que se ponen en acción" y estamos. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 18:55 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, te aviso cuando lo suba version responsiva

**Comment by FAAREIA** [comment]
Ya esta todo listo!

Abrazo

**Comment by LeandroBraier** [comment]
Genial. Estoy probando el formulario, me pasás la URL del ftp así accedo y
lo puedo chequear?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 19:22 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Otro error:

Cuando cerrás el pop up final de que cargaste bien el formulario, te
debería llevar a Facebook, no al sitio de Benteveo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 19:35 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
En el mail no estan los adjuntos, sino que te llega el link

**Comment by FAAREIA** [comment]
oka

**Comment by LeandroBraier** [comment]
Entiendo, pero yo no recibo copia de los mails que llegan a info@benteveo y
no tengo acceso a eso. Por eso te pedía que redirigieras al gmail. Ahí le
pregunté a Marce y a Eze, que ellos sí lo leen.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 19:42 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya esta listo lo del link de cerrar cuando manda bien el mail.

**Comment by LeandroBraier** [comment]
Fede, Eze lo probó de nuevo y parece que está funcionando bien ahora.

Lo único: mientras carga debería aparecer un cartel que te diga. Aguarde unos segundos mientras se carga la información, o algo asi. De lo contrario parece que no pasa nada y hay un error. Ponele un preloader con un mensaje que diga: "Subiendo archivos...10%" y que vaya aumentando el porcentaje.

**Comment by LeandroBraier** [comment]
Hola Fede! Quedó excelente y funciona perfecto la landing. Te pido una cosita más y ya cerramos este tema.

Necesito que le sumes un campo de texto más para poner un link. El título del campo sería 

URL/LINK (Sitio Web/Reel/Blog/etc)

Avisame cuando esté.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya lo agregué lea, denle una última probada al formulario.
Abrazo

**Comment by LeandroBraier** [comment]
Probado! Quedó muy bien.

Gracias.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
